const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

(async () => {
  const { SqlitePlatformRepository } = await import("../src/persistence/sqlitePlatformRepository.mjs");
  const { analyzeMarketComparables } = await import("../src/underwriting/marketComparables.mjs");
  const { createAcquisitionHandoffWorkflow } = await import("../src/intelligence/acquisitionHandoffWorkflow.mjs");
  const organizationId = "org-acquisition-handoff";
  const countyId = "dallas-county-dcad";
  const propertyId = `wrp:v1:${countyId}:HANDOFF-1`;
  let now = "2026-08-24T16:00:00.000Z";
  const context = { organizationId, actorUserId: "analyst-writer", subjectUserId: "analyst-writer", sessionId: "handoff-session", requestId: "handoff-request", grants: ["persistence:read", "persistence:write", "acquisition-handoff:create"], issuedAt: "2026-08-24T15:00:00.000Z", expiresAt: "2026-08-26T17:00:00.000Z" };
  const decision = { schemaVersion: "wr-opportunity-decision-v1", id: "decision_priority_1", organizationId, whiteRabbitPropertyId: propertyId, asOf: "2026-08-24T15:55:00.000Z", disposition: "analyst-review-priority", model: { id: "acquisition-priority", version: "2026.08", validationStatus: "validated" }, predictiveScore: { schemaVersion: "wr-explainable-signal-score-v1", validationStatus: "validated", status: "scored", netScore: 90, effectiveConfidence: 1, evidenceCoveragePct: 100, factors: [{ metric: "demand-index", points: 90 }] }, heuristicSignal: { schemaVersion: "wr-opportunity-signal-v1", tier: "high", score: 85, missingEvidence: [] }, sourceEvidence: [{ sourceCountyId: countyId, datasetId: "certified-opportunity-fixture", sourceVersion: "2026.08.24", sourceUpdatedAt: "2026-08-24T15:55:00.000Z", freshnessStatus: "current", partial: false }], certification: { expiresAt: "2026-12-31T00:00:00.000Z", modelSha256: "a".repeat(64), backtestSha256: "b".repeat(64), driftSha256: "c".repeat(64) }, advisoryOnly: true };
  const profile = { schemaVersion: "wr-property-profile-v1", whiteRabbitPropertyId: propertyId, accountNum: "HANDOFF-1", asOf: now, parcel: { whiteRabbitPropertyId: propertyId, accountNum: "HANDOFF-1", siteAddress: "100 Rabbit Way", ownerName: "RABBIT LAND LLC", ownershipTenureYears: 12, landAreaSize: 8, landAreaUnit: "ACRE", totalValue: 1100000, yearBuilt: 2005 }, intelligence: { zoning: { code: "MU-2", sourceDatasetId: "dallas-zoning", sourceAsOf: now }, floodplain: { designation: "outside", sourceDatasetId: "fema", sourceAsOf: now }, development: { signalCount: 1, sourceDatasetId: "dallas-permits", latestActivityDate: "2026-08-01" } }, evidence: { layerStatus: { permits: "not-found" }, permitCount: 0, errors: [] }, lineage: { sourceDatasetId: "dcad-2026", sourceVersion: "2026", sourceUpdatedAt: now, sourceAsOf: now, freshnessStatus: "current" } };
  const subject = { whiteRabbitPropertyId: propertyId, propertyType: "office", location: { latitude: 32.7767, longitude: -96.797 }, buildingSqFt: 10000, yearBuilt: 2005 };
  const comparables = [0, 1, 2].map((index) => ({ id: `rent-${index + 1}`, comparableType: "rent", propertyType: "office", transactionDate: `2026-0${7 - index}-01T00:00:00.000Z`, location: { latitude: 32.7767 + index * 0.005, longitude: -96.797 - index * 0.005 }, economics: { annualRent: 230000 + index * 10000, buildingSqFt: 9500 + index * 500 }, yearBuilt: 2000 + index * 3, source: { datasetId: "licensed-feed", recordId: `rent-${index + 1}`, sourceUrl: "https://data.example", licenseId: "license-1", licenseStatus: "authorized", observedAt: "2026-08-01T00:00:00.000Z", availableAt: "2026-08-02T00:00:00.000Z", expiresAt: "2026-12-31T00:00:00.000Z", sourceFields: {} } }));
  const rentAnalysis = analyzeMarketComparables({ analysisType: "rent", analysisAsOf: now, subject, comparables, selectionPolicy: { minComparableCount: 3 }, adjustmentPolicy: { annualMarketGrowthPct: { value: 3, source: "licensed-index", asOf: now }, sizeElasticityPct: { value: -5, source: "approved-policy", asOf: now }, ageAdjustmentPctPerYear: { value: 0.1, source: "approved-policy", asOf: now } } });
  assert.equal(rentAnalysis.status, "adjusted-estimate");
  let evidenceAsOf = now;
  const profileProvider = { schemaVersion: "wr-acquisition-handoff-profile-provider-v1", activationAuthorized: true, async getProfile() { return structuredClone(profile); } };
  const underwritingEvidenceProvider = { schemaVersion: "wr-underwriting-evidence-provider-v1", activationAuthorized: true, async getEvidence() { return { schemaVersion: "wr-underwriting-evidence-pack-v1", activationAuthorized: true, evidenceAsOf, assumptionInput: { purchasePrice: 1000000, rentableAreaSqFt: 10000, rentPerSqFtAnnual: rentAnalysis.estimate.weightedUnitValue, exitCapRatePct: 7 }, comparableAnalyses: [rentAnalysis], requiredComparableTypes: ["rent"] }; } };
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "white-rabbit-acquisition-handoff-"));
  const databasePath = path.join(tempDir, "handoff.sqlite");
  const repository = new SqlitePlatformRepository({ filename: databasePath, clock: () => now });
  repository.commit({ context, namespace: "opportunity-intelligence", key: `property:${propertyId}`, value: { schemaVersion: "wr-opportunity-decision-ledger-v1", organizationId, whiteRabbitPropertyId: propertyId, revision: 2, decisions: [decision], updatedAt: decision.asOf }, expectedTenantRevision: 0, expectedRecordRevision: 0, idempotencyKey: "seed-priority-decision", occurredAt: decision.asOf }, { now: decision.asOf });
  const releases = ["opportunity-briefs", "scenario-underwriting"].map((capabilityId) => ({ schemaVersion: "wr-capability-release-decision-v1", capabilityId, activationAuthorized: true }));
  const verified = () => ({ valid: true, activationAuthorized: true });
  const workflow = createAcquisitionHandoffWorkflow({ repository, allowedCountyIds: [countyId], releaseDecisions: releases, verifyReleaseDecision: verified, profileProvider, underwritingEvidenceProvider, verifyProvider: verified, verifyUnderwritingEvidence: verified, clock: () => now });
  assert.equal(workflow.activationAuthorized, true);
  const inactive = createAcquisitionHandoffWorkflow({ repository, allowedCountyIds: [countyId] });
  await assert.rejects(() => inactive.create({}, context), (error) => error.code === "WR_ACQUISITION_HANDOFF_INACTIVE");
  const input = { whiteRabbitPropertyId: propertyId, asOf: now, expectedTenantRevision: 1, expectedHandoffRecordRevision: 0, expectedUnderwritingRecordRevision: 0, idempotencyKey: "create-handoff-1" };
  const unverifiedEvidence = createAcquisitionHandoffWorkflow({ repository, allowedCountyIds: [countyId], releaseDecisions: releases, verifyReleaseDecision: verified, profileProvider, underwritingEvidenceProvider, verifyProvider: verified });
  await assert.rejects(() => unverifiedEvidence.create({ ...input, idempotencyKey: "unverified-evidence" }, context), (error) => error.code === "WR_UNDERWRITING_EVIDENCE_SIGNATURE_REJECTED");
  assert.equal(repository.tenantRevision(context, { now }), 1, "rejected evidence must not mutate durable state");
  const created = await workflow.create(input, context);
  assert.equal(created.status, "created");
  assert.equal(created.receipt.mutationCount, 2);
  assert.deepEqual(created.receipt.records.map((item) => item.namespace).sort(), ["acquisition-handoff", "underwriting"]);
  assert.equal(created.handoff.sourceDecisionId, decision.id);
  assert.equal(created.handoff.status, "draft-pending-independent-review");
  assert.equal(created.handoff.advisoryOnly, true);
  assert.equal(created.handoff.exportAuthorized, false);
  assert.equal(created.handoff.approvalAuthorized, false);
  assert.equal(created.handoff.brief.whiteRabbitPropertyId, propertyId);
  assert.notEqual(created.handoff.brief.status, "insufficient-evidence");
  assert.equal(created.scenario.status, "draft");
  assert.equal(created.scenario.requiredComparableTypes[0], "rent");
  assert.match(created.scenario.evidenceDigest, /^[a-f0-9]{64}$/);
  const tenantBeforeReplay = repository.tenantRevision(context, { now });
  const replay = await workflow.create(input, context);
  assert.equal(replay.status, "replayed");
  assert.equal(replay.handoff.id, created.handoff.id);
  assert.equal(repository.tenantRevision(context, { now }), tenantBeforeReplay);
  await assert.rejects(() => workflow.create({ ...input, asOf: "2026-08-24T16:01:00.000Z" }, context), (error) => error.code === "WR_IDEMPOTENCY_CONFLICT");
  await assert.rejects(() => workflow.create({ ...input, expectedTenantRevision: 2, expectedHandoffRecordRevision: 1, expectedUnderwritingRecordRevision: 1, idempotencyKey: "duplicate-handoff" }, context), (error) => error.code === "WR_ACQUISITION_HANDOFF_DUPLICATE");
  const staleWorkflow = createAcquisitionHandoffWorkflow({ repository, allowedCountyIds: [countyId], releaseDecisions: releases, verifyReleaseDecision: verified, profileProvider, underwritingEvidenceProvider, verifyProvider: verified, verifyUnderwritingEvidence: verified, maximumDecisionAgeHours: 1 });
  await assert.rejects(() => staleWorkflow.create({ ...input, asOf: "2026-08-24T17:00:01.000Z", expectedTenantRevision: 2, expectedHandoffRecordRevision: 1, expectedUnderwritingRecordRevision: 1, idempotencyKey: "stale-decision" }, context), (error) => error.code === "WR_OPPORTUNITY_DECISION_STALE");
  const unverified = createAcquisitionHandoffWorkflow({ repository, allowedCountyIds: [countyId], releaseDecisions: releases, verifyReleaseDecision: verified, profileProvider, underwritingEvidenceProvider });
  await assert.rejects(() => unverified.create({ ...input, expectedTenantRevision: 2, expectedHandoffRecordRevision: 1, expectedUnderwritingRecordRevision: 1, idempotencyKey: "unverified-provider" }, context), (error) => error.code === "WR_ACQUISITION_HANDOFF_PROVIDER_INACTIVE");
  const ledger = repository.readRecord(context, "acquisition-handoff", `property:${propertyId}`, { now }).value;
  const governance = repository.readRecord(context, "underwriting", "governance-state", { now }).value;
  assert.equal(ledger.handoffs.length, 1);
  assert.equal(governance.scenarios.length, 1);
  assert.equal(governance.reviews.length, 0);
  assert.equal(governance.approvals.length, 0, "handoff must never manufacture review or approval evidence");
  assert.equal(JSON.stringify(ledger).includes("Secret"), false);
  const audit = repository.exportAuditLog(context, { now, exportedAt: now });
  assert.equal(audit.verification.valid, true);
  repository.close();
  for (const suffix of ["", "-wal", "-shm"]) { const target = `${databasePath}${suffix}`; if (fs.existsSync(target)) fs.rmSync(target); }
  fs.rmdirSync(tempDir);
  assert.equal(fs.readFileSync(path.join(__dirname, "..", "src", "App.tsx"), "utf8").includes("acquisitionHandoffWorkflow"), false);
  if (process.env.WR_HANDOFF_CERTIFICATION_CHILD !== "1") {
    execFileSync(process.execPath, [path.join(__dirname, "..", "scripts", "build-acquisition-handoff-readiness.cjs")], { stdio: "inherit" });
    require("./acquisition-handoff-readiness.test.cjs");
  }
  console.log("White Rabbit governed opportunity-to-brief underwriting handoff, atomic persistence, replay, freshness, and human-approval boundary tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
