const assert = require("assert");
const fs = require("fs");
const path = require("path");

(async () => {
  const zoning = await import("../src/operations/countyZoningIntelligence.mjs");
  const sha = zoning.countyZoningSha256;
  const base = { countyId: "test-county", publisher: "Official City", serviceUrl: "https://official.example/Zoning/MapServer", layerUrl: "https://official.example/Zoning/MapServer/0", layerName: "Zoning", geometryType: "esriGeometryPolygon", spatialReference: "EPSG:4326", identityField: "OBJECTID", identityUniqueness: "unverified", featureCount: 10, nonNullCounts: { OBJECTID: 10, DISTRICT: 10, BASE: 8, EFFECTIVE: 4 }, taxonomyTupleCount: 3, metadataSha256: sha("meta"), countResponseSha256: sha("count"), completenessResponseSha256: sha("complete"), taxonomyResponseSha256: sha("taxonomy"), observedAt: "2026-08-23" };
  const current = zoning.createCountyZoningSourceProbe({ ...base, sourceId: "city-a-current", sourceRole: "current-zoning", jurisdictionIds: ["city-a"], coverageStatement: "City A current zoning", temporalCoverage: "current; dates incomplete", districtField: "DISTRICT", baseDistrictField: "BASE", effectiveDateField: "EFFECTIVE" });
  const overlay = zoning.createCountyZoningSourceProbe({ ...base, sourceId: "city-a-overlay", sourceRole: "overlay", jurisdictionIds: ["city-a"], coverageStatement: "City A overlays", temporalCoverage: "current", districtField: "", baseDistrictField: "", effectiveDateField: "" });
  const cases = zoning.createCountyZoningSourceProbe({ ...base, sourceId: "city-a-cases", sourceRole: "zoning-case", jurisdictionIds: ["city-a"], coverageStatement: "City A cases", temporalCoverage: "rolling three years", districtField: "", baseDistrictField: "", effectiveDateField: "" });
  assert.equal(current.metadataReady, true);
  assert.equal(current.nullDistrictCount, 0);
  assert.equal(current.captureAuthorized, false);
  const coverage = zoning.reconcileCountyZoningCoverage({ countyId: "test-county", jurisdictionUniverseIds: ["city-a", "city-b", "unincorporated"], probes: [current, overlay, cases] });
  assert.deepEqual(coverage.discoveredCurrentZoningJurisdictionIds, ["city-a"]);
  assert.deepEqual(coverage.certifiedCurrentZoningJurisdictionIds, []);
  assert.deepEqual(coverage.overlaySourceIds, ["city-a-overlay"]);
  assert.deepEqual(coverage.caseSourceIds, ["city-a-cases"]);
  const blocked = zoning.createCountyZoningSnapshotPolicy({ countyId: "test-county", sourceProbeSha256: current.probeSha256, identityUniqueness: current.identityUniqueness, nullDistrictCount: current.nullDistrictCount, effectiveAt: "2026-08-23" });
  assert.equal(blocked.status, "blocked");
  const ready = zoning.createCountyZoningSnapshotPolicy({ countyId: "test-county", sourceProbeSha256: current.probeSha256, identityUniqueness: "verified-unique", nullDistrictCount: 0, jurisdictionBoundarySnapshotSha256: sha("boundary"), effectiveAt: "2026-08-23", rights: ["store", "derive", "query"], rightsEvidenceRef: "artifact://license", approvalRefs: ["approval://planning", "approval://quality"] });
  assert.equal(ready.status, "capture-authorized");
  const unmapped = zoning.createCountyZoningDistrictDefinition({ jurisdictionId: "city-a", districtCode: "R1", districtLabel: "Residential One", broadUseCategory: "residential", officialDefinitionRef: "https://official.example/code/R1", sourceSnapshotSha256: sha("snapshot") });
  assert.equal(unmapped.broadUseCategory, "unmapped", "Broad use must not be inferred without mapping evidence");
  const mapped = zoning.createCountyZoningDistrictDefinition({ jurisdictionId: "city-a", districtCode: "R1", districtLabel: "Residential One", broadUseCategory: "residential", officialDefinitionRef: "https://official.example/code/R1", mappingEvidenceRef: "artifact://mapping/R1", sourceSnapshotSha256: sha("snapshot") });
  assert.equal(mapped.broadUseCategory, "residential");
  const baseAssignment = { countyId: "test-county", countyParcelId: "P-1", jurisdictionId: "city-a", zoningSnapshotSha256: sha("snapshot"), effectiveAt: "2026-08-23", zoningSnapshotCertified: true, jurisdictionAssignmentCertified: true, parcelGeometryValid: true };
  const assigned = zoning.assignParcelZoning({ ...baseAssignment, intersections: [{ sourceFeatureId: "Z1", districtCode: "R1", baseDistrictCode: "R1", intersectionRatio: 0.4, containsCentroid: true }, { sourceFeatureId: "Z2", districtCode: "R1", baseDistrictCode: "R1", intersectionRatio: 0.2, containsCentroid: false }, { sourceFeatureId: "Z3", districtCode: "C1", baseDistrictCode: "C1", intersectionRatio: 0.4, containsCentroid: false }], overlays: ["airport"], pendingCaseIds: ["CASE-1"] });
  assert.equal(assigned.primaryDistrictCode, "R1");
  assert.equal(assigned.splitParcel, true);
  assert.equal(assigned.districts.find((item) => item.districtCode === "R1").intersectionRatio, 0.6);
  assert.deepEqual(assigned.overlays, ["airport"]);
  assert.deepEqual(assigned.pendingCaseIds, ["CASE-1"]);
  const ambiguous = zoning.assignParcelZoning({ ...baseAssignment, intersections: [{ sourceFeatureId: "A", districtCode: "R1", intersectionRatio: 0.5, containsCentroid: true }, { sourceFeatureId: "B", districtCode: "C1", intersectionRatio: 0.5, containsCentroid: true }] });
  assert.equal(ambiguous.ambiguous, true);
  assert.equal(ambiguous.ambiguityReason, "multiple-centroid-districts");
  const uncertified = zoning.assignParcelZoning({ ...baseAssignment, zoningSnapshotCertified: false, intersections: [{ sourceFeatureId: "A", districtCode: "R1", intersectionRatio: 1, containsCentroid: true }] });
  assert.equal(uncertified.primaryDistrictCode, "");
  assert.equal(uncertified.ambiguityReason, "zoning-snapshot-not-certified");
  const audit = zoning.createCountyZoningAssignmentAudit({ countyId: "test-county", jurisdictionId: "city-a", zoningSnapshotSha256: sha("snapshot"), parcelManifestSha256: sha("parcels"), zoningSnapshotCertified: true, jurisdictionAssignmentsCertified: true, maximumAmbiguousCount: 0, counts: { parcels: 100, assigned: 90, split: 5, ambiguous: 0, unmatched: 8, invalid: 2, missingDefinition: 0 }, evaluatedAt: "2026-08-23" });
  assert.equal(audit.status, "certified");
  const rejected = zoning.createCountyZoningAssignmentAudit({ ...audit, counts: { parcels: 100, assigned: 89, split: 5, ambiguous: 1, unmatched: 8, invalid: 2, missingDefinition: 0 }, maximumAmbiguousCount: 0 });
  assert.equal(rejected.status, "rejected");
  const schema = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/schemas/county-zoning-intelligence.schema.json"), "utf8"));
  assert.equal(schema.$defs.assignment.properties.schemaVersion.const, zoning.COUNTY_PARCEL_ZONING_ASSIGNMENT_VERSION);
  const gates = fs.readFileSync(path.join(__dirname, "../src/data/platformFeatureGates.ts"), "utf8");
  for (const gate of ["countyZoningSourceFederation", "countyZoningGeometryCapture", "countyZoningParcelAssignment", "countyZoningTemporalHistory", "countyZoningCaseMonitoring"]) assert(gates.includes(`${gate}: false`));
  console.log("White Rabbit zoning roles, district evidence, split-parcel assignment, and exact audit tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
