const assert = require("assert");
const fs = require("fs");
const path = require("path");

(async () => {
  const development = await import("../src/operations/countyDevelopmentIntelligence.mjs");
  const sha = development.countyDevelopmentSha256;
  const candidate = development.createCountyDevelopmentFeedBinding({ countyId: "test-county", sourceId: "city-permits", publisher: "Official City", feedRole: "permit-event", jurisdictionIds: ["city-a"], temporalCoverage: "rolling three years", upstreamContractVersion: "wr-test-v1", upstreamProbeSha256: sha("probe"), candidateRecordCount: 100 });
  assert.equal(candidate.status, "candidate-only");
  assert.equal(candidate.candidateRecordsAreSignals, false);
  assert.equal(candidate.emittedSignalCount, 0);
  assert.throws(() => development.createCountyDevelopmentFeedBinding({ ...candidate, feedRole: "marketing-lead" }), /Unsupported/);
  const certified = development.createCountyDevelopmentFeedBinding({ countyId: "test-county", sourceId: "city-cases", publisher: "Official City", feedRole: "zoning-case", jurisdictionIds: ["city-a"], temporalCoverage: "full", upstreamContractVersion: "wr-test-v1", upstreamProbeSha256: sha("probe-2"), candidateRecordCount: 20, upstreamCaptureCertified: true, upstreamNormalizationCertified: true, jurisdictionBoundaryCertified: true, reuseRightsCertified: true });
  assert.equal(certified.status, "feed-certified");
  const coverage = development.reconcileCountyDevelopmentCoverage({ countyId: "test-county", jurisdictionUniverseIds: ["city-a", "city-b"], bindings: [candidate, certified] });
  assert.equal(coverage.candidateRecordCount, 120);
  assert.deepEqual(coverage.discoveredJurisdictionIds, ["city-a"]);
  assert.deepEqual(coverage.certifiedJurisdictionIds, ["city-a"]);
  assert.deepEqual(coverage.uncoveredOrUncertifiedJurisdictionIds, ["city-b"]);
  assert(coverage.rules.includes("zoning-case-never-proves-construction"));
  const draftRule = development.createCountyDevelopmentClassificationRule({ ruleId: "new-build", ruleVersion: "1", feedRole: "permit-event", signalType: "new-construction", lifecycleStage: "construction", conditions: [{ field: "category", operator: "equals", value: "new" }], exclusions: [{ field: "status", operator: "equals", value: "void" }], officialDefinitionRef: "artifact://definition", approvedByRefs: [] });
  assert.equal(draftRule.status, "draft");
  assert.equal(draftRule.modelGenerated, false);
  const approvedRule = development.createCountyDevelopmentClassificationRule({ ...draftRule, approvedByRefs: ["approval://data", "approval://quality"] });
  assert.equal(approvedRule.status, "approved");
  assert.throws(() => development.createCountyDevelopmentClassificationRule({ ...draftRule, conditions: [] }), /explicit classification condition/);
  const incomplete = development.createNormalizedCountyDevelopmentEvent({ countyId: "test-county", jurisdictionId: "city-a", sourceId: "city-permits", sourceRecordId: "P-1", sourceSnapshotSha256: sha("snapshot"), sourceRecordSha256: sha("record"), classificationRuleSha256: approvedRule.ruleSha256, signalType: "new-construction", lifecycleStage: "construction", occurredAt: "2026-08-23", parcelLinkStatus: "ambiguous", evidenceRefs: ["artifact://record"] });
  assert.equal(incomplete.eligibleAsSignal, false);
  assert.throws(() => development.createNormalizedCountyDevelopmentEvent({ ...incomplete, activate: true }), /Uncertified/);
  assert.throws(() => development.createNormalizedCountyDevelopmentEvent({ ...incomplete, parcelLinkStatus: "direct", countyParcelId: "" }), /countyParcelId/);
  const eligible = development.createNormalizedCountyDevelopmentEvent({ countyId: "test-county", jurisdictionId: "city-a", sourceId: "city-permits", sourceRecordId: "P-2", sourceSnapshotSha256: sha("snapshot"), sourceRecordSha256: sha("record-2"), classificationRuleSha256: approvedRule.ruleSha256, signalType: "new-construction", lifecycleStage: "construction", occurredAt: "2026-08-23", parcelLinkStatus: "direct", countyParcelId: "A-1", sourceSnapshotCertified: true, normalizationCertified: true, classificationRuleApproved: true, parcelLinkCertified: true, evidenceRefs: ["artifact://record-2"], activate: true });
  assert.equal(eligible.status, "certified-signal");
  const audit = development.createCountyDevelopmentSignalAudit({ countyId: "test-county", jurisdictionId: "city-a", counts: { candidateRecords: 100, normalizedEvents: 70, ineligibleRecords: 20, duplicateRecords: 5, invalidRecords: 5, linkedEvents: 50, unmatchedEvents: 10, ambiguousEvents: 5, conflictEvents: 5, emittedSignals: 40, suppressedLinkedEvents: 10 }, sourceCaptureCertified: true, classificationRulesCertified: true, parcelLinksCertified: true, lineageCertified: true, evaluatedAt: "2026-08-23" });
  assert.equal(audit.status, "certified");
  const badAudit = development.createCountyDevelopmentSignalAudit({ countyId: "test-county", jurisdictionId: "city-a", counts: { candidateRecords: 100, normalizedEvents: 70, ineligibleRecords: 20, duplicateRecords: 5, invalidRecords: 4, linkedEvents: 50, unmatchedEvents: 10, ambiguousEvents: 5, conflictEvents: 5, emittedSignals: 40, suppressedLinkedEvents: 10 }, sourceCaptureCertified: true, classificationRulesCertified: true, parcelLinksCertified: true, lineageCertified: true, evaluatedAt: "2026-08-23" });
  assert.equal(badAudit.status, "rejected");
  const blockedManifest = development.createCountyDevelopmentIndexManifest({ countyId: "test-county", parcelManifestSha256: "", signalAuditSha256: badAudit.auditSha256, parcelCount: 0, signalCount: 0, approvalRefs: [] });
  assert.equal(blockedManifest.activationAuthorized, false);
  const schema = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/schemas/county-development-intelligence.schema.json"), "utf8"));
  assert.equal(schema.$defs.event.properties.schemaVersion.const, development.NORMALIZED_COUNTY_DEVELOPMENT_EVENT_VERSION);
  const gates = fs.readFileSync(path.join(__dirname, "../src/data/platformFeatureGates.ts"), "utf8");
  for (const gate of ["countyDevelopmentSourceFederation", "countyDevelopmentEventNormalization", "countyDevelopmentParcelLinking", "countyDevelopmentLifecycleAggregation", "countyDevelopmentSignalActivation"]) assert(gates.includes(`${gate}: false`));
  console.log("White Rabbit county development evidence, classification, exact partitions, and activation gates passed.");
})().catch((error) => { console.error(error); process.exit(1); });
