const assert = require("assert");
const fs = require("fs");
const path = require("path");

(async () => {
  const flood = await import("../src/operations/countyFloodIntelligence.mjs");
  const sha = flood.countyFloodSha256;
  const base = { countyId: "test-county", publisher: "Official County / FEMA", serviceUrl: "https://official.example/Flood/MapServer", layerUrl: "https://official.example/Flood/MapServer/0", layerName: "Flood Hazards", sourceIdField: "FLD_AR_ID", zoneField: "FLD_ZONE", sfhaField: "SFHA_TF", geometryType: "esriGeometryPolygon", spatialReference: "EPSG:4326", featureCount: 3, nonNullSourceIdCount: 3, sourceIdUniqueness: "unverified", zoneTuples: [{ zone: "A", sfhaFlag: "T", versionId: "1" }, { zone: "X", sfhaFlag: "F", versionId: "1" }], metadataSha256: sha("metadata"), countResponseSha256: sha("count"), identityCountResponseSha256: sha("identity"), taxonomyResponseSha256: sha("taxonomy"), observedAt: "2026-08-23" };
  const regulatory = flood.createCountyFloodSourceProbe({ ...base, sourceId: "regulatory", role: "regulatory-candidate" });
  const estimated = flood.createCountyFloodSourceProbe({ ...base, sourceId: "estimate", role: "planning-estimate-only", sourceIdField: "EST_AR_ID" });
  const historical = flood.createCountyFloodSourceProbe({ ...base, sourceId: "legacy", role: "historical-only" });
  assert.equal(regulatory.metadataReady, true);
  assert.equal(regulatory.captureAuthorized, false);
  assert.equal(flood.normalizeFloodZone("Floodway", "T").riskTier, "extreme");
  assert.equal(flood.normalizeFloodZone("AE", "T").sfha, true);
  assert.equal(flood.normalizeFloodZone("X", "F").sfha, false);
  assert.equal(flood.normalizeFloodZone("mystery", "T").taxonomyKnown, false);
  const blocked = flood.reconcileCountyFloodSources({ countyId: "test-county", probes: [regulatory, estimated, historical] });
  assert.equal(blocked.status, "blocked");
  assert(blocked.blockers.includes("regulatory-source-id-uniqueness-unverified"));
  assert(blocked.blockers.includes("regulatory-geometry-capture-not-authorized"));
  assert.equal(blocked.planningEstimateSourceIds[0], "estimate");
  assert.equal(blocked.historicalSourceIds[0], "legacy");
  const selected = flood.reconcileCountyFloodSources({ countyId: "test-county", probes: [{ ...regulatory, sourceIdUniqueness: "verified-unique", captureAuthorized: true }, estimated, historical] });
  assert.equal(selected.status, "selected");
  const policyBlocked = flood.createCountyFloodSnapshotPolicy({ countyId: "test-county", reconciliationSha256: blocked.reconciliationSha256, reconciliationStatus: blocked.status, sourceProbeSha256: regulatory.probeSha256, sourceIdUniqueness: regulatory.sourceIdUniqueness, effectiveAt: "2026-08-23" });
  assert.equal(policyBlocked.status, "blocked");
  const policyReady = flood.createCountyFloodSnapshotPolicy({ countyId: "test-county", reconciliationSha256: selected.reconciliationSha256, reconciliationStatus: selected.status, sourceProbeSha256: regulatory.probeSha256, sourceIdUniqueness: "verified-unique", effectiveAt: "2026-08-23", countyBoundarySnapshotSha256: sha("boundary"), rights: ["store", "derive", "query"], rightsEvidenceRef: "artifact://license", approvalRefs: ["approval://gis", "approval://governance"] });
  assert.equal(policyReady.status, "capture-authorized");
  const classificationBase = { countyId: "test-county", countyParcelId: "P-1", sourceSnapshotSha256: sha("snapshot"), effectiveAt: "2026-08-23", sourceSnapshotCertified: true, parcelGeometryValid: true };
  const classified = flood.classifyParcelFloodRisk({ ...classificationBase, intersections: [{ sourceFeatureId: "F1", zone: "AE", sfhaFlag: "T", intersectionRatio: 0.4, containsCentroid: true }, { sourceFeatureId: "F2", zone: "AE", sfhaFlag: "T", intersectionRatio: 0.2, containsCentroid: false }, { sourceFeatureId: "F3", zone: "Floodway", sfhaFlag: "T", intersectionRatio: 0.1, containsCentroid: false }, { sourceFeatureId: "F4", zone: "X", sfhaFlag: "F", intersectionRatio: 0.8, containsCentroid: false }] });
  assert.equal(classified.primaryZone, "FLOODWAY");
  assert.equal(classified.primaryRiskTier, "extreme");
  assert.equal(classified.sfha, true);
  assert.equal(classified.floodway, true);
  assert.equal(classified.zones.find((item) => item.canonicalZone === "AE").intersectionRatio, 0.6);
  assert(classified.disclaimer.includes("not a FEMA flood-zone determination"));
  const unknown = flood.classifyParcelFloodRisk({ ...classificationBase, intersections: [{ sourceFeatureId: "U", zone: "mystery", sfhaFlag: "T", intersectionRatio: 1, containsCentroid: true }] });
  assert.equal(unknown.ambiguous, true);
  assert.equal(unknown.ambiguityReason, "unknown-zone");
  const uncertified = flood.classifyParcelFloodRisk({ ...classificationBase, sourceSnapshotCertified: false, intersections: [{ sourceFeatureId: "F", zone: "X", sfhaFlag: "F", intersectionRatio: 1, containsCentroid: true }] });
  assert.equal(uncertified.primaryZone, "");
  assert.equal(uncertified.ambiguityReason, "source-snapshot-not-certified");
  assert.throws(() => flood.createCountyFloodSourceProbe({ ...base, sourceId: "bad", role: "unsupported" }), /Unsupported/);
  const schema = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/schemas/county-flood-intelligence.schema.json"), "utf8"));
  assert.equal(schema.$defs.classification.properties.schemaVersion.const, flood.COUNTY_PARCEL_FLOOD_CLASSIFICATION_VERSION);
  const gates = fs.readFileSync(path.join(__dirname, "../src/data/platformFeatureGates.ts"), "utf8");
  for (const gate of ["countyFloodSourceReconciliation", "countyFloodGeometryCapture", "countyFloodParcelClassification", "countyFloodTemporalHistory"]) assert(gates.includes(`${gate}: false`));
  console.log("White Rabbit flood source roles, taxonomy, capture policy, and fail-closed parcel classification tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
