const assert = require("assert");
const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

(async () => {
  const tiles = await import("../src/operations/countyTileDelivery.mjs");
  const sha = tiles.countyTileSha256;
  const sourceInput = { countyId: "test-county", countyFips: "00001", parcelManifestPath: "public/data/counties/test/parcels/manifest.json", parcelManifestSha256: sha("manifest"), searchIndexSha256: sha("search"), chunkInventorySha256: sha("chunks"), lineageLedgerRootSha256: sha("ledger"), counts: { official: 100, manifest: 100, chunks: 100, search: 100 }, chunkCount: 4, searchShardCount: 2, bounds: { minLng: -98, minLat: 32, maxLng: -97, maxLat: 33 }, outputLineageCertified: true, sourceToOutputCertified: false };
  const blockedSource = tiles.createCountyTileSourceBundle(sourceInput);
  assert.equal(blockedSource.status, "blocked");
  const source = tiles.createCountyTileSourceBundle({ ...sourceInput, sourceToOutputCertified: true });
  assert.equal(source.status, "certified");
  const drift = tiles.createCountyTileSourceBundle({ ...sourceInput, counts: { ...sourceInput.counts, chunks: 99 }, sourceToOutputCertified: true });
  assert.equal(drift.status, "blocked");
  const draftPolicy = tiles.createCountyTilePropertyPolicy({ countyId: "test-county", includedFields: ["countyParcelId", "address"], approvalRefs: [] });
  assert.equal(draftPolicy.status, "draft");
  const unsafePolicy = tiles.createCountyTilePropertyPolicy({ countyId: "test-county", includedFields: ["countyParcelId", "ownerEmail"], approvalRefs: ["a", "b"] });
  assert.equal(unsafePolicy.status, "draft");
  assert.deepEqual(unsafePolicy.forbiddenIncluded, ["ownerEmail"]);
  const policy = tiles.createCountyTilePropertyPolicy({ countyId: "test-county", includedFields: ["countyParcelId", "address"], approvalRefs: ["a", "b"] });
  assert.equal(policy.status, "approved");
  const planBase = { countyId: "test-county", sourceBundleSha256: source.bundleSha256, propertyPolicySha256: policy.policySha256, streamCommand: "node stream.cjs", layerId: "parcels", minZoom: 10, maxZoom: 16, outputPath: "output/test.pmtiles", artifactManifestPath: "output/test.pmtiles.manifest.json", outputPathGuarded: true };
  const blockedPlan = tiles.createCountyTileBuildPlan(planBase);
  assert.equal(blockedPlan.status, "blocked");
  const plan = tiles.createCountyTileBuildPlan({ ...planBase, sourceBundleCertified: true, propertyPolicyApproved: true, reuseRightsCertified: true, tippecanoeVerified: true, tippecanoeVersion: "tippecanoe v2" });
  assert.equal(plan.status, "build-authorized");
  const counts = { sourceFeatures: 100, streamedFeatures: 99, tiledFeatures: 99, excludedFeatures: 0, invalidFeatures: 1 };
  const audit = tiles.createCountyTileArtifactAudit({ countyId: "test-county", buildPlanSha256: plan.planSha256, counts, artifactPath: "output/test.pmtiles", artifactBytes: 1000, artifactSha256: sha("artifact"), artifactPresent: true, pmtilesHeaderVerified: true, decodedSampleVerified: true, propertyPolicyVerified: true, evaluatedAt: "2026-08-23" });
  assert.equal(audit.status, "certified");
  const badAudit = tiles.createCountyTileArtifactAudit({ countyId: "test-county", buildPlanSha256: plan.planSha256, counts: { ...counts, tiledFeatures: 98 }, artifactPath: "output/test.pmtiles", artifactBytes: 1000, artifactSha256: sha("artifact"), artifactPresent: true, pmtilesHeaderVerified: true, decodedSampleVerified: true, propertyPolicyVerified: true, evaluatedAt: "2026-08-23" });
  assert.equal(badAudit.status, "rejected");
  const rejected = tiles.createCountyTilePublicationDecision({ countyId: "test-county", artifactAuditSha256: audit.auditSha256, artifactAuditCertified: true, httpRangeDeliveryCertified: true, pmtilesUrl: "https://cdn.example/test.pmtiles", viewportFallbackCertified: true, approvalRefs: ["a", "b"], countyReleaseAuthorized: true, evaluatedAt: "2026-08-23" });
  assert.equal(rejected.status, "rejected");
  const authorized = tiles.createCountyTilePublicationDecision({ countyId: "test-county", artifactAuditSha256: audit.auditSha256, artifactAuditCertified: true, httpRangeDeliveryCertified: true, pmtilesUrl: `https://cdn.example/${sha("artifact").slice(0, 16)}-test.pmtiles`, viewportFallbackCertified: true, approvalRefs: ["a", "b"], countyReleaseAuthorized: true, evaluatedAt: "2026-08-23" });
  assert.equal(authorized.status, "authorized");
  const schema = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/schemas/county-tile-delivery.schema.json"), "utf8"));
  assert.equal(schema.$defs.decision.properties.schemaVersion.const, tiles.COUNTY_TILE_PUBLICATION_DECISION_VERSION);
  const stream = spawnSync(process.execPath, [path.join(__dirname, "../scripts/stream-county-parcels-ndjson.cjs"), "--manifest=public/data/counties/tarrant/parcels/manifest.json", "--limit=3"], { cwd: path.join(__dirname, ".."), encoding: "utf8", maxBuffer: 2_000_000 });
  assert.equal(stream.status, 0, stream.stderr);
  const features = stream.stdout.trim().split(/\r?\n/).map(JSON.parse);
  assert.equal(features.length, 3);
  assert(features.every((feature) => feature.type === "Feature" && ["Polygon", "MultiPolygon"].includes(feature.geometry.type)));
  assert(features.every((feature) => !Object.keys(feature.properties).some((field) => ["ownerName", "ownerMailingAddress", "ownerPhone", "ownerEmail", "sourceReferences"].includes(field))));
  const gates = fs.readFileSync(path.join(__dirname, "../src/data/platformFeatureGates.ts"), "utf8");
  for (const gate of ["countyTileBuildAuthorization", "countyPmtilesArtifactCertification", "countyTileHttpRangeCertification", "countyPmtilesRuntimeActivation"]) assert(gates.includes(`${gate}: false`));
  console.log("White Rabbit county tile source, privacy, build, artifact, CDN, fallback, and activation tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
