const assert = require("assert");
const fs = require("fs");
const path = require("path");

(async () => {
  const permits = await import("../src/operations/countyPermitIntelligence.mjs");
  const sha = permits.countyPermitSha256;
  const base = { countyId: "test-county", publisher: "Official City", serviceUrl: "https://official.example/Permits/FeatureServer", layerUrl: "https://official.example/Permits/FeatureServer/0", layerName: "Permits", geometryType: "esriGeometryPoint", spatialReference: "EPSG:4326", identityField: "PERMIT_ID", identityUniqueness: "unverified", addressField: "ADDRESS", sourceParcelKeyField: "GIS_ID", sourceParcelKeyBridgeStatus: "unverified", featureCount: 10, nonNullCounts: { PERMIT_ID: 10, ADDRESS: 9, GIS_ID: 8 }, typeStatusTupleCount: 2, permitTypes: ["Building", "Electrical"], metadataSha256: sha("meta"), countResponseSha256: sha("count"), completenessResponseSha256: sha("complete"), taxonomyResponseSha256: sha("taxonomy"), observedAt: "2026-08-23" };
  const cityA = permits.createCountyPermitSourceProbe({ ...base, sourceId: "city-a", sourceRole: "municipal-building", jurisdictionIds: ["city-a"], coverageStatement: "City A only", temporalCoverage: "rolling three years" });
  const utility = permits.createCountyPermitSourceProbe({ ...base, sourceId: "utility", sourceRole: "county-utility", jurisdictionIds: [], coverageStatement: "Utility only", temporalCoverage: "unknown" });
  assert.equal(cityA.metadataReady, true);
  assert.equal(cityA.captureAuthorized, false);
  assert.throws(() => permits.createCountyPermitSourceProbe({ ...base, sourceId: "bad", sourceRole: "municipal-building", jurisdictionIds: [] }), /jurisdictionIds/);
  const coverage = permits.reconcileCountyPermitCoverage({ countyId: "test-county", jurisdictionUniverseIds: ["city-a", "city-b", "unincorporated"], probes: [cityA, utility] });
  assert.deepEqual(coverage.discoveredBuildingJurisdictionIds, ["city-a"]);
  assert.deepEqual(coverage.certifiedBuildingJurisdictionIds, []);
  assert.deepEqual(coverage.uncoveredBuildingJurisdictionIds, ["city-a", "city-b", "unincorporated"]);
  assert.deepEqual(coverage.nonBuildingSourceIds, ["utility"]);
  assert(coverage.rules.includes("county-utility-never-labeled-building-permit"));
  const policyBlocked = permits.createCountyPermitNormalizationPolicy({ countyId: "test-county", sourceProbeSha256: cityA.probeSha256, identityUniqueness: cityA.identityUniqueness, sourceParcelKeyBridgeStatus: cityA.sourceParcelKeyBridgeStatus, addressField: "ADDRESS", geometryAvailable: true });
  assert.equal(policyBlocked.status, "blocked");
  const policyReady = permits.createCountyPermitNormalizationPolicy({ countyId: "test-county", sourceProbeSha256: cityA.probeSha256, identityUniqueness: "verified-unique", sourceParcelKeyBridgeStatus: "verified", sourceParcelKeyField: "GIS_ID", jurisdictionBoundarySnapshotSha256: sha("boundary"), rights: ["store", "derive", "query"], rightsEvidenceRef: "artifact://license", approvalRefs: ["approval://data", "approval://quality"] });
  assert.equal(policyReady.status, "normalization-authorized");
  const event = permits.createNormalizedCountyPermitEvent({ countyId: "test-county", jurisdictionId: "city-a", sourceId: "city-a", sourcePermitId: "P-1", permitNumber: "2026-1", permitType: "Building", permitCategory: "new-construction", status: "issued", filedAt: "2026-08-20", declaredValue: 100000, normalizedAddress: "100 MAIN ST", sourceParcelKey: "G-1", point: { longitude: -97.3, latitude: 32.7 }, sourceSnapshotSha256: sha("snapshot"), sourceRecordSha256: sha("record") });
  assert.equal(event.schemaVersion, permits.NORMALIZED_COUNTY_PERMIT_EVENT_VERSION);
  assert.equal(event.declaredValue, 100000);
  assert.throws(() => permits.createNormalizedCountyPermitEvent({ ...event, declaredValue: -1 }), /non-negative/);
  const auditBase = { countyId: "test-county", sourceId: "city-a", sourceSnapshotSha256: sha("snapshot"), parcelManifestSha256: sha("parcels"), sourceSnapshotCertified: true, parcelBridgeCertified: true, maximumAmbiguousCount: 0, maximumConflictCount: 0, evaluatedAt: "2026-08-23" };
  const audit = permits.createCountyPermitParcelLinkAudit({ ...auditBase, counts: { source: 100, normalized: 98, directLinked: 40, addressLinked: 30, spatialLinked: 10, unmatched: 18, ambiguous: 0, conflict: 0, invalid: 2 } });
  assert.equal(audit.status, "certified");
  assert.equal(audit.unmatchedRate, 0.18);
  const rejected = permits.createCountyPermitParcelLinkAudit({ ...auditBase, counts: { source: 100, normalized: 98, directLinked: 40, addressLinked: 30, spatialLinked: 9, unmatched: 18, ambiguous: 1, conflict: 0, invalid: 2 } });
  assert.equal(rejected.status, "rejected");
  assert(rejected.checks.some((item) => item.id === "ambiguity-threshold" && !item.passed));
  const badPartition = permits.createCountyPermitParcelLinkAudit({ ...auditBase, counts: { source: 100, normalized: 98, directLinked: 40, addressLinked: 30, spatialLinked: 10, unmatched: 17, ambiguous: 0, conflict: 0, invalid: 2 } });
  assert.equal(badPartition.status, "rejected");
  const schema = JSON.parse(fs.readFileSync(path.join(__dirname, "../data/schemas/county-permit-intelligence.schema.json"), "utf8"));
  assert.equal(schema.$defs.event.properties.schemaVersion.const, permits.NORMALIZED_COUNTY_PERMIT_EVENT_VERSION);
  const gates = fs.readFileSync(path.join(__dirname, "../src/data/platformFeatureGates.ts"), "utf8");
  for (const gate of ["countyPermitSourceFederation", "countyPermitRecordCapture", "countyPermitNormalization", "countyPermitParcelLinking", "countyPermitTemporalHistory"]) assert(gates.includes(`${gate}: false`));
  console.log("White Rabbit permit scope, normalization, event, and exact parcel-link audit tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
