const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const app = fs.readFileSync(path.join(root, "src", "App.tsx"), "utf8");
const crm = fs.readFileSync(path.join(root, "src", "components", "CrmPage.tsx"), "utf8");
const crmImport = fs.readFileSync(path.join(root, "src", "crm", "importLeads.mjs"), "utf8");
const memberExchange = fs.readFileSync(path.join(root, "src", "components", "MemberExchange.tsx"), "utf8");
const agentControl = fs.readFileSync(path.join(root, "src", "components", "AgentControlCenter.tsx"), "utf8");
const platformIdentity = fs.readFileSync(path.join(root, "src", "platform", "platformIdentity.ts"), "utf8");

assert(app.includes('import CrmPage from "./components/CrmPage"'), "The CRM page must be connected to the application");
assert(app.includes("const [crmOpen, setCrmOpen]"), "The landing shell must own CRM navigation state");
assert(app.includes("<CrmPage logo={<RabbitLogo />}"), "The CRM must retain the white rabbit brand mark");
assert(app.includes(">CRM</button>"), "CRM must be discoverable from the existing navigation");
assert(crm.includes('data-page="crm"'), "CRM must expose a stable page hook");
assert(crm.includes('data-crm-storage="local-device"'), "Local-only CRM persistence must be disclosed");
assert(crm.includes("real-estate-savant:crm:v1"), "CRM records must use an isolated versioned storage key");
for (const view of ["people", "pipeline", "tasks"]) assert(crm.includes(`data-crm-view="${view}"`), `${view} CRM view must exist`);
for (const stage of ["Lead", "Qualified", "Underwriting", "Due diligence", "Offer", "Closed"]) assert(crm.includes(`"${stage}"`), `${stage} CRM stage must exist`);
for (const destination of ["People", "Members", "Tasks", "Calendar", "Listings", "Deals", "Reporting", "Admin"]) assert(crm.includes(`"${destination}"`), `${destination} CRM navigation must exist`);
assert(crm.includes('activeView === "inbox" ? "Member Exchange"'), "CRM member messaging must have a clearly labeled page title");
for (const column of ["Phone 1", "Phone 2", "Phone 3", "Phone 4", "Phone 5", "Email 1", "Email 2", "Email 3", "Email 4", "Email 5", "Property type", "APN", "Property address", "City", "County", "State", "ZIP", "Sold date", "Sold price", "Price", "Created", "Last activity", "Agent", "Stage / source", "Follow-up"]) assert(crm.includes(`"${column}"`), `${column} people-table column must exist`);
assert(crm.includes("Assigned collections") && crm.includes("Needs Contact") && crm.includes("Follow-up Due") && crm.includes("Active Opportunities"), "CRM smart lists must exist");
assert(crm.includes("No people yet") && crm.includes("No opportunities") && crm.includes("No follow-ups yet"), "CRM must use honest empty states");
assert(crm.includes("phone?: string") && crm.includes("agent?: string") && crm.includes("source?: string"), "CRM relationship records must support contact routing fields");
assert(crm.includes('accept=".csv,text/csv"') && crm.includes("Import leads"), "CRM must expose a local CSV lead import action");
assert(crm.includes("importCrmLeadsFromCsv") && crm.includes("duplicate") && crm.includes("skipped"), "CRM must report CSV import and duplicate outcomes");
assert(crm.includes("sanitizeCrmLead") && crmImport.includes("removeCrexiLinksFromText"), "CRM must remove Crexi links from new and already stored imported leads");
assert(crm.includes("current.map(sanitizeCrmLead).filter(hasMeaningfulLeadInfo)"), "The live CRM state must be sanitized immediately when the CRM opens");
assert(crm.includes('data-crm-csv-dropzone="true"') && crm.includes("onDrop={dropLeadCsv}"), "CRM must support drag-and-drop CSV lead imports");
assert(crm.includes("Please choose a CSV file.") && crm.includes("10 MB"), "CRM CSV drop zone must validate file type and size");
assert(crmImport.includes('CRM_IMPORT_VERSION = "wr-crm-lead-import-v1"'), "CRM import must use a versioned contract");
assert(crmImport.includes("first name") && crmImport.includes("last activity") && crmImport.includes("assigned agent") && crmImport.includes("lead source"), "CRM import must recognize common Follow Up Boss-style columns");
assert(crmImport.includes('"phone 1"') && crmImport.includes('"phone 5"') && crmImport.includes('"email 1"') && crmImport.includes('"email 5"'), "CRM import must recognize numbered property-export phone and email columns");
assert(crmImport.includes("mergeContactDetails") && crm.includes("existing lead"), "CRM re-import must repair existing leads without creating duplicates");
assert(crm.includes('data-action="open-lead-profile"') && crm.includes("setSelectedLeadId(item.id)"), "CRM lead names must open their profile");
assert(crm.includes('data-crm-lead-profile="true"') && crm.includes("Phone numbers") && crm.includes("Email addresses"), "CRM lead profiles must show all contact channels");
assert(crm.includes('min-w-[3600px]') && crm.includes("overflow-x-auto"), "CRM people table must scroll horizontally for numbered contact and property columns");
assert(crm.includes("Phone {index + 1}:") && crm.includes("Email {index + 1}:"), "CRM lead profiles must label Phone 1-5 and Email 1-5");
assert(crm.includes('href={`tel:${') && crm.includes('data-action="call-lead"') && crm.includes("Call ${"), "CRM phone values must provide explicit click-to-call actions");
assert(crmImport.includes("importedFields") && crm.includes('data-crm-export-details="true"'), "CRM imports must retain and display every populated export field");
assert(crm.includes("const exportColumns = useMemo") && crm.includes('data-crm-complete-export-columns="true"'), "CRM people table must add columns for all remaining imported intelligence fields");
assert(crm.includes("...Object.values(item.importedFields || {})"), "CRM search must cover all imported intelligence fields");
assert(crm.includes("function hasMeaningfulLeadInfo") && crm.includes("parsed.map(sanitizeCrmLead).filter(hasMeaningfulLeadInfo)") && crm.includes("result.records.filter(hasMeaningfulLeadInfo)"), "CRM must remove empty and placeholder-only leads from saved and imported records");
assert(crm.includes('data-crm-follow-up-reminder="true"') && crm.includes('data-crm-follow-up-editor="true"'), "CRM must display due reminders and provide a lead-profile reminder editor");
assert(crm.includes("Interested buyer") && crm.includes("Interested seller") && crm.includes("Buyer and seller"), "CRM reminders must classify interested buyers and sellers");
assert(crm.includes("postponeFollowUp") && crm.includes("completeFollowUp") && crm.includes("Tomorrow") && crm.includes("In 7 days"), "CRM members must be able to postpone or complete reminders");
assert(crm.includes('data-crm-column-selector="true"') && crm.includes("columnVisibility") && crm.includes("sticky left-0"), "CRM must provide functional column groups and keep the Name column visible while scrolling");
assert(crm.includes('data-crm-lead-editor="true"') && crm.includes("updateContactValue"), "CRM lead profiles must support editing core property and contact information");
assert(crm.includes('data-crm-delete-recovery="true"') && crm.includes("restoreDeletedLead") && crm.includes("Remove lead"), "CRM lead deletion must be recoverable with Undo");
assert(crm.includes('data-crm-import-report="true"') && crmImport.includes("issues.push"), "CRM imports must provide row-level review reports");
assert(crm.includes("enqueueSavantEvent") && app.includes("enqueueSavantEvent"), "CRM reminders and listing uploads must enter the Savant agent event queue");
assert(crm.includes("<MemberExchange />") && memberExchange.includes('data-crm-member-exchange="true"'), "CRM Inbox must provide the Member Exchange");
assert(memberExchange.includes("Listing for sale") && memberExchange.includes("Buyer need") && memberExchange.includes("Message members"), "Member Exchange must support listing posts, buyer needs, and member conversations");
assert(memberExchange.includes('data-member-direct-chat="true"') && memberExchange.includes("Talk to a member or real estate agent") && memberExchange.includes("Start conversation"), "Member Exchange must provide simple direct member and agent conversations");
assert(memberExchange.includes("Recent conversations") && memberExchange.includes("startDirectConversation"), "Direct conversations must be easy to reopen");
assert(crm.includes("<AgentControlCenter />") && agentControl.includes('data-savant-agent-control-center="true"'), "CRM Admin must expose the Savant Agent Control Center");
assert(agentControl.includes('data-savant-human-approval-gate="true"') && agentControl.includes("Architecture locked"), "Savant agent controls must visibly enforce the locked human-approval baseline");
assert(platformIdentity.includes('creator: "Ernest Rodriguez"'), "Ernest Rodriguez must remain embedded in the internal core platform identity");
assert(!app.includes("Created by {PLATFORM_IDENTITY.creator}") && !app.includes('data-platform-creator="ernest-rodriguez"') && !agentControl.includes("PLATFORM_IDENTITY.creator"), "Creator attribution must not appear on application pages");
assert(crm.includes("View parcel on map") && crm.includes("Deal stage") && crm.includes("Next action"), "CRM lead profile must include property and workflow details");
assert(!crm.includes("10300 SANDEN"), "CRM must not introduce the old automatic fallback address");

console.log("Real Estate Savant CRM page tests passed.");
