const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");

(async () => {
  const operations = await import("../src/portfolio/assetOperations.mjs");
  const strategyApi = await import("../src/portfolio/forwardStrategy.mjs");
  const persistence = await import("../src/persistence/platformPersistenceService.mjs");
  const { SqlitePlatformRepository } = await import("../src/persistence/sqlitePlatformRepository.mjs");
  const organizationId = "org-a", assetId = "asset-1", propertyId = "wrp:v1:dallas-county-dcad:A1", evaluatedAt = "2026-11-15T12:00:00.000Z";
  let sourceIndex = 0;
  const source = (overrides = {}) => ({ datasetId: "forward-strategy", recordId: `record-${++sourceIndex}`, sourceRef: `source-ref:forward-${sourceIndex}`, licenseId: "license-forward", licenseStatus: "authorized", observedAt: "2026-10-01T00:00:00.000Z", availableAt: "2026-10-02T00:00:00.000Z", expiresAt: "", sourceVersion: "2026.10", fieldMap: { value: "value" }, contentSha256: operations.assetOperationsSha256(`forward-${sourceIndex}`), ...overrides });
  const observed = (value, sourceField = "value") => ({ status: "observed", value, sourceField });
  const asset = operations.createAssetRecord({ id: assetId, organizationId, whiteRabbitPropertyId: propertyId, name: "Rabbit Tower", propertyType: "office", currency: "USD", acquiredOn: "2025-01-01", rentableAreaSqFt: observed(10000, "area"), unitCount: observed(1, "units"), portfolioMemberships: [{ portfolioId: "main", effectiveFrom: "2025-01-01" }], source: source() });
  const lease = operations.createLeaseRecord({ id: "lease-record-1", organizationId, assetId, whiteRabbitPropertyId: propertyId, leaseId: "lease-1", tenantEntityId: "tenant-1", tenantDisplayName: "Anchor Tenant", unitIds: ["suite-100"], executedAt: "2025-01-01T00:00:00.000Z", commencementDate: "2025-01-01", expirationDate: "2026-12-31", areaSqFt: observed(10000, "area"), currency: "USD", baseRentSchedule: [{ effectiveFrom: "2025-01-01", effectiveTo: "2026-12-31", monthlyAmount: observed(10000, "rent") }], recoveryStructure: "gross", status: "executed", source: source() });
  const statement = operations.createOperatingStatement({ id: "statement-oct", organizationId, assetId, whiteRabbitPropertyId: propertyId, periodStart: "2026-10-01", periodEnd: "2026-10-31", basis: "accrual", currency: "USD", expectedAccountCodes: ["rent", "opex"], entries: [{ accountCode: "rent", accountName: "Rent", category: "revenue", status: "observed", amount: 10000, sourceField: "rent" }, { accountCode: "opex", accountName: "Operating expense", category: "operating-expense", status: "observed", amount: 4000, sourceField: "opex" }], source: source() });
  const operationsState = operations.createAssetOperationsState({ organizationId, assets: [asset], leases: [lease], statements: [statement], updatedAt: evaluatedAt });
  const assumption = (id, metric, value, unit, leaseId = "", overrides = {}) => strategyApi.createForecastAssumption({ id, organizationId, assetId, leaseId, metric, status: "assumed", value, unit, effectiveFrom: "2026-01-01", rationale: "Approved 2027 business-plan assumption", createdByUserId: "manager-1", approvedByUserId: "director-1", createdAt: "2026-10-10T00:00:00.000Z", source: source(), ...overrides });
  const assumptions = [
    assumption("renewal", "renewal-probability-pct", 60, "percent", "lease-1"),
    assumption("downtime", "downtime-months", 2, "months", "lease-1"),
    assumption("market-rent", "market-rent-monthly", 12000, "usd-month", "lease-1"),
    assumption("rent-growth", "rent-growth-pct", 3, "percent"),
    assumption("expense-growth", "expense-growth-pct", 4, "percent"),
    assumption("capital-multiplier", "capital-cost-multiplier-pct", 100, "percent")
  ];
  assert.throws(() => assumption("self-approved", "rent-growth-pct", 3, "percent", "", { approvedByUserId: "manager-1" }), (error) => error.code === "WR_FORECAST_ASSUMPTION_APPROVAL_SEPARATION_REQUIRED");
  assert.throws(() => assumption("bad-probability", "renewal-probability-pct", 101, "percent", "lease-1"), /between 0 and 100/);
  const capitalProject = strategyApi.createCapitalProject({ id: "lobby-renovation", organizationId, assetId, name: "Lobby renovation", category: "tenant-experience", startDate: "2027-01-01", endDate: "2027-03-31", dependencyProjectIds: [], schedule: [{ id: "mobilization", date: "2027-01-15", status: "assumed", amount: 12000, sourceField: "january_draw" }, { id: "completion", date: "2027-03-15", status: "assumed", amount: 8000, sourceField: "march_draw" }], contingencyPct: 10, status: "approved", createdByUserId: "manager-1", approvedByUserId: "director-1", approvedAt: "2026-10-12T00:00:00.000Z", source: source() });
  assert.throws(() => strategyApi.createCapitalProject({ ...capitalProject, projectSha256: undefined, approvedByUserId: "manager-1" }), (error) => error.code === "WR_CAPITAL_PROJECT_APPROVAL_SEPARATION_REQUIRED");
  const stressScenario = strategyApi.createStressScenario({ id: "severe-leasing", organizationId, assetId, name: "Severe leasing stress", description: "Lower renewal and market rent with higher expense growth", shocks: [{ metric: "renewal-probability-pct", leaseId: "lease-1", operation: "add", value: -30, rationale: "Renewal downside" }, { metric: "market-rent-monthly", leaseId: "lease-1", operation: "multiply", value: 0.8, rationale: "Market-rent downside" }, { metric: "expense-growth-pct", operation: "add", value: 5, rationale: "Expense inflation" }], createdByUserId: "risk-1", createdAt: "2026-10-13T00:00:00.000Z" });
  assert.equal(stressScenario.probabilityAssigned, false);
  const strategyState = strategyApi.createForwardStrategyState({ organizationId, revision: 1, assumptions, capitalProjects: [capitalProject], stressScenarios: [stressScenario], updatedAt: "2026-11-01T00:00:00.000Z" });
  const rollover = strategyApi.buildLeaseRolloverReport(operationsState, strategyState, { assetId, asOf: "2026-11-01", evaluatedAt, horizonMonths: 24 });
  assert.equal(rollover.expirations.length, 1); assert.equal(rollover.expirations[0].renewalProbabilityPct, 60); assert.equal(rollover.years[0].totalMonthlyBaseRent, 10000); assert.equal(rollover.coverage.knownRenewalCount, 1);
  const futureAmendment = operations.createLeaseAmendment({ id: "future-extension", organizationId, assetId, leaseId: lease.leaseId, sequence: 1, effectiveDate: "2026-12-01", executedAt: "2026-10-15T00:00:00.000Z", previousTermsSha256: operations.expectedLeaseAmendmentPreviousTermsSha256(lease), changes: { expirationDate: "2027-06-30" }, source: source() });
  const amendedOperations = operations.createAssetOperationsState({ organizationId, assets: [asset], leases: [lease], amendments: [futureAmendment], statements: [statement], updatedAt: evaluatedAt }); const amendedRollover = strategyApi.buildLeaseRolloverReport(amendedOperations, strategyState, { assetId, asOf: "2026-11-01", evaluatedAt, horizonMonths: 24 }); assert.equal(amendedRollover.expirations[0].expirationDate, "2027-06-30", "known future-effective amendments must change rollover exposure"); assert(amendedRollover.expirations[0].evidenceSha256s.includes(futureAmendment.amendmentSha256));
  const forecast = strategyApi.buildCashFlowForecast(operationsState, strategyState, { assetId, asOf: "2026-11-01", evaluatedAt, horizonMonths: 15, baselineStatement: statement });
  assert.equal(forecast.status, "complete"); assert.equal(forecast.probabilityClaim, false); assert.equal(forecast.months.find((item) => item.month === "2026-11").totalRent, 10000);
  const january = forecast.months.find((item) => item.month === "2027-01"); assert(january.totalRent > 7000 && january.totalRent < 8000, "downtime month should include only probability-weighted renewal rent"); assert.equal(january.totalCapitalCost, 13200);
  const february = forecast.months.find((item) => item.month === "2027-02"); assert(february.totalRent > january.totalRent, "reletting rent should begin after downtime");
  assert(forecast.evidenceSha256s.includes(capitalProject.projectSha256)); assert(forecast.findings.every((finding) => !finding.includes("default")));
  const unknownRenewal = strategyApi.createForecastAssumption({ ...assumptions[0], assumptionSha256: undefined, status: "unknown", value: null, rationale: "", approvedByUserId: "", source: source() });
  const partialState = strategyApi.createForwardStrategyState({ ...strategyState, assumptions: [unknownRenewal, ...assumptions.slice(1)] });
  const partialForecast = strategyApi.buildCashFlowForecast(operationsState, partialState, { assetId, asOf: "2026-11-01", evaluatedAt, horizonMonths: 4, baselineStatement: statement }); assert.equal(partialForecast.status, "partial"); assert.equal(partialForecast.months.find((item) => item.month === "2027-01").totalRent, null);
  const futureMarketRent = strategyApi.createForecastAssumption({ ...assumptions[2], assumptionSha256: undefined, source: source({ observedAt: "2026-12-01T00:00:00.000Z", availableAt: "2026-12-02T00:00:00.000Z" }) });
  const futureState = strategyApi.createForwardStrategyState({ ...strategyState, assumptions: [...assumptions.slice(0, 2), futureMarketRent, ...assumptions.slice(3)] }); assert.equal(strategyApi.buildCashFlowForecast(operationsState, futureState, { assetId, asOf: "2026-11-01", evaluatedAt, horizonMonths: 4, baselineStatement: statement }).status, "partial");
  const restrictedProject = strategyApi.createCapitalProject({ ...capitalProject, id: "restricted-project", projectSha256: undefined, source: source({ licenseStatus: "restricted" }) }); const restrictedState = strategyApi.createForwardStrategyState({ ...strategyState, capitalProjects: [restrictedProject] }); const restrictedForecast = strategyApi.buildCashFlowForecast(operationsState, restrictedState, { assetId, asOf: "2026-11-01", evaluatedAt, horizonMonths: 4, baselineStatement: statement }); assert.equal(restrictedForecast.months.find((item) => item.month === "2027-01").totalCapitalCost, null);
  const stress = strategyApi.runStressScenario(operationsState, strategyState, stressScenario, { assetId, asOf: "2026-11-01", evaluatedAt, horizonMonths: 15, baselineStatement: statement }); assert.equal(stress.deterministicScenario, true); assert.equal(stress.probabilityAssigned, false); assert(stress.years.some((item) => item.delta < 0));
  assert.throws(() => strategyApi.runStressScenario(operationsState, strategyState, { ...stressScenario, id: "not-persisted", scenarioSha256: undefined }, { assetId, asOf: "2026-11-01", evaluatedAt, baselineStatement: statement }), (error) => error.code === "WR_STRESS_SCENARIO_SCOPE_MISMATCH");
  const projectA = strategyApi.createCapitalProject({ ...capitalProject, id: "project-a", projectSha256: undefined, status: "planned", approvedByUserId: "", approvedAt: "", dependencyProjectIds: ["project-b"], source: source() }), projectB = strategyApi.createCapitalProject({ ...capitalProject, id: "project-b", projectSha256: undefined, status: "planned", approvedByUserId: "", approvedAt: "", dependencyProjectIds: ["project-a"], source: source() }); assert.throws(() => strategyApi.createForwardStrategyState({ organizationId, capitalProjects: [projectA, projectB], updatedAt: evaluatedAt }), (error) => error.code === "WR_CAPITAL_PROJECT_DEPENDENCY_CYCLE");
  assert.throws(() => strategyApi.addStressScenario(strategyState, { ...stressScenario, id: "stress-2", scenarioSha256: undefined }, { organizationId, grants: ["forward-strategy:write"], expectedRevision: 99, occurredAt: evaluatedAt }), (error) => error.code === "WR_REVISION_CONFLICT");
  assert.throws(() => strategyApi.addStressScenario(strategyState, { ...stressScenario, id: "stress-b", scenarioSha256: undefined, organizationId: "org-b" }, { organizationId, grants: ["forward-strategy:write"], expectedRevision: 1, occurredAt: evaluatedAt }), (error) => error.code === "WR_TENANT_ISOLATION_VIOLATION");
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "white-rabbit-forward-strategy-")), dbPath = path.join(tempDir, "strategy.sqlite"), context = { organizationId, actorUserId: "strategy-service", subjectUserId: "strategy-service", sessionId: "session-1", requestId: "request-1", grants: ["persistence:read", "persistence:write"], issuedAt: "2026-11-15T11:00:00.000Z", expiresAt: "2026-11-15T13:00:00.000Z" };
  let repository = new SqlitePlatformRepository({ filename: dbPath, clock: () => evaluatedAt }); persistence.persistForwardStrategyState(repository, context, strategyState, { expectedTenantRevision: 0, expectedRecordRevision: 0, idempotencyKey: "strategy-state-1", occurredAt: evaluatedAt, validation: { now: evaluatedAt } }); repository.close(); repository = new SqlitePlatformRepository({ filename: dbPath, clock: () => evaluatedAt }); assert.equal(persistence.loadForwardStrategyState(repository, context, { validation: { now: evaluatedAt } }).stressScenarios[0].id, stressScenario.id); assert.equal(persistence.loadForwardStrategyState(repository, { ...context, organizationId: "org-b" }, { validation: { now: evaluatedAt } }), null); repository.close();
  for (const suffix of ["", "-wal", "-shm"]) { const target = `${dbPath}${suffix}`; if (fs.existsSync(target)) fs.rmSync(target); } fs.rmdirSync(tempDir);
  const schema = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "data", "schemas", "forward-strategy.schema.json"), "utf8")); assert.equal(schema.$defs.forecast.properties.schemaVersion.const, "wr-cash-flow-forecast-v1");
  const app = fs.readFileSync(path.join(__dirname, "..", "src", "App.tsx"), "utf8"); assert.equal(app.includes("forwardStrategy"), false);
  console.log("White Rabbit lease-rollover, evidence-bound cash-flow, capital-plan, stress-scenario, and durable forward-strategy tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
