const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function readJson(relativePath) {
  return JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8"));
}

const adapter = readJson("data/county-adapters/louisville/adapter.json");
const sourceManifest = readJson("data/county-adapters/louisville/lojic-parcel-source-manifest.json");
const fieldMap = readJson("data/county-adapters/louisville/lojic-universal-field-map.json");
const pvaManifest = readJson("data/county-adapters/louisville/pva-owner-appraisal-source-manifest.json");
const permitCoManifest = readJson("data/county-adapters/louisville/permit-co-source-manifest.json");
const publicPermitManifest = readJson("public/data/counties/jefferson-ky/permits/manifest.json");
const zoningSourceManifest = readJson("data/county-adapters/louisville/lojic-zoning-source-manifest.json");
const publicZoningManifest = readJson("public/data/counties/jefferson-ky/zoning/manifest.json");
const publicZoningIndex = readJson("public/data/counties/jefferson-ky/zoning/parcel-zoning-index.json");
const zoningReport = readJson("output/jefferson-ky/zoning-source-report.json");
const floodplainSourceManifest = readJson("data/county-adapters/louisville/fema-floodplain-source-manifest.json");
const publicFloodplainManifest = readJson("public/data/counties/jefferson-ky/floodplain/manifest.json");
const publicFloodplainIndex = readJson("public/data/counties/jefferson-ky/floodplain/parcel-floodplain-index.json");
const floodplainReport = readJson("output/jefferson-ky/floodplain-source-report.json");
const schemaReport = readJson("output/jefferson-ky/schema-report.json");
const buildScript = fs.readFileSync(path.join(root, "scripts", "build-jefferson-ky-lojic-parcels.cjs"), "utf8");
const zoningBuildScript = fs.readFileSync(path.join(root, "scripts", "build-jefferson-ky-zoning-index.cjs"), "utf8");
const floodplainBuildScript = fs.readFileSync(path.join(root, "scripts", "build-jefferson-ky-floodplain-index.cjs"), "utf8");
const pvaBuildScript = fs.readFileSync(path.join(root, "scripts", "build-jefferson-ky-pva-owner-appraisal.cjs"), "utf8");
const pipeline = readJson("data/county-adapters/louisville/pipeline.json");

assert(adapter.id === "jefferson-ky", "Jefferson County adapter must use county_id jefferson-ky");
assert(adapter.countyName === "Jefferson County", "Jefferson County adapter must preserve county name");
assert(adapter.marketName === "Louisville", "Jefferson County adapter must preserve Louisville market name");
assert(adapter.cadName === "Jefferson County PVA", "Jefferson County adapter must preserve PVA/CAD name");
assert(adapter.gisSource === "LOJIC Jefferson County KY Parcels", "Jefferson County adapter must preserve LOJIC GIS source");
assert(adapter.uniqueGisKey === "LRSN", "Jefferson County adapter must use LRSN as the unique GIS key");
assert(adapter.parcelIdField === "PARCELID", "Jefferson County adapter must use PARCELID as the parcel ID field");
assert(adapter.geometryType === "polygon", "Jefferson County adapter must treat LOJIC geometry as polygons");
assert(adapter.sourceSpatialReference.includes("EPSG:2246"), "Jefferson County adapter must document EPSG:2246 source spatial reference");
assert(adapter.verifiedCounts.parcelGeometryFeatures === 284553, "Jefferson County parcel count must lock the current live PARCEL_TYPE=0 count");
assert(adapter.sourceFiles.parcelAttributesCsv === "data/raw/jefferson-ky/Jefferson_County_KY_Parcels.csv", "Jefferson County adapter must register the provided LOJIC parcel CSV");
assert(fs.existsSync(path.join(root, adapter.sourceFiles.parcelAttributesCsv)), "Provided Jefferson County parcel CSV must be present in data/raw");
assert(adapter.sourceFiles.parcelGeometryGeojson === "data/raw/jefferson-ky/Jefferson_County_KY_Parcels.geojson", "Jefferson County adapter must register the provided local GeoJSON");
assert(fs.existsSync(path.join(root, adapter.sourceFiles.parcelGeometryGeojson)), "Provided Jefferson County GeoJSON must be present in data/raw");
assert(adapter.sourceFiles.parcelGeometryKml === "data/raw/jefferson-ky/Jefferson_County_KY_Parcels.kml", "Jefferson County adapter must register the provided local KML");
assert(fs.existsSync(path.join(root, adapter.sourceFiles.parcelGeometryKml)), "Provided Jefferson County KML must be present in data/raw");
assert(adapter.sourceFiles.parcelGeometryZip === "data/raw/jefferson-ky/Jefferson_County_KY_Parcels.zip", "Jefferson County adapter must register the provided shapefile ZIP");
assert(fs.existsSync(path.join(root, adapter.sourceFiles.parcelGeometryZip)), "Provided Jefferson County shapefile ZIP must be present in data/raw");
assert(adapter.sourceFiles.parcelGeometryShp.endsWith("Jefferson_County_KY_Parcels.shp"), "Jefferson County adapter must register extracted SHP path");
assert(fs.existsSync(path.join(root, adapter.sourceFiles.parcelGeometryShp)), "Extracted Jefferson County SHP must be present");
assert(adapter.sourceFiles.parcelGeometryDbf.endsWith("Jefferson_County_KY_Parcels.dbf"), "Jefferson County adapter must register extracted DBF path");
assert(fs.existsSync(path.join(root, adapter.sourceFiles.parcelGeometryDbf)), "Extracted Jefferson County DBF must be present");
assert(adapter.sourceFiles.permitsRaw.includes("active_construction_permits"), "Jefferson County adapter must point permits to the official active construction permit source");
assert(adapter.sourceFiles.zoningRaw.includes("OpenDataDevelopment/MapServer/15"), "Jefferson County adapter must point zoning to the official LOJIC zoning source");
assert(adapter.sourceFiles.floodplainRaw.includes("CamaFloodContour/MapServer/2"), "Jefferson County adapter must point floodplain to the current FEMA flood zone source");
const permitLayer = adapter.optionalLayers.find((layer) => layer.id === "permits");
assert(permitLayer, "Jefferson County adapter must declare the permits optional layer");
assert(permitLayer.manifestPath === "data/county-adapters/louisville/permit-co-source-manifest.json", "Jefferson permits layer must use the official permit/CO source manifest");
assert(permitLayer.sourceUrls.some((url) => url.includes("active_construction_permits")), "Jefferson permits layer must link active construction permits");
assert(permitLayer.sourceUrls.some((url) => url.includes("pm_occupancy")), "Jefferson permits layer must link property maintenance occupancy");
assert(adapter.verifiedCounts.sourcePermitRecords === 22832, "Jefferson County adapter must lock the current verified active permit source count");
assert(adapter.verifiedCounts.permitRowsJoined === 22717, "Jefferson County adapter must lock exact spatial permit joins");
assert(adapter.verifiedCounts.permitRowsUnmatched === 115, "Jefferson County adapter must preserve unmatched and invalid-coordinate permit counts");
assert(adapter.verifiedCounts.parcelsWithDevelopmentSignals === 16320, "Jefferson County adapter must lock parcels with development signals");
const zoningLayer = adapter.optionalLayers.find((layer) => layer.id === "zoning-intelligence");
assert(zoningLayer, "Jefferson County adapter must declare the zoning intelligence optional layer");
assert(zoningLayer.status === "parcel-index-ready", "Jefferson zoning layer must be parcel-index-ready");
assert(zoningLayer.manifestPath === "data/county-adapters/louisville/lojic-zoning-source-manifest.json", "Jefferson zoning layer must point to its source manifest");
assert(zoningLayer.publicManifestPath === "public/data/counties/jefferson-ky/zoning/manifest.json", "Jefferson zoning layer must point to its public manifest");
assert(zoningLayer.parcelIndexPath === "public/data/counties/jefferson-ky/zoning/parcel-zoning-index.json", "Jefferson zoning layer must point to its parcel zoning index");
assert(zoningLayer.sourceUrls.includes("https://gis.lojic.org/maps/rest/services/LojicSolutions/OpenDataDevelopment/MapServer/15"), "Jefferson zoning layer must link the official LOJIC zoning source");
assert(adapter.verifiedCounts.sourceZoningRecords === 4883, "Jefferson County adapter must lock the verified LOJIC zoning source count");
assert(adapter.verifiedCounts.zoningPolygonsIndexed === 4881, "Jefferson County adapter must lock indexed LOJIC zoning polygon count");
assert(adapter.verifiedCounts.parcelsWithZoning === 284226, "Jefferson County adapter must lock parcel zoning match count");
const floodplainLayer = adapter.optionalLayers.find((layer) => layer.id === "floodplain-intelligence");
assert(floodplainLayer, "Jefferson County adapter must declare the floodplain intelligence optional layer");
assert(floodplainLayer.status === "parcel-index-ready", "Jefferson floodplain layer must be parcel-index-ready");
assert(floodplainLayer.manifestPath === "data/county-adapters/louisville/fema-floodplain-source-manifest.json", "Jefferson floodplain layer must point to its source manifest");
assert(floodplainLayer.publicManifestPath === "public/data/counties/jefferson-ky/floodplain/manifest.json", "Jefferson floodplain layer must point to its public manifest");
assert(floodplainLayer.parcelIndexPath === "public/data/counties/jefferson-ky/floodplain/parcel-floodplain-index.json", "Jefferson floodplain layer must point to its parcel floodplain index");
assert(floodplainLayer.sourceUrls.includes("https://gis.lojic.org/maps/rest/services/PvaGis/CamaFloodContour/MapServer/2"), "Jefferson floodplain layer must link the current FEMA flood zone source");
assert(adapter.verifiedCounts.sourceFloodplainRecords === 10087, "Jefferson County adapter must lock the verified floodplain source count");
assert(adapter.verifiedCounts.floodplainPolygonsIndexed === 10087, "Jefferson County adapter must lock indexed floodplain polygon count");
assert(adapter.verifiedCounts.parcelsWithFloodZone === 284229, "Jefferson County adapter must lock parcel flood zone match count");
assert(adapter.verifiedCounts.parcelsInSfha === 9312, "Jefferson County adapter must lock parcel SFHA count");
assert(adapter.verifiedCounts.parcelsInFloodway === 1223, "Jefferson County adapter must lock parcel floodway count");

assert(sourceManifest.county_id === adapter.id, "LOJIC source manifest must use the same county id as the adapter");
assert(sourceManifest.unique_gis_key === "LRSN", "LOJIC source manifest must lock LRSN as unique GIS key");
assert(sourceManifest.parcel_id_field === "PARCELID", "LOJIC source manifest must lock PARCELID as parcel ID field");
assert(sourceManifest.geometry_type === "polygon", "LOJIC source manifest must declare parcel polygons");
assert(sourceManifest.source_spatial_reference.epsg === 2246, "LOJIC source manifest must lock EPSG:2246");
assert(sourceManifest.verified_counts.parcel_type_0_features === 284429, "LOJIC source manifest must lock true parcel count");
assert(sourceManifest.qa_findings.duplicate_lrsn_groups === 20, "LOJIC source manifest must preserve duplicate LRSN QA count");
assert(sourceManifest.qa_findings.duplicate_parcelid_groups === 11, "LOJIC source manifest must preserve duplicate PARCELID QA count");
assert(sourceManifest.download_tests.csv.provided_local_csv_supported === true, "LOJIC source manifest must record the provided local CSV as supported plumbing data");
assert(sourceManifest.download_tests.csv.provided_local_csv_latest_download_name === "Jefferson_County_KY_Parcels (3).csv", "LOJIC source manifest must record the latest provided CSV download name");
assert(sourceManifest.download_tests.csv.provided_local_csv_sha256 === "3AE16B41DC9E9F631541782324C095522DF89044E6D0659E7450EB18BDCA7C01", "LOJIC source manifest must preserve latest provided CSV SHA-256");
assert(sourceManifest.download_tests.arcgis_rest_query.supported, "LOJIC source manifest must test ArcGIS REST query support");
assert(sourceManifest.download_tests.geojson.supported, "LOJIC source manifest must test GeoJSON support");
assert(sourceManifest.local_geojson_snapshot.total_features === 293119, "LOJIC source manifest must lock provided GeoJSON feature count");
assert(sourceManifest.local_geojson_snapshot.latest_provided_download_name === "Jefferson_County_KY_Parcels (3).geojson", "LOJIC source manifest must record latest provided GeoJSON download name");
assert(sourceManifest.local_geojson_snapshot.sha256 === "2942A274C4B57A532E57573A5A8B330B35D14FAE293E5F7286F725DA369A7E59", "LOJIC source manifest must preserve provided GeoJSON SHA-256");
assert(sourceManifest.local_geojson_snapshot.parcel_type_0_features === 284429, "LOJIC source manifest must lock provided GeoJSON parcel count");
assert(sourceManifest.local_geojson_snapshot.exportable_parcel_polygon_features === 284428, "LOJIC source manifest must lock provided GeoJSON exportable polygon count");
assert(sourceManifest.local_geojson_snapshot.invalid_polygon_ring_features === 1, "LOJIC source manifest must document provided GeoJSON invalid polygon ring count");
assert(sourceManifest.local_geojson_snapshot.geometry_types.Polygon === 293106, "LOJIC source manifest must record provided GeoJSON polygon count");
assert(sourceManifest.local_geojson_snapshot.geometry_types.MultiPolygon === 13, "LOJIC source manifest must record provided GeoJSON multipolygon count");
assert(sourceManifest.download_tests.geojson.provided_local_geojson_supported === true, "LOJIC source manifest must record the provided local GeoJSON as supported plumbing data");
assert(sourceManifest.download_tests.geojson.provided_local_geojson_latest_download_name === "Jefferson_County_KY_Parcels (3).geojson", "LOJIC source manifest must preserve latest provided GeoJSON download name");
assert(sourceManifest.download_tests.geojson.provided_local_geojson_sha256 === sourceManifest.local_geojson_snapshot.sha256, "LOJIC source manifest must keep local GeoJSON SHA-256 consistent");
assert(sourceManifest.download_tests.geojson.provided_local_geojson_exportable_parcel_polygon_features === 284428, "LOJIC source manifest must preserve provided GeoJSON exportable polygon count");
assert(sourceManifest.local_kml_snapshot.total_placemarks === 293119, "LOJIC source manifest must lock provided KML placemark count");
assert(sourceManifest.local_kml_snapshot.parcel_type_0_placemarks === 284429, "LOJIC source manifest must lock provided KML parcel count");
assert(sourceManifest.local_kml_snapshot.exportable_parcel_polygon_placemarks === 284428, "LOJIC source manifest must lock provided KML exportable polygon count");
assert(sourceManifest.local_kml_snapshot.invalid_polygon_ring_placemarks === 1, "LOJIC source manifest must document provided KML invalid polygon ring count");
assert(sourceManifest.local_kml_snapshot.sha256 === "985ED0CE78FD9714C4AC7B7F5A5695708ACDC6B070992F5686652FF787AA4B2D", "LOJIC source manifest must preserve provided KML SHA-256");
assert(sourceManifest.local_kml_snapshot.geometry_types.Polygon === 293106, "LOJIC source manifest must record provided KML polygon count");
assert(sourceManifest.local_kml_snapshot.geometry_types.MultiGeometry === 13, "LOJIC source manifest must record provided KML multigeometry count");
assert(sourceManifest.local_kml_snapshot.schema_fields.includes("PIN"), "LOJIC source manifest must record KML-declared PIN schema field");
assert(!sourceManifest.local_kml_snapshot.observed_simple_data_fields.includes("PIN"), "LOJIC source manifest must document that no KML PIN SimpleData values were observed");
assert(sourceManifest.download_tests.kml.provided_local_kml_supported === true, "LOJIC source manifest must record the provided local KML as supported plumbing data");
assert(sourceManifest.download_tests.kml.provided_local_kml_sha256 === sourceManifest.local_kml_snapshot.sha256, "LOJIC source manifest must keep local KML SHA-256 consistent");
assert(sourceManifest.download_tests.csv.direct_arcgis_query_supported === false, "LOJIC source manifest must not pretend direct CSV query is supported");
assert(sourceManifest.download_tests.shapefile_zip.direct_layer_download_supported === false, "LOJIC source manifest must not pretend direct shapefile ZIP export is advertised");
assert(sourceManifest.local_shapefile_snapshot.record_count === 293119, "LOJIC source manifest must lock provided shapefile record count");
assert(sourceManifest.local_shapefile_snapshot.parcel_type_0_records === 284429, "LOJIC source manifest must lock local shapefile parcel count");
assert(sourceManifest.local_shapefile_snapshot.exportable_parcel_polygon_records === 284428, "LOJIC source manifest must lock exportable local shapefile polygon count");
assert(sourceManifest.local_shapefile_snapshot.invalid_polygon_ring_records === 1, "LOJIC source manifest must document invalid polygon ring count");
assert(sourceManifest.local_shapefile_snapshot.geometry_type === "Polygon", "LOJIC source manifest must record shapefile polygon geometry");
assert(sourceManifest.local_shapefile_snapshot.dbf_field_aliases.PARCEL_TYP === "PARCEL_TYPE", "LOJIC source manifest must document DBF PARCEL_TYP alias");
assert(sourceManifest.download_tests.shapefile_zip.provided_local_shapefile_zip_supported === true, "LOJIC source manifest must record the provided local shapefile ZIP as supported plumbing data");
assert(sourceManifest.download_tests.shapefile_zip.provided_local_shapefile_zip_latest_download_name === "Jefferson_County_KY_Parcels (2).zip", "LOJIC source manifest must record the latest provided shapefile ZIP download name");
assert(sourceManifest.download_tests.shapefile_zip.provided_local_shapefile_zip_sha256 === "61152AB1F9422578F9C6C555B3BD1C83FA742910E63353690DB7504CC0FDFD75", "LOJIC source manifest must preserve latest provided shapefile ZIP SHA-256");
assert(sourceManifest.download_tests.shapefile_zip.provided_local_shapefile_record_count === 293119, "LOJIC source manifest must preserve provided local shapefile record count");
assert(sourceManifest.download_tests.shapefile_zip.provided_local_shapefile_exportable_parcel_polygon_records === 284428, "LOJIC source manifest must preserve provided shapefile exportable polygon count");

assert(fieldMap.field_map.countyParcelId.value === "jefferson-ky:${LRSN}", "Field map must build countyParcelId from LRSN");
assert(fieldMap.field_map.accountNum.sourceField === "PARCELID", "Field map must map accountNum from PARCELID");
assert(fieldMap.field_map.gisParcelId.sourceField === "LRSN", "Field map must map gisParcelId from LRSN");
assert(fieldMap.field_map.centroid.method.includes("polygon centroid"), "Field map must generate centroids from parcel polygons");
assert(fieldMap.search_index_fields.includes("PARCELID") && fieldMap.search_index_fields.includes("LRSN"), "Search index must use PARCELID and LRSN");
assert(fieldMap.owner_appraisal_placeholder_hook.status === "join-ready-source-needed", "PVA owner/appraisal hook must be join-ready but source-needed");
assert(fieldMap.owner_appraisal_placeholder_hook.primary_join.includes("PARCELID"), "PVA owner/appraisal hook must document PARCELID primary join");
assert(fieldMap.owner_appraisal_placeholder_hook.secondary_join.includes("LRSN"), "PVA owner/appraisal hook must document LRSN secondary join");

assert(pvaManifest.status === "join-ready-source-needed", "PVA source manifest must be join-ready but source-needed");
assert(pvaManifest.input_files.preferred_csv === "data/raw/jefferson-ky/Jefferson_County_KY_PVA_Owner_Appraisal.csv", "PVA source manifest must lock the expected owner/appraisal CSV path");
assert(pvaManifest.join_strategy.primary.source_field === "PARCELID", "PVA source manifest must use PARCELID as the primary join field");
assert(pvaManifest.join_strategy.secondary.source_field === "LRSN", "PVA source manifest must use LRSN as the secondary join field");
assert(pvaManifest.field_aliases.ownerName.includes("OWNER NAME"), "PVA source manifest must include owner name aliases");
assert(pvaManifest.field_aliases.landValue.includes("LAND VALUE"), "PVA source manifest must include land value aliases");
assert(pvaManifest.field_aliases.improvementValue.includes("IMPROVEMENT VALUE"), "PVA source manifest must include improvement value aliases");
assert(pvaManifest.field_aliases.totalValue.includes("ASSESSED VALUE"), "PVA source manifest must include assessed value aliases");
assert(pvaManifest.related_public_sources.louisville_active_construction_permits_url.includes("active_construction_permits"), "PVA source manifest must link active construction permits as related public data");
assert(pvaManifest.official_source_notes.some((note) => note.includes("parcel join remains pending")), "PVA source notes must keep permit parcel join pending");

assert(permitCoManifest.status === "parcel-index-ready-production-disabled", "Permit/CO manifest must mark the spatial parcel index ready but production-disabled");
assert(permitCoManifest.sources.some((source) => source.id === "louisville-active-construction-permits" && source.verified_record_count === 22832), "Permit/CO manifest must lock current active permit count");
assert(permitCoManifest.sources.some((source) => source.id === "jefferson-ky-certificate-of-occupancy" && source.status === "bulk-source-not-confirmed"), "Permit/CO manifest must not pretend CO bulk data is verified");
assert(permitCoManifest.join_strategy.owner_contact_rule.includes("Contractors"), "Permit/CO manifest must keep permit parties separate from owner contacts");
assert(publicPermitManifest.status === "parcel-index-ready-production-disabled", "Public Jefferson permit manifest must expose ready but production-disabled status");
assert(publicPermitManifest.permitCount === 22832, "Public Jefferson permit manifest must carry the current official active permit count");
assert(publicPermitManifest.joinedPermitCount === 22717, "Public Jefferson permit manifest must preserve exact spatial joins");
assert(publicPermitManifest.sourceIntel.certificateOfOccupancyStatus === "bulk-source-not-confirmed", "Public Jefferson permit manifest must keep CO source unconfirmed");
assert(zoningSourceManifest.status === "parcel-index-ready", "Jefferson zoning source manifest must be parcel-index-ready");
assert(zoningSourceManifest.source_url.includes("OpenDataDevelopment/MapServer/15"), "Jefferson zoning source manifest must link the official LOJIC zoning layer");
assert(zoningSourceManifest.verified_record_count === 4883, "Jefferson zoning source manifest must lock source zoning count");
assert(zoningSourceManifest.qa.indexed_polygon_count === 4881, "Jefferson zoning source manifest must lock indexed polygon count");
assert(zoningSourceManifest.qa.parcel_zoning_record_count === 284226, "Jefferson zoning source manifest must lock parcel zoning record count");
assert(zoningSourceManifest.qa.page_design_changed === false, "Jefferson zoning source manifest must document no page design changes");
assert(publicZoningManifest.sourceCountyId === "jefferson-ky", "Public Jefferson zoning manifest must be county-aware");
assert(publicZoningManifest.status === "parcel-index-ready", "Public Jefferson zoning manifest must be parcel-index-ready");
assert(publicZoningManifest.defaultVisible === false, "Public Jefferson zoning manifest must remain default-off");
assert(publicZoningManifest.renderDirectlyInBrowser === false, "Public Jefferson zoning manifest must not render huge layers directly in the browser");
assert(publicZoningManifest.parcelIndexCount === 284226, "Public Jefferson zoning manifest must lock parcel zoning count");
assert(publicZoningManifest.sourceLayers.some((layer) => layer.id === "lojic-zoning" && layer.featureCount === 4883 && layer.indexedFeatureCount === 4881), "Public Jefferson zoning manifest must record LOJIC source and indexed counts");
assert(publicZoningIndex.sourceCountyId === "jefferson-ky", "Public Jefferson zoning index must be county-aware");
assert(publicZoningIndex.recordCount === 284226, "Public Jefferson zoning index must lock parcel zoning record count");
assert(publicZoningIndex.shardCount === 8030, "Public Jefferson zoning index must lock shard count");
assert(publicZoningIndex.shardKeyLength === 6, "Public Jefferson zoning index must use six-character shards");
assert(zoningReport.pageDesignChanged === false, "Jefferson zoning report must document no page design changes");
assert(zoningReport.sourceZoningFeatureCount === 4883, "Jefferson zoning report must lock source zoning count");
assert(zoningReport.indexedZoningFeatureCount === 4881, "Jefferson zoning report must lock indexed zoning polygon count");
assert(zoningReport.recordCount === 284226, "Jefferson zoning report must lock parcel zoning record count");
assert(floodplainSourceManifest.status === "parcel-index-ready", "Jefferson floodplain source manifest must be parcel-index-ready");
assert(floodplainSourceManifest.source_url.includes("CamaFloodContour/MapServer/2"), "Jefferson floodplain source manifest must link the current FEMA flood zone layer");
assert(floodplainSourceManifest.verified_record_count === 10087, "Jefferson floodplain source manifest must lock source floodplain count");
assert(floodplainSourceManifest.qa.indexed_polygon_count === 10087, "Jefferson floodplain source manifest must lock indexed polygon count");
assert(floodplainSourceManifest.qa.parcel_floodplain_record_count === 284229, "Jefferson floodplain source manifest must lock parcel floodplain record count");
assert(floodplainSourceManifest.qa.parcels_in_sfha === 9312, "Jefferson floodplain source manifest must lock parcel SFHA count");
assert(floodplainSourceManifest.qa.parcels_in_floodway === 1223, "Jefferson floodplain source manifest must lock parcel floodway count");
assert(floodplainSourceManifest.qa.page_design_changed === false, "Jefferson floodplain source manifest must document no page design changes");
assert(publicFloodplainManifest.sourceCountyId === "jefferson-ky", "Public Jefferson floodplain manifest must be county-aware");
assert(publicFloodplainManifest.status === "parcel-index-ready", "Public Jefferson floodplain manifest must be parcel-index-ready");
assert(publicFloodplainManifest.defaultVisible === false, "Public Jefferson floodplain manifest must remain default-off");
assert(publicFloodplainManifest.renderDirectlyInBrowser === false, "Public Jefferson floodplain manifest must not render huge layers directly in the browser");
assert(publicFloodplainManifest.parcelIndexCount === 284229, "Public Jefferson floodplain manifest must lock parcel floodplain count");
assert(publicFloodplainManifest.sourceLayers.some((layer) => layer.id === "current-fema-flood-zones" && layer.featureCount === 10087 && layer.indexedFeatureCount === 10087), "Public Jefferson floodplain manifest must record source and indexed counts");
assert(publicFloodplainIndex.sourceCountyId === "jefferson-ky", "Public Jefferson floodplain index must be county-aware");
assert(publicFloodplainIndex.parcelFloodplainRecordCount === 284229, "Public Jefferson floodplain index must lock parcel floodplain record count");
assert(publicFloodplainIndex.parcelsInSfhaCount === 9312, "Public Jefferson floodplain index must lock parcel SFHA count");
assert(publicFloodplainIndex.parcelsInFloodwayCount === 1223, "Public Jefferson floodplain index must lock parcel floodway count");
assert(publicFloodplainIndex.shardCount === 8030, "Public Jefferson floodplain index must lock shard count");
assert(publicFloodplainIndex.shardKeyLength === 6, "Public Jefferson floodplain index must use six-character shards");
assert(floodplainReport.pageDesignChanged === false, "Jefferson floodplain report must document no page design changes");
assert(floodplainReport.sourceFeatureCount === 10087, "Jefferson floodplain report must lock source floodplain count");
assert(floodplainReport.indexedFeatureCount === 10087, "Jefferson floodplain report must lock indexed floodplain polygon count");
assert(floodplainReport.parcelFloodplainRecordCount === 284229, "Jefferson floodplain report must lock parcel floodplain record count");

assert(schemaReport.adapterId === "jefferson-ky", "Schema report must use county_id jefferson-ky");
assert(schemaReport.fields.some((field) => field.name === "LRSN" && field.role.includes("unique GIS")), "Schema report must mark LRSN as unique GIS parcel identifier");
assert(schemaReport.fields.some((field) => field.name === "PARCELID" && field.role.includes("parcel identification")), "Schema report must mark PARCELID as parcel identification number");

assert(buildScript.includes("fetchGeoJsonFeatures"), "Jefferson build script must ingest GeoJSON parcel geometry");
assert(buildScript.includes("fetchLocalGeoJsonFeatures"), "Jefferson build script must ingest local GeoJSON parcel geometry");
assert(buildScript.includes("streamLocalGeoJsonUniversalRecords"), "Jefferson build script must stream full local GeoJSON geometry builds");
assert(buildScript.includes("streamRestUniversalRecords"), "Jefferson build script must stream full ArcGIS REST geometry builds");
assert(buildScript.includes("fetchShapefileFeatures"), "Jefferson build script must ingest local shapefile parcel geometry");
assert(buildScript.includes("streamShapefileUniversalRecords"), "Jefferson build script must stream full local shapefile geometry builds");
assert(buildScript.includes("openGeoJsonFeatureCollectionWriter"), "Jefferson build script must write full county GeoJSON without one huge stringify");
assert(buildScript.includes("transformCoordinates"), "Jefferson build script must transform shapefile coordinates");
assert(buildScript.includes("+x_0=500000"), "Jefferson build script must use a proj4 EPSG:2246 definition that lands parcels in Louisville");
assert(buildScript.includes("PARCEL_TYP"), "Jefferson build script must support the shapefile DBF PARCEL_TYP alias");
assert(buildScript.includes("const accountNum = parcelId || lrsn"), "Jefferson build script must preserve parcels that have LRSN but no PARCELID");
assert(buildScript.includes("geometrySourceMode"), "Jefferson build script must record whether geometry came from REST or local shapefile");
assert(buildScript.includes("propertyGeometryStorage"), "Jefferson build script must document that full GeoJSON geometry lives on feature.geometry");
assert(buildScript.includes("geometryCentroid"), "Jefferson build script must generate centroids");
assert(buildScript.includes("loadPvaOwnerAppraisalIndex"), "Jefferson build script must load the PVA owner/appraisal join index");
assert(buildScript.includes("applyPvaOwnerAppraisal"), "Jefferson build script must enrich parcel records from the PVA owner/appraisal join index");
assert(buildScript.includes("pvaOwnerAppraisalForParcel({ parcelId, lrsn, pin })"), "Jefferson build script must join PVA data by PARCELID, LRSN, or PIN candidate");
assert(buildScript.includes("duplicateSummary(duplicateRows, \"LRSN\")"), "Jefferson build script must QA duplicate LRSN values");
assert(buildScript.includes("duplicateSummary(duplicateRows, \"PARCELID\")"), "Jefferson build script must QA duplicate PARCELID values");
assert(buildScript.includes("ownerAppraisalHook"), "Jefferson build script must preserve PVA owner/appraisal placeholder hook");
assert(zoningBuildScript.includes("fetchZoningFeatures"), "Jefferson zoning build script must fetch official LOJIC zoning features");
assert(zoningBuildScript.includes("parcel centroid spatial join"), "Jefferson zoning build script must document parcel centroid spatial join");
assert(zoningBuildScript.includes("ZONING_CODE"), "Jefferson zoning build script must map ZONING_CODE");
assert(zoningBuildScript.includes("ZONING_NAME"), "Jefferson zoning build script must map ZONING_NAME");
assert(zoningBuildScript.includes("ZONING_TYPE"), "Jefferson zoning build script must map ZONING_TYPE");
assert(zoningBuildScript.includes("assertInsideWorkspace"), "Jefferson zoning build script must guard generated write paths");
assert(floodplainBuildScript.includes("fetchFloodplainFeatures"), "Jefferson floodplain build script must fetch current FEMA flood zone features");
assert(floodplainBuildScript.includes("parcel centroid spatial join"), "Jefferson floodplain build script must document parcel centroid spatial join");
assert(floodplainBuildScript.includes("FLD_ZONE"), "Jefferson floodplain build script must map flood zones");
assert(floodplainBuildScript.includes("SFHA_TF"), "Jefferson floodplain build script must map SFHA flags");
assert(floodplainBuildScript.includes("FLOODWAY"), "Jefferson floodplain build script must map floodway attributes");
assert(floodplainBuildScript.includes("requestJsonPost"), "Jefferson floodplain build script must use ArcGIS POST queries for large batches");
assert(floodplainBuildScript.includes("assertInsideWorkspace"), "Jefferson floodplain build script must guard generated write paths");
assert(pvaBuildScript.includes("manifest.input_files"), "PVA build script must resolve the official owner/appraisal source from the manifest");
assert(pvaBuildScript.includes("duplicateSummary(indexedRows, \"parcelId\")"), "PVA build script must QA duplicate PARCELID groups");
assert(pvaBuildScript.includes("duplicateSummary(indexedRows, \"lrsn\")"), "PVA build script must QA duplicate LRSN groups");
assert(pvaBuildScript.includes("blocked-missing-join-field"), "PVA build script must block exports without PARCELID/LRSN join fields");
assert(pipeline.steps.some((step) => step.command === "node scripts/build-jefferson-ky-lojic-parcels.cjs --full"), "Jefferson pipeline must include the full LOJIC geometry ingestion command");
assert(pipeline.steps.some((step) => step.command === "node scripts/build-jefferson-ky-pva-owner-appraisal.cjs"), "Jefferson pipeline must include the PVA owner/appraisal join index build command");
assert(pipeline.steps.some((step) => step.command === "node scripts/build-jefferson-ky-zoning-index.cjs"), "Jefferson pipeline must include the LOJIC zoning parcel index build command");
assert(pipeline.steps.some((step) => step.command === "node scripts/build-jefferson-ky-floodplain-index.cjs"), "Jefferson pipeline must include the FEMA flood zone parcel index build command");

console.log("Jefferson County KY LOJIC adapter tests passed.");
