const assert = require("assert");
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");
const root = path.resolve(__dirname, "..");
execFileSync("node", ["scripts/build-jefferson-ky-permit-intelligence.cjs"], { cwd: root, stdio: "pipe" });
const permit = JSON.parse(fs.readFileSync(path.join(root, "public/data/counties/jefferson-ky/permits/manifest.json"), "utf8"));
const development = JSON.parse(fs.readFileSync(path.join(root, "public/data/counties/jefferson-ky/developments/manifest.json"), "utf8"));
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
assert.equal(permit.schemaVersion, "wr-jefferson-permit-intelligence-v1");
assert.equal(permit.sourcePermitCount, permit.locatedPermitCount + permit.unlocatedPermitCount);
assert.equal(permit.locatedPermitCount, permit.joinedPermitCount + permit.unmatchedLocatedPermitCount);
assert(permit.joinedPermitCount > 15000, "Most valid Louisville permit points should spatially join to Jefferson parcels");
assert(permit.unlocatedPermitCount > 0, "Invalid source coordinates must stay quarantined");
assert(permit.chunks.length > 100, "Permit output must remain viewport-sharded");
assert.equal(permit.productionActivation, false);
assert.equal(development.joinedPermitCount, permit.joinedPermitCount);
assert(development.parcelCountWithSignals > 10000);
assert.equal(development.productionActivation, false);
assert.equal(pkg.scripts["jefferson:permits:build"], "node scripts/build-jefferson-ky-permit-intelligence.cjs");
assert.equal(pkg.scripts["test:jefferson:permits"], "node tests/jefferson-ky-permit-intelligence.test.cjs");
console.log("White Rabbit Jefferson County permit intelligence tests passed.");
