const assert = require("assert");
const fs = require("fs");
const path = require("path");

(() => {
  const root = path.join(__dirname, "..");
  const report = JSON.parse(fs.readFileSync(path.join(root, "output", "opportunity-decision-workflow-readiness.json"), "utf8"));
  const schema = JSON.parse(fs.readFileSync(path.join(root, "data", "schemas", "opportunity-decision-workflow-readiness.schema.json"), "utf8"));
  assert.equal(report.schemaVersion, schema.properties.schemaVersion.const);
  assert(schema.required.every((field) => schema.properties[field]));
  assert.equal(report.status, "foundation-ready-release-blocked");
  assert(report.checks.every((item) => item.passed));
  assert.deepEqual(report.decisionWorkflow.atomicNamespaces, ["opportunity-intelligence", "alert-routing"]);
  assert.equal(report.decisionWorkflow.canonicalPropertyJoinKey, "whiteRabbitPropertyId");
  assert.equal(report.decisionWorkflow.rawObservationsPersisted, false);
  assert.equal(report.validationEvidence.backtestSample, 500);
  assert.equal(report.validationEvidence.minimumDriftSamplePerFeature, 500);
  assert.equal(report.validationEvidence.leakageAuditPassed, true);
  assert.equal(report.alertBoundary.inAppOnly, true);
  assert.equal(report.alertBoundary.externalProviderContacted, false);
  assert.equal(report.certificationScenario.baselineNetScore, 20);
  assert.equal(report.certificationScenario.changedNetScore, 90);
  assert.equal(report.certificationScenario.queuedWatchlistAlertCount, 1);
  assert.equal(report.certificationScenario.replayPreservedTenantRevision, true);
  assert.equal(report.activation.productionReleaseDecisionPresent, false);
  assert.equal(report.activation.visibleUiActivated, false);
  assert.equal(report.activation.lockedWebsiteDesignChanged, false);
  assert(report.releaseBlockers.length >= 4);
  console.log("White Rabbit opportunity decision workflow readiness artifact tests passed.");
})();
