const assert = require("assert");
const fs = require("fs");
const os = require("os");
const path = require("path");

(async () => {
  const feeds = await import("../src/operations/feedCertification.mjs");
  const telemetry = await import("../src/operations/serviceObservability.mjs");
  const runtime = await import("../src/portfolio/operatingConnectorRuntime.mjs");
  const assurance = await import("../src/portfolio/operatingConnectorAssurance.mjs");
  const sdk = await import("../src/portfolio/operatingProviderSdk.mjs");
  const governance = await import("../src/portfolio/providerOnboardingGovernance.mjs");
  const persistence = await import("../src/persistence/platformPersistenceService.mjs");
  const { SqlitePlatformRepository } = await import("../src/persistence/sqlitePlatformRepository.mjs");

  const organizationId = "org-a", connectorId = "yardi-statements", now = "2026-11-15T12:00:00.000Z", yardiProfile = sdk.OPERATING_VENDOR_SANDBOX_PROFILES.find((item) => item.providerId === "yardi");
  const manifest = feeds.createFeedConnectorManifest({ connectorId, connectorVersion: "1.0.0", providerId: "yardi", datasetId: "operating-statements", expectedEventSchemaVersion: "wr-operating-feed-record-v1", licenseId: "yardi-license", contractStartsAt: "2026-01-01", contractExpiresAt: "2027-12-31", thresholds: { minimumFixtureCount: 1, minimumSampleCount: 1, minimumGeometryPct: 0 } });
  const feedEvidence = feeds.createFeedCertificationEvidence({ connectorId, connectorVersion: "1.0.0", generatedAt: "2026-11-15T11:00:00.000Z", license: { contractExecuted: true, licenseId: "yardi-license", rights: { store: true, derive: true, query: true } }, schema: { schemaVersion: "wr-operating-feed-record-v1", fixtureCount: 25, failedFixtureCount: 0 }, pointInTime: { futureEvidenceRejected: true, availabilityTimePreserved: true, expiryEnforced: true }, replay: { idempotencyPassed: true, checkpointResumePassed: true, duplicateWriteCount: 0 }, freshness: { sampleCount: 100, p95LagMs: 100, maxLagMs: 200, currentPct: 100 }, coverage: { sampleCount: 100, canonicalIdentityPct: 100, requiredFieldPct: 100, geometryPct: 100 }, dataQuality: { duplicatePct: 0, invalidIdentityPct: 0, quarantinePct: 0 }, security: { secretRefOnly: true, encryptedTransport: true, ssrfProtection: true, leastPrivilege: true }, loadReport: { schemaVersion: "wr-load-resilience-report-v1", status: "passed" }, provenance: { artifactSha256: "a".repeat(64), testRunId: "governance-1", independentReviewer: true } });
  const connector = runtime.createOperatingConnector({ organizationId, connectorId, connectorVersion: "1.0.0", providerId: "yardi", datasetId: "operating-statements", baseUrl: "https://tenant-api.example.com/yardi", allowedHosts: ["tenant-api.example.com"], credentialRef: "secret-ref:vault/yardi-v1", licenseId: "yardi-license", rights: { store: true, derive: true, query: true }, mappingProfileId: "yardi-statement-map", mappingProfileVersion: 1, certification: feeds.certifyFeedConnector({ manifest, evidence: feedEvidence, asOf: now }) });
  const runtimeMapping = runtime.createOperatingMappingProfile({ id: "yardi-statement-map", organizationId, connectorId, version: 1, targetKind: "operating-statement", mappings: [{ sourceField: "statement_id", targetPath: "id", required: true }, { sourceField: "asset_id", targetPath: "assetId", required: true }, { sourceField: "period_start", targetPath: "periodStart", required: true }, { sourceField: "period_end", targetPath: "periodEnd", required: true }, { sourceField: "expected_accounts", targetPath: "expectedAccountCodes", required: true }, { sourceField: "entries", targetPath: "entries", required: true }], constants: { organizationId, whiteRabbitPropertyId: "wrp:v1:dallas-county-dcad:A1", basis: "accrual", currency: "USD" }, createdByUserId: "integration-author", createdAt: now, approvedByUserId: "integration-approver", approvedAt: "2026-11-15T11:05:00.000Z" });

  const taxonomy = governance.WHITE_RABBIT_ACCOUNT_TAXONOMY;
  assert(taxonomy.accounts.some((item) => item.code === "RENT_BASE" && item.includedInNoi));
  assert(taxonomy.accounts.some((item) => item.code === "CAPITAL_EXPENDITURE" && !item.includedInNoi));
  assert.throws(() => governance.createCanonicalAccountTaxonomy({ accounts: [{ code: "DUP", name: "A" }, { code: "DUP", name: "B" }], createdAt: now }), /unique/);
  const accountMapping = governance.createVendorAccountMappingProfile({ id: "yardi-coa-v1", organizationId, connectorId, providerId: "yardi", vendorProfileId: yardiProfile.id, version: 1, taxonomy, mappings: [{ sourceAccountCode: "4000", sourceAccountName: "Base Rent", canonicalCode: "RENT_BASE", multiplier: -1, required: true }, { sourceAccountCode: "5000", sourceAccountName: "Property Tax", canonicalCode: "PROPERTY_TAX", multiplier: 1, required: true }, { sourceAccountCode: "5100", sourceAccountName: "Insurance", canonicalCode: "INSURANCE", multiplier: 1 }], effectiveFrom: "2026-01-01", createdByUserId: "accounting-integrator", createdAt: "2026-11-15T10:00:00.000Z", approvedByUserId: "controller", approvedAt: "2026-11-15T10:30:00.000Z" });
  assert.throws(() => governance.createVendorAccountMappingProfile({ ...accountMapping, mappingSha256: undefined, approvedByUserId: "accounting-integrator", taxonomy }), (error) => error.code === "WR_ACCOUNT_MAPPING_APPROVAL_SEPARATION_REQUIRED");
  assert.throws(() => governance.createVendorAccountMappingProfile({ ...accountMapping, mappingSha256: undefined, mappings: [{ sourceAccountCode: "x", canonicalCode: "NOT_REAL" }], taxonomy }), /Unknown canonical account/);
  const sourceStatement = { id: "yardi-oct", assetId: "asset-1", periodStart: "2026-10-01", periodEnd: "2026-10-31", currency: "USD", entries: [{ sourceAccountCode: "4000", sourceAccountName: "Base Rent", amount: -10000, status: "observed" }, { sourceAccountCode: "5000", sourceAccountName: "Property Tax", amount: 3000, status: "observed" }, { sourceAccountCode: "5100", sourceAccountName: "Insurance", amount: 1000, status: "observed" }] };
  const canonicalResult = governance.mapVendorAccountingStatement(accountMapping, sourceStatement, { taxonomy, asOf: "2026-10-31" });
  assert.equal(canonicalResult.status, "complete"); assert.equal(canonicalResult.mappedEntries.find((item) => item.accountCode === "RENT_BASE").amount, 10000);
  const quality = governance.evaluateAccountingReconciliationQuality(canonicalResult, { evaluatedAt: now, minimumScore: 95, controlTolerance: 0.01, controlTotals: { revenue: 10000, operatingExpense: 4000, noi: 6000 } });
  assert.equal(quality.status, "passed"); assert.equal(quality.score, 100); assert.equal(quality.activationAuthorized, true);
  const partialResult = governance.mapVendorAccountingStatement(accountMapping, { ...sourceStatement, id: "yardi-partial", entries: [sourceStatement.entries[0], { sourceAccountCode: "9999", sourceAccountName: "Mystery", amount: 500, status: "observed" }] }, { taxonomy, asOf: "2026-10-31" });
  const failedQuality = governance.evaluateAccountingReconciliationQuality(partialResult, { evaluatedAt: now, minimumScore: 95, controlTotals: { revenue: 10000, operatingExpense: 4000, noi: 6000 } });
  assert.equal(failedQuality.status, "failed"); assert(failedQuality.blockers.includes("unmapped-accounts")); assert(failedQuality.blockers.includes("required-accounts-missing"));
  const duplicateResult = governance.mapVendorAccountingStatement(accountMapping, { ...sourceStatement, id: "yardi-duplicate", entries: [...sourceStatement.entries, sourceStatement.entries[0]] }, { taxonomy, asOf: "2026-10-31" }); assert.deepEqual(duplicateResult.duplicateSourceAccountCodes, ["4000"]);

  const normalizer = governance.createCanonicalStatementNormalizer(accountMapping, { taxonomy, currency: "USD" });
  const normalizedFields = normalizer.normalize({ statement_id: "yardi-oct", asset_id: "asset-1", period_start: "2026-10-01", period_end: "2026-10-31", vendor_entries: sourceStatement.entries });
  assert.deepEqual(normalizedFields.expected_accounts, ["INSURANCE", "PROPERTY_TAX", "RENT_BASE"]); assert.equal(normalizedFields.entries.find((item) => item.accountCode === "RENT_BASE").category, "revenue");
  const resolver = sdk.createManagedSecretResolver({ backend: { resolve: async (reference) => ({ reference, organizationId, connectorId, version: "1", validFrom: "2026-01-01", expiresAt: "2027-01-01", value: { token: "secret" } }) }, auditSink: { record() {} }, clock: () => now });
  const canonicalAdapter = sdk.createOperatingProviderAdapter({ profile: yardiProfile, secretResolver: resolver, allowedHosts: connector.allowedHosts, recordNormalizer: normalizer, clock: () => now, transport: { fetchPage: async () => ({ status: 200, body: { responseId: "canonical-response", fetchedAt: now, hasMore: false, records: [{ id: "raw-1", sequence: 0, cursor: "c0", observedAt: "2026-11-15T11:00:00Z", availableAt: "2026-11-15T11:01:00Z", effectiveAt: "2026-10-31T23:59:59Z", fields: { statement_id: "yardi-oct", asset_id: "asset-1", period_start: "2026-10-01", period_end: "2026-10-31", vendor_entries: sourceStatement.entries } }] } }) } });
  const canonicalPage = await canonicalAdapter.fetchPage({ organizationId, connectorId, providerId: "yardi", baseUrl: connector.baseUrl, credentialRef: connector.credentialRef, cursor: "", limit: 10, mode: "incremental", idempotencyKey: "canonical-fetch" }); assert.equal(canonicalPage.records[0].fields.entries.length, 3);

  const schemaBaseline = assurance.createConnectorSchemaBaseline({ id: "yardi-schema", organizationId, connectorId, version: 1, sampleRecords: [normalizedFields], requiredPaths: ["statement_id", "asset_id", "entries", "entries[].accountCode"], createdByUserId: "data-engineer", createdAt: now, approvedByUserId: "data-governor", approvedAt: "2026-11-15T11:10:00Z" });
  const credential = assurance.createConnectorCredentialBinding({ id: "yardi-credential", organizationId, connectorId, version: 1, secretRef: connector.credentialRef, validFrom: "2026-01-01", expiresAt: "2027-01-01", status: "active", createdByUserId: "security", createdAt: "2026-01-01", evidenceRefs: ["evidence-ref:vault"] });
  const drillPlan = assurance.createConnectorDrillPlan({ id: "yardi-drills", organizationId, connectorId, connectorSha256: connector.connectorSha256, createdByUserId: "sre", createdAt: "2026-11-14T09:00:00Z", approvedByUserId: "sre-director", approvedAt: "2026-11-14T10:00:00Z" });
  const drillResult = await assurance.runConnectorDrillSuite(drillPlan, ({ scenario }) => ({ passed: true, assertionCount: 3, durationMs: 10, evidenceRefs: [`evidence-ref:${scenario}`] }), { startedAt: "2026-11-14T11:00:00Z", completedAt: "2026-11-14T11:05:00Z" });
  const collector = telemetry.createTelemetryCollector({ organizationId }); collector.record({ organizationId, serviceName: "operating-connector", operation: "fetch-page", traceId: "slo", spanId: "slo-1", startedAt: "2026-11-15T11:59:00Z", endedAt: "2026-11-15T11:59:00.100Z", status: "success", measurements: { durationMs: 100, saturationPct: 10, sourceLagMs: 1000 }, attributes: { connectorId, providerId: "yardi" } });
  const sloReport = telemetry.evaluateServiceSlo(collector.snapshot({ capturedAt: now, serviceName: "operating-connector", operation: "fetch-page" }), telemetry.createServiceSloPolicy({ serviceName: "operating-connector", operation: "fetch-page", windowMinutes: 10, minimumSampleCount: 1, availabilityTargetPct: 99, latencyP95Ms: 500, maxSaturationPct: 80, maxSourceLagMs: 5000 }), { evaluatedAt: now });
  const adapterCertification = assurance.certifyOperatingAdapter({ connector, mappingProfile: runtimeMapping, schemaBaseline, credentialBinding: credential, drillResult, sloReport, reviewerUserId: "independent-reviewer", certifiedAt: now });
  const vendorPack = sdk.buildVendorSandboxCertificationPack({ id: "yardi-pack", profile: yardiProfile, connector, adapterCertification, evaluatedAt: now, sandboxEvidence: { programEnrollmentApproved: true, dataExchangeAgreementExecuted: true, sandboxAccessConfirmed: true, tenantAuthorizationConfirmed: true, cursorSemanticsVerified: true, rateLimitSemanticsVerified: true, correctionAndDeletionSemanticsVerified: true, fixtureCount: 25, failedFixtureCount: 0, evidenceRefs: ["evidence-ref:program", "evidence-ref:agreement", "evidence-ref:sandbox"] } });
  const lifecycle = governance.evaluateProviderCertificationLifecycle({ connector, adapterCertification, vendorPack, mappingProfile: accountMapping, qualityReport: quality, drillResult, sloReport, evaluatedAt: "2026-11-15T12:30:00Z", policy: { warningDays: 1 } });
  assert.equal(lifecycle.status, "current"); assert.equal(lifecycle.activationAuthorized, true);
  const warningLifecycle = governance.evaluateProviderCertificationLifecycle({ connector, adapterCertification, vendorPack, mappingProfile: accountMapping, qualityReport: quality, drillResult, sloReport, evaluatedAt: "2026-11-20T12:00:00Z", policy: { warningDays: 7 } }); assert.equal(warningLifecycle.status, "warning"); assert.equal(warningLifecycle.activationAuthorized, false);
  const expiredLifecycle = governance.evaluateProviderCertificationLifecycle({ connector, adapterCertification, vendorPack, mappingProfile: accountMapping, qualityReport: quality, drillResult, sloReport, evaluatedAt: "2027-01-01T00:00:00Z" }); assert.equal(expiredLifecycle.status, "suspended"); assert(expiredLifecycle.blockers.includes("connector-slo"));
  const tamperedAdapterLifecycle = governance.evaluateProviderCertificationLifecycle({ connector, adapterCertification: { ...adapterCertification, reviewerUserId: "tampered" }, vendorPack, mappingProfile: accountMapping, qualityReport: quality, drillResult, sloReport, evaluatedAt: "2026-11-15T12:30:00Z", policy: { warningDays: 1 } }); assert.equal(tamperedAdapterLifecycle.status, "suspended"); assert(tamperedAdapterLifecycle.blockers.includes("adapter-certification"));

  let workflow = governance.createProviderOnboardingWorkflow({ id: "yardi-onboarding", connector, vendorProfileId: yardiProfile.id, createdByUserId: "integration-lead", createdAt: now });
  const approve = (stageId, input, occurredAt) => { workflow = governance.approveProviderOnboardingStage(workflow, stageId, { connector, submittedByUserId: `${stageId}-submitter`, evidenceRefs: [`evidence-ref:${stageId}`], expiresAt: "2027-06-01T00:00:00Z", ...input }, { organizationId, actorUserId: `${stageId}-approver`, grants: ["provider:onboarding-approve"], expectedRevision: workflow.revision, occurredAt }); };
  assert.throws(() => governance.approveProviderOnboardingStage(workflow, "data-quality", { connector, submittedByUserId: "submitter", evidenceRefs: ["evidence-ref:quality"], expiresAt: "2027-06-01T00:00:00Z", qualityReport: quality }, { organizationId, actorUserId: "approver", grants: ["provider:onboarding-approve"], expectedRevision: workflow.revision, occurredAt: "2026-11-15T12:01:00Z" }), (error) => error.code === "WR_PROVIDER_ONBOARDING_DEPENDENCY_NOT_READY");
  approve("provider-selection", {}, "2026-11-15T12:01:00Z"); approve("commercial-legal", {}, "2026-11-15T12:02:00Z"); approve("sandbox-access", {}, "2026-11-15T12:03:00Z"); approve("mapping-governance", { mappingProfile: accountMapping }, "2026-11-15T12:04:00Z"); approve("data-quality", { qualityReport: quality }, "2026-11-15T12:05:00Z"); approve("security-privacy", { vendorPack }, "2026-11-15T12:06:00Z"); approve("operations-readiness", { lifecycleReport: lifecycle }, "2026-11-15T12:07:00Z");
  assert.equal(workflow.status, "production-ready"); assert.equal(workflow.revision, 8);
  assert.equal(governance.evaluateProviderOnboardingReadiness(workflow, connector, { evaluatedAt: "2026-12-01T00:00:00Z" }).status, "production-ready");
  const suspendedReadiness = governance.evaluateProviderOnboardingReadiness(workflow, connector, { evaluatedAt: "2027-06-02T00:00:00Z" }); assert.equal(suspendedReadiness.status, "suspended"); assert.equal(suspendedReadiness.activationAuthorized, false); assert.equal(suspendedReadiness.expiredStageIds.length, 7);
  assert.throws(() => governance.approveProviderOnboardingStage(governance.createProviderOnboardingWorkflow({ connector, vendorProfileId: yardiProfile.id, createdByUserId: "x", createdAt: now }), "provider-selection", { connector, submittedByUserId: "same", evidenceRefs: ["evidence-ref:x"], expiresAt: "2027-01-01" }, { organizationId, actorUserId: "same", grants: ["provider:onboarding-approve"], expectedRevision: 1, occurredAt: "2026-11-15T12:01:00Z" }), (error) => error.code === "WR_PROVIDER_ONBOARDING_APPROVAL_SEPARATION_REQUIRED");

  const incidentPolicy = governance.createProviderIncidentRoutingPolicy({ id: "provider-incidents", organizationId, createdAt: now, rules: [{ codePrefix: "WR_PROVIDER_AUTH", severity: "critical", queue: "security-on-call", acknowledgeWithinMinutes: 10, resolveWithinMinutes: 60 }, { codePrefix: "WR_CONNECTOR_SCHEMA", severity: "high", queue: "data-governance", acknowledgeWithinMinutes: 30, resolveWithinMinutes: 240 }, { codePrefix: "WR_RECONCILIATION", severity: "high", queue: "accounting-operations", acknowledgeWithinMinutes: 30, resolveWithinMinutes: 240 }, { codePrefix: "*", severity: "medium", queue: "integration-operations", acknowledgeWithinMinutes: 60, resolveWithinMinutes: 480 }] });
  let incident = governance.routeProviderIncident(incidentPolicy, { organizationId, connectorId, errorCode: "WR_CONNECTOR_SCHEMA_DRIFT", occurredAt: "2026-11-15T12:10:00Z", evidenceRefs: ["evidence-ref:drift-assessment"] }); assert.equal(incident.queue, "data-governance"); assert.equal(incident.occurrenceCount, 1);
  incident = governance.routeProviderIncident(incidentPolicy, { organizationId, connectorId, errorCode: "WR_CONNECTOR_SCHEMA_DRIFT", occurredAt: "2026-11-15T12:11:00Z", evidenceRefs: ["evidence-ref:drift-assessment-2"] }, incident); assert.equal(incident.occurrenceCount, 2);
  assert.throws(() => governance.routeProviderIncident(incidentPolicy, { organizationId, connectorId, errorCode: "WR_PROVIDER_AUTHENTICATION_FAILED", occurredAt: "2026-11-15T12:12:00Z", evidenceRefs: ["evidence-ref:auth"] }, incident), (error) => error.code === "WR_PROVIDER_INCIDENT_DEDUPE_CONFLICT");

  let state = governance.createProviderGovernanceState({ organizationId, connectors: [connector], onboardingWorkflows: [workflow], incidents: [incident], lifecycleReports: [lifecycle], accountMappings: [accountMapping], qualityReports: [quality], updatedAt: "2026-11-15T12:11:00Z" });
  assert.throws(() => governance.acknowledgeProviderIncident(state, incident.id, { organizationId, actorUserId: "operator", grants: [], expectedRevision: state.revision, occurredAt: "2026-11-15T12:12:00Z" }), (error) => error.code === "WR_PROVIDER_INCIDENT_PERMISSION_DENIED");
  state = governance.acknowledgeProviderIncident(state, incident.id, { organizationId, actorUserId: "operator", grants: ["provider:incident-manage"], expectedRevision: state.revision, occurredAt: "2026-11-15T12:12:00Z" }); assert.equal(state.incidents[0].status, "acknowledged");
  assert.throws(() => governance.resolveProviderIncident(state, incident.id, {}, { organizationId, actorUserId: "operator", grants: ["provider:incident-manage"], expectedRevision: state.revision, occurredAt: "2026-11-15T12:13:00Z" }), /evidence-ref/);
  state = governance.resolveProviderIncident(state, incident.id, { evidenceRefs: ["evidence-ref:mapping-corrected", "evidence-ref:replay-passed"] }, { organizationId, actorUserId: "operator", grants: ["provider:incident-manage"], expectedRevision: state.revision, occurredAt: "2026-11-15T12:13:00Z" }); assert.equal(state.incidents[0].status, "resolved");
  assert.throws(() => governance.createProviderGovernanceState({ ...state, stateSha256: undefined, qualityReports: [{ ...quality, score: 1 }] }), (error) => error.code === "WR_RECONCILIATION_QUALITY_INTEGRITY_FAILURE");

  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "white-rabbit-provider-governance-")), dbPath = path.join(tempDir, "governance.sqlite"), context = { organizationId, actorUserId: "governance-worker", subjectUserId: "governance-worker", sessionId: "session-1", requestId: "request-1", grants: ["persistence:read", "persistence:write"], issuedAt: "2026-11-15T11:00:00Z", expiresAt: "2026-11-15T14:00:00Z" };
  const routerState = governance.createProviderGovernanceState({ ...state, stateSha256: undefined, revision: state.revision + 1, incidents: [incident], updatedAt: "2026-11-15T12:14:00Z" });
  let repository = new SqlitePlatformRepository({ filename: dbPath, clock: () => "2026-11-15T12:15:00Z" }); persistence.persistProviderGovernanceState(repository, context, routerState, { expectedTenantRevision: 0, expectedRecordRevision: 0, idempotencyKey: "provider-governance-state-1", occurredAt: "2026-11-15T12:14:00Z", validation: { now: "2026-11-15T12:14:00Z" } });
  const incidentRouter = governance.createDurableProviderIncidentRouter({ repository, context, policy: incidentPolicy }); const routed = incidentRouter.record({ connector, errorCode: "WR_CONNECTOR_SCHEMA_DRIFT", occurredAt: "2026-11-15T12:15:00Z", evidenceRefs: ["evidence-ref:runtime-drift-3"] }, { expectedTenantRevision: 1 }); assert.equal(routed.incident.occurrenceCount, 3); assert.equal(routed.receipt.tenantRevision, 2);
  repository.close(); repository = new SqlitePlatformRepository({ filename: dbPath, clock: () => "2026-11-15T12:16:00Z" });
  const recoveredState = persistence.loadProviderGovernanceState(repository, context, { validation: { now: "2026-11-15T12:16:00Z" } }); assert.equal(recoveredState.onboardingWorkflows[0].status, "production-ready"); assert.equal(recoveredState.incidents[0].occurrenceCount, 3); assert.equal(persistence.loadProviderGovernanceState(repository, { ...context, organizationId: "org-b" }, { validation: { now: "2026-11-15T12:16:00Z" } }), null); repository.close(); fs.rmSync(tempDir, { recursive: true, force: true });

  const schema = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "data", "schemas", "provider-onboarding-governance.schema.json"), "utf8")); assert.equal(schema.$defs.governanceState.properties.schemaVersion.const, "wr-provider-governance-state-v1");
  const gates = fs.readFileSync(path.join(__dirname, "..", "src", "data", "platformFeatureGates.ts"), "utf8"); for (const gate of ["canonicalAccountingTaxonomy", "crossVendorAccountMappings", "reconciliationQualityGates", "providerOnboardingWorkflows", "providerIncidentRouting", "certificationExpiryAutomation"]) assert.match(gates, new RegExp(`${gate}: false`));
  const app = fs.readFileSync(path.join(__dirname, "..", "src", "App.tsx"), "utf8"); assert.equal(app.includes("providerOnboardingGovernance"), false);
  console.log("White Rabbit canonical accounting, reconciliation quality, provider onboarding, incident routing, certification lifecycle, and durability tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
