const assert = require("assert");
const fs = require("fs");
const path = require("path");
const { pathToFileURL } = require("url");

(async () => {
  const root = path.join(__dirname, "..");
  const tools = await import(pathToFileURL(path.join(root, "src/platform/savantTools.mjs")).href);
  const valid = tools.validateResoListing({ ListingKey: "1", StandardStatus: "Active", ListPrice: 100000, PropertyType: "Residential", UnparsedAddress: "1 Main St" });
  assert.equal(valid.valid, true);
  assert.equal(tools.validateResoListing({ ListingKey: "1" }).valid, false);
  assert.equal(tools.evaluateOutreachReadiness({ phone: "502-555-0100", channel: "call" }).ready, true);
  assert.equal(tools.evaluateOutreachReadiness({ phone: "502-555-0100", channel: "sms" }).ready, false);
  assert.equal(tools.evaluateOutreachReadiness({ phone: "502-555-0100", channel: "sms", writtenConsent: true }).ready, true);
  assert.equal(tools.evaluatePilotReadiness({ invitedMembers: 10, activeMembers: 5, listingsLoaded: 10, matchesCreated: 3, followUpsCompleted: 5, openDataErrors: 0 }).ready, true);
  const source = fs.readFileSync(path.join(root, "src/components/SavantToolsPage.tsx"), "utf8");
  const appSource = fs.readFileSync(path.join(root, "src/App.tsx"), "utf8");
  const radar = JSON.parse(fs.readFileSync(path.join(root, "public", "data", "savant-tools", "development-path-radar.json"), "utf8"));
  for (const label of ["Production Backbone Workspace", "RESO Listing Feed Validator", "County Activation Inspector", "Deal Formula Lab", "Buyer-to-Listing Matchmaker", "Outreach Compliance Guard", "Savant Agent Orchestrator", "Nearby Development Impact", "Controlled Pilot Tracker"]) assert(!source.includes(label), `${label} must not be listed in Savant Tools`);
  assert(source.includes('data-page="savant-tools"'));
  assert(source.includes('data-savant-tools-entry="true"'));
  assert(source.includes('data-savant-development-path-radar="true"'));
  assert(source.includes("Development Path Radar"));
  assert(source.includes("Off-market parcels, assemblage, growth patterns, and developer control"));
  assert(source.includes('data-savant-radar-candidates="true"'));
  assert(source.includes('data-savant-radar-candidate="true"'));
  assert(source.includes("const RADAR_PAGE_SIZE = 5"), "Development Path Radar must use a bounded five-parcel page size");
  assert(source.includes('data-savant-radar-pagination="true"'), "Development Path Radar must expose pagination controls");
  assert(source.includes('const SAVANT_MAINTENANCE_STATUS_URL = "/data/savant-tools/maintenance-status.json"'), "Savant Tools must load disconnected maintenance-agent health");
  assert(source.includes('data-savant-maintenance-health={maintenanceStatus.status}'), "Savant Tools must expose maintenance health status");
  assert(source.includes('data-savant-maintenance-warning="true"'), "Savant Tools must warn when a refresh is not publication-authorized");
  assert(source.includes("Page {formatNumber(radarPage + 1)} of {formatNumber(radarPageCount)}"), "Development Path Radar must report the active page");
  assert(source.includes("Math.min(radarPageCount - 1, page + 1)"), "Development Path Radar next-page control must stop at the final page");
  assert(source.includes("Math.max(0, page - 1)"), "Development Path Radar previous-page control must stop at the first page");
  assert(source.includes('const SAVANT_RADAR_URL = "/data/savant-tools/development-path-radar.json"'));
  assert(source.includes("onOpenMap(candidate.accountNum)"));
  assert(appSource.includes("onOpenMap={(query = \"\") => openListingMap(query)}"));
  assert(appSource.includes("onOpenTools={openTools}"), "WhiteRabbitMap must receive the Savant Tools opener");
  assert(appSource.includes("onClick={openTools}"), "Landing rabbit logo must open Savant Tools");
  assert(appSource.includes("onClick={onOpenTools}"), "Live-map rabbit logo must open Savant Tools");
  assert(appSource.includes('aria-label="Open Savant Tools"'), "Rabbit logo action must be accessible as Savant Tools");
  assert((appSource.match(/data-rabbit-action="open-savant-tools"/g) || []).length >= 2, "Top-left rabbit logos must point to Savant Tools");
  assert.equal(radar.schemaVersion, "wr-savant-development-path-radar-v1");
  assert.equal(radar.sourceParcelFeatureCount, 696601);
  assert.equal(radar.opportunityCandidateCount, 3592);
  assert.equal(radar.analyzedCandidateCount, 3592);
  assert(radar.reasonCounts.offMarketDevelopmentPath > 0, "Development Path Radar must identify off-market development path candidates");
  assert(radar.reasonCounts.sameBlockAssemblage > 0, "Development Path Radar must identify same-block assemblage candidates");
  assert(radar.reasonCounts.growthPattern > 0, "Development Path Radar must identify growth-pattern candidates");
  assert(radar.reasonCounts.developerSurroundingControl > 0, "Development Path Radar must identify developer-control candidates");
  assert(radar.topCandidates.length >= 25, "Development Path Radar must expose a usable candidate list");
  assert(radar.topCandidates.some((candidate) => candidate.reasonCodes.includes("developer-surrounding-control")));
  assert(source.includes("They appear in context instead of being presented as a separate catalog of ideas."));
  console.log("White Rabbit contextual Savant Tools entry tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
