const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const artifact = JSON.parse(fs.readFileSync(path.join(root, "output/tarrant/tile-delivery-readiness/tarrant-tile-delivery-readiness.json"), "utf8"));
assert.equal(artifact.schemaVersion, "wr-tarrant-tile-delivery-readiness-v1");
for (const count of Object.values(artifact.sourceBundle.counts)) assert.equal(count, 758633);
assert.equal(artifact.sourceBundle.chunkCount, 1608);
assert.equal(artifact.sourceBundle.searchShardCount, 1111);
assert.equal(artifact.sourceBundle.checks.find((item) => item.id === "count-parity").passed, true);
assert.equal(artifact.sourceBundle.checks.find((item) => item.id === "output-lineage").passed, true);
assert.equal(artifact.sourceBundle.checks.find((item) => item.id === "source-to-output-lineage").passed, false);
assert.equal(artifact.sourceBundle.status, "blocked");
assert.equal(artifact.propertyPolicy.status, "draft");
assert.equal(artifact.propertyPolicy.forbiddenIncluded.length, 0);
assert.equal(artifact.buildPlan.sourceMode, "viewport-chunk-stream");
assert.equal(artifact.buildPlan.status, "blocked");
assert.equal(artifact.tooling.tippecanoeVerified, false);
assert.equal(artifact.sourceGeoJsonPresent, false);
assert.equal(artifact.chunkStreamAvailable, true);
assert.equal(artifact.pmtilesArtifactPresent, false);
assert.equal(artifact.artifactAudit.status, "rejected");
assert.equal(artifact.publicationDecision.status, "rejected");
assert.equal(artifact.viewportFallbackPreserved, true);
assert.equal(artifact.activationAuthorized, false);
const builder = fs.readFileSync(path.join(root, "output/tarrant/vector-tiles/build-tarrant-pmtiles.ps1"), "utf8");
assert(builder.includes("758633"));
assert(builder.includes(artifact.sourceBundle.parcelManifestSha256));
assert(builder.includes(artifact.sourceBundle.chunkInventorySha256));
assert(builder.includes("sourceToOutputCertified"));
assert(builder.includes("stream-county-parcels-ndjson.cjs"));
assert(builder.includes("verify-pmtiles-artifact.cjs"));
console.log("White Rabbit Tarrant tile delivery is exact, privacy-minimized, build-ready, fallback-safe, and activation-blocked.");
