const assert = require("assert");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const root = path.resolve(__dirname, "..");
const directory = path.join(root, "output/tarrant/source-capture-readiness");
const readiness = JSON.parse(fs.readFileSync(path.join(directory, "tarrant-source-capture-readiness.json"), "utf8"));
const metadata = fs.readFileSync(path.join(directory, "official-layer-metadata.json"));
const count = fs.readFileSync(path.join(directory, "official-count-response.json"));
assert.equal(readiness.schemaVersion, "wr-tarrant-source-capture-readiness-v1");
assert.equal(readiness.countyId, "tarrant-county-tad");
assert.equal(readiness.officialSource.currentAccountFeatureCount, 758633);
assert.equal(readiness.officialSource.priorAuditedAccountFeatureCount, 758633);
assert.equal(readiness.officialSource.countDrift, 0);
assert.equal(readiness.officialSource.maximumRecordCount, 10000);
assert.equal(readiness.officialSource.supportsPagination, true);
assert.equal(readiness.capturePlan.expectedPageCount, 76);
assert.equal(readiness.capturePlan.orderBy, "OBJECTID");
assert.equal(crypto.createHash("sha256").update(metadata).digest("hex"), readiness.responseEvidence.metadata.sha256);
assert.equal(crypto.createHash("sha256").update(count).digest("hex"), readiness.responseEvidence.count.sha256);
assert.equal(readiness.gates.officialHttpsSource, true);
assert.equal(readiness.gates.exactCountStable, true);
assert.equal(readiness.gates.licenseEvidencePresent, false);
assert.equal(readiness.gates.rawCapturePresent, false);
assert.equal(readiness.captureReady, false);
assert.equal(readiness.captureStarted, false);
assert.equal(readiness.productionActivationAuthorized, false);
assert.equal(readiness.pageDesignChanged, false);
assert(!fs.existsSync(path.join(root, "data/licenses/tarrant-tad-public-records-license-evidence.json")), "test assumes no license rights are being invented");
assert(!fs.existsSync(path.join(root, "data/raw/tarrant/tad-parcels/capture-state.json")), "raw capture must remain unstarted before license evidence");
const denied = spawnSync(process.execPath, [path.join(root, "scripts/capture-tarrant-raw-source.cjs")], { cwd: root, encoding: "utf8" });
assert.notEqual(denied.status, 0);
assert((denied.stderr + denied.stdout).includes("WR_TARRANT_LICENSE_EVIDENCE_REQUIRED"));
assert(!fs.existsSync(path.join(root, "data/raw/tarrant/tad-parcels/capture-state.json")), "denied launcher must not create capture state");
const markdown = fs.readFileSync(path.join(directory, "tarrant-source-capture-readiness.md"), "utf8");
assert(markdown.includes("758,633"));
assert(markdown.includes("Expected pages: **76**"));
assert(markdown.includes("Capture started: **no**"));
console.log("White Rabbit official TAD readiness evidence and license-gated no-capture tests passed.");
