const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const artifact = JSON.parse(fs.readFileSync(path.join(root, "output/tarrant/permit-readiness/tarrant-permit-readiness.json"), "utf8"));
const tarrant = artifact.probes.find((item) => item.sourceId === "tarrant-transportation-utility-permits");
const fortWorth = artifact.probes.find((item) => item.sourceId === "fort-worth-accela-permits");
const arlington = artifact.probes.find((item) => item.sourceId === "arlington-issued-permits-three-year");
assert.equal(tarrant.featureCount, 1652);
assert.equal(tarrant.nonNullCounts.PERMIT_NO, 1652);
assert.equal(tarrant.sourceRole, "county-utility");
assert(tarrant.coverageStatement.includes("not building permits"));
assert.equal(fortWorth.featureCount, 762483);
assert.equal(fortWorth.nonNullCounts.Unique_ID, 762483);
assert.equal(fortWorth.nonNullCounts.Address, 762483);
assert.equal(fortWorth.nonNullCounts.Latitude, 722403);
assert.equal(fortWorth.nonNullCounts.Longitude, 722403);
assert.equal(fortWorth.typeStatusTupleCount, 126);
assert.equal(arlington.featureCount, 18911);
assert.equal(arlington.nonNullCounts.FOLDERSEQUENCE, 18911);
assert.equal(arlington.nonNullCounts.PROPGISID1, 18906);
assert.equal(arlington.typeStatusTupleCount, 29);
assert(arlington.temporalCoverage.includes("rolling three-year"));
assert.deepEqual(artifact.reconciliation.discoveredBuildingJurisdictionIds, ["arlington", "fort-worth"]);
assert.equal(artifact.reconciliation.certifiedBuildingJurisdictionIds.length, 0);
assert.equal(artifact.reconciliation.uncoveredBuildingJurisdictionIds.length, 42);
assert(artifact.reconciliation.nonBuildingSourceIds.includes("tarrant-transportation-utility-permits"));
assert(artifact.normalizationPolicies.every((item) => item.status === "blocked"));
assert.equal(artifact.recordsCaptured, false);
assert.equal(artifact.geometryCaptured, false);
assert.equal(artifact.parcelLinksBuilt, false);
assert.equal(artifact.activationAuthorized, false);
console.log("White Rabbit Tarrant permit sources remain jurisdiction-scoped, exact, metadata-only, and activation-blocked.");
