const assert = require("assert");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const root = path.resolve(__dirname, "..");
const run = spawnSync(process.execPath, [path.join(root, "scripts/build-tarrant-county-release-preflight.cjs")], { cwd: root, encoding: "utf8" });
assert.equal(run.status, 0, run.stderr || run.stdout);

const outputPath = path.join(root, "output/tarrant/release-preflight/tarrant-county-release-preflight.json");
const reportPath = path.join(root, "output/tarrant/release-preflight/tarrant-county-release-preflight.md");
const preflight = JSON.parse(fs.readFileSync(outputPath, "utf8"));
const countyQc = JSON.parse(fs.readFileSync(path.join(root, "output/county-qc/tarrant-county-tad.json"), "utf8"));
const schema = JSON.parse(fs.readFileSync(path.join(root, "data/schemas/tarrant-county-release-preflight.schema.json"), "utf8"));
assert.equal(preflight.schemaVersion, schema.properties.schemaVersion.const);
assert.equal(preflight.countyId, "tarrant-county-tad");
assert.equal(preflight.countyFips, "48439");
assert.equal(preflight.mode, "non-visible-dry-run");
assert.equal(preflight.pageDesignChanged, false);
assert.equal(preflight.productionActivationAttempted, false);
assert.equal(preflight.productionActivationAuthorized, false);
assert.equal(preflight.decision.status, "rejected");
assert.equal(preflight.decision.activationAuthorized, false);

for (const field of ["officialAuditFeatureCount", "emittedFeatureCount", "viewportIndexedFeatureCount", "searchIndexCount", "primaryJoinKeyNonNullCount"]) assert.equal(preflight.exactCounts[field], 758633, `${field} must reconcile exactly`);
assert.equal(preflight.exactCounts.primaryJoinKeyMaxMultiplicity, 1);
assert.equal(preflight.exactCounts.parcelCountParity, true);
assert.equal(preflight.deliveryArtifacts.viewportChunkCount, 1608);
assert.equal(preflight.deliveryArtifacts.searchShardCount, 1111);
assert.equal(preflight.quality.warningCount, countyQc.warningCount, "preflight warning count must equal current county QC evidence");
assert.equal(preflight.quality.failureCount, 0);
assert.equal(preflight.sourceSnapshotCandidate.contentKind, "source-audit");
assert.equal(preflight.artifactBundleCandidate.artifacts.every((item) => item.immutable === false), true);
assert.equal(preflight.lineage.outputLineageCertified, true);
assert.equal(preflight.lineage.sourceToOutputCertified, false);
assert.equal(preflight.jurisdictionBoundaries.cityFeatureCount, 98);
assert.equal(preflight.jurisdictionBoundaries.cityDistinctNameCount, 45);
assert.equal(preflight.jurisdictionBoundaries.etjFeatureCount, 107);
assert.equal(preflight.jurisdictionBoundaries.etjDistinctNameCount, 14);
assert.equal(preflight.jurisdictionBoundaries.etjReconciliationStatus, "inconsistent-needs-review");
assert.deepEqual(preflight.jurisdictionBoundaries.guidanceNamesMissingFromService, ["CROWLEY ETJ"]);
assert.equal(preflight.jurisdictionBoundaries.serviceNamesMissingFromGuidance.length, 9);
assert.equal(preflight.jurisdictionBoundaries.geometryCaptured, false);
assert.equal(preflight.jurisdictionBoundaries.snapshotPolicyStatus, "blocked");
assert.equal(preflight.jurisdictionBoundaries.parcelAssignmentAuthorized, false);
assert.equal(preflight.floodIntelligence.regulatoryCandidateFeatureCount, 18208);
assert.equal(preflight.floodIntelligence.regulatoryCandidateNonNullSourceIdCount, 18208);
assert.equal(preflight.floodIntelligence.regulatoryCandidateSourceIdUniqueness, "unverified");
assert.equal(preflight.floodIntelligence.regulatoryCandidateZoneTupleCount, 30);
assert.equal(preflight.floodIntelligence.planningEstimateFeatureCount, 1149064);
assert.equal(preflight.floodIntelligence.historicalFeatureCount, 4064);
assert.equal(preflight.floodIntelligence.sourceReconciliationStatus, "blocked");
assert(preflight.floodIntelligence.sourceReconciliationBlockers.includes("regulatory-source-id-uniqueness-unverified"));
assert.equal(preflight.floodIntelligence.snapshotPolicyStatus, "blocked");
assert.equal(preflight.floodIntelligence.geometryCaptured, false);
assert.equal(preflight.floodIntelligence.parcelClassificationAuthorized, false);
assert.equal(preflight.permitIntelligence.tarrantUtilityPermitCount, 1652);
assert.equal(preflight.permitIntelligence.fortWorthPermitCount, 767150);
assert.equal(preflight.permitIntelligence.fortWorthCompleteAddressCount, 767150);
assert.equal(preflight.permitIntelligence.fortWorthCompleteCoordinateCount, 726915);
assert.equal(preflight.permitIntelligence.arlingtonRollingThreeYearPermitCount, 18726);
assert.equal(preflight.permitIntelligence.arlingtonCompletePropertyGisIdCount, 18721);
assert.deepEqual(preflight.permitIntelligence.discoveredBuildingJurisdictionIds, ["arlington", "fort-worth"]);
assert.equal(preflight.permitIntelligence.certifiedBuildingJurisdictionCount, 0);
assert.equal(preflight.permitIntelligence.uncoveredBuildingJurisdictionCount, 42);
assert(preflight.permitIntelligence.normalizationPolicyStatuses.every((item) => item === "blocked"));
assert.equal(preflight.permitIntelligence.recordsCaptured, false);
assert.equal(preflight.permitIntelligence.parcelLinksBuilt, false);
assert.equal(preflight.zoningIntelligence.fortWorthCurrentZoningFeatureCount, 10011);
assert.equal(preflight.zoningIntelligence.fortWorthCompleteDistrictCount, 9971);
assert.equal(preflight.zoningIntelligence.fortWorthCompleteBaseDistrictCount, 1439);
assert.equal(preflight.zoningIntelligence.fortWorthCompleteEffectiveDateCount, 1966);
assert.equal(preflight.zoningIntelligence.fortWorthOverlayFeatureCount, 32);
assert.equal(preflight.zoningIntelligence.fortWorthCaseFeatureCount, 115);
assert.equal(preflight.zoningIntelligence.arlingtonCurrentZoningFeatureCount, 6283);
assert.equal(preflight.zoningIntelligence.arlingtonCompleteDistrictCount, 6283);
assert.equal(preflight.zoningIntelligence.arlingtonCompleteEffectiveDateCount, 893);
assert.equal(preflight.zoningIntelligence.arlingtonOverlayFeatureCount, 8);
assert.equal(preflight.zoningIntelligence.arlingtonRollingThreeYearCaseCount, 316);
assert.deepEqual(preflight.zoningIntelligence.discoveredCurrentZoningJurisdictionIds, ["arlington", "fort-worth"]);
assert.equal(preflight.zoningIntelligence.certifiedCurrentZoningJurisdictionCount, 0);
assert.equal(preflight.zoningIntelligence.uncoveredCurrentZoningJurisdictionCount, 42);
assert(preflight.zoningIntelligence.snapshotPolicyStatuses.every((item) => item === "blocked"));
assert.equal(preflight.zoningIntelligence.geometryCaptured, false);
assert.equal(preflight.zoningIntelligence.parcelAssignmentsBuilt, false);
assert.equal(preflight.developmentIntelligence.candidateRecordCount, 781809);
assert.equal(preflight.developmentIntelligence.fortWorthPermitCandidateCount, 762483);
assert.equal(preflight.developmentIntelligence.arlingtonPermitCandidateCount, 18911);
assert.equal(preflight.developmentIntelligence.fortWorthZoningCaseCandidateCount, 109);
assert.equal(preflight.developmentIntelligence.arlingtonZoningCaseCandidateCount, 306);
assert.deepEqual(preflight.developmentIntelligence.discoveredJurisdictionIds, ["arlington", "fort-worth"]);
assert.equal(preflight.developmentIntelligence.certifiedJurisdictionCount, 0);
assert.equal(preflight.developmentIntelligence.uncoveredOrUncertifiedJurisdictionCount, 42);
assert.equal(preflight.developmentIntelligence.draftClassificationRuleCount, 4);
assert.equal(preflight.developmentIntelligence.normalizedEventCount, 0);
assert.equal(preflight.developmentIntelligence.emittedSignalCount, 0);
assert.equal(preflight.developmentIntelligence.signalAuditStatus, "rejected");
assert.equal(preflight.developmentIntelligence.activationAuthorized, false);
assert.equal(preflight.demandIntelligence.sourceRowCount, 674);
assert.equal(preflight.demandIntelligence.inflowRowCount, 353);
assert.equal(preflight.demandIntelligence.outflowRowCount, 321);
assert.equal(preflight.demandIntelligence.aggregateRowCount, 12);
assert.equal(preflight.demandIntelligence.detailRowCount, 662);
assert.equal(preflight.demandIntelligence.invalidRowCount, 0);
assert.equal(preflight.demandIntelligence.duplicateRowCount, 0);
assert.equal(preflight.demandIntelligence.inflowReturns, 61211);
assert.equal(preflight.demandIntelligence.outflowReturns, 59215);
assert.equal(preflight.demandIntelligence.netReturns, 1996);
assert.equal(preflight.demandIntelligence.netExemptions, 2042);
assert.equal(preflight.demandIntelligence.netAgiThousands, -61076);
assert.deepEqual(preflight.demandIntelligence.observedDomains, ["migration"]);
assert.equal(preflight.demandIntelligence.certifiedDomainCount, 0);
assert.equal(preflight.demandIntelligence.missingOrUncertifiedDomains.length, 5);
assert.equal(preflight.demandIntelligence.censusApiKeyRequired, true);
assert.equal(preflight.demandIntelligence.auditStatus, "rejected");
assert.equal(preflight.demandIntelligence.pointInTimeVectorBuilt, false);
assert.equal(preflight.demandIntelligence.parcelDemandScoresBuilt, false);
assert.equal(preflight.demandIntelligence.activationAuthorized, false);
for (const field of ["officialFeatureCount", "manifestFeatureCount", "chunkFeatureCount", "searchFeatureCount"]) assert.equal(preflight.tileDelivery[field], 758633);
assert.equal(preflight.tileDelivery.chunkCount, 1608);
assert.equal(preflight.tileDelivery.searchShardCount, 1111);
assert.match(preflight.tileDelivery.chunkInventorySha256, /^[a-f0-9]{64}$/);
assert.equal(preflight.tileDelivery.outputLineageCertified, true);
assert.equal(preflight.tileDelivery.sourceToOutputCertified, false);
assert.equal(preflight.tileDelivery.propertyPolicyStatus, "draft");
assert.equal(preflight.tileDelivery.forbiddenIncludedFieldCount, 0);
assert.equal(preflight.tileDelivery.tippecanoeVerified, false);
assert.equal(preflight.tileDelivery.sourceGeoJsonPresent, false);
assert.equal(preflight.tileDelivery.chunkStreamAvailable, true);
assert.equal(preflight.tileDelivery.buildPlanStatus, "blocked");
assert.equal(preflight.tileDelivery.pmtilesArtifactPresent, false);
assert.equal(preflight.tileDelivery.artifactAuditStatus, "rejected");
assert.equal(preflight.tileDelivery.httpRangeDeliveryCertified, false);
assert.equal(preflight.tileDelivery.viewportFallbackPreserved, true);
assert.equal(preflight.tileDelivery.publicationStatus, "rejected");
assert.equal(preflight.tileDelivery.activationAuthorized, false);

const failures = new Set(preflight.dryRunSummary.failedCheckIds);
for (const id of ["source-content", "required-artifacts", "qc", "approval:county-data-reviewer", "approval:quality-reviewer", "approval:release-manager", "approval-separation", "platform-release-authorization"]) assert(failures.has(id), `missing fail-closed blocker: ${id}`);
for (const id of ["source-count-reconciliation", "geometry-parity", "identity-parity", "search-parity", "viewport-parity", "lineage-parity", "no-placeholders"]) assert(preflight.dryRunSummary.passedCheckIds.includes(id), `expected local evidence check to pass: ${id}`);

for (const evidence of preflight.observedEvidence) {
  const bytes = fs.readFileSync(path.join(root, evidence.relativePath));
  assert.equal(bytes.length, evidence.bytes, `byte count drift: ${evidence.relativePath}`);
  assert.equal(crypto.createHash("sha256").update(bytes).digest("hex"), evidence.sha256, `digest drift: ${evidence.relativePath}`);
}

const markdown = fs.readFileSync(reportPath, "utf8");
assert(markdown.includes("rejected as expected"));
assert(markdown.includes("758,633"));
assert(markdown.includes("Production activation attempted: no"));
const gates = fs.readFileSync(path.join(root, "src/data/platformFeatureGates.ts"), "utf8");
assert(/priorityCountyActivation:\s*false/.test(gates));
assert(/countyAtomicPromotion:\s*false/.test(gates));
const adapter = JSON.parse(fs.readFileSync(path.join(root, "data/county-adapters/tarrant/adapter.json"), "utf8"));
assert.notEqual(adapter.enabledForProduction, true);
const app = fs.readFileSync(path.join(root, "src/App.tsx"), "utf8");
assert(!app.includes("tarrant-county-release-preflight"));
assert(!app.includes("countyReleasePipeline"));
console.log("White Rabbit Tarrant evidence-pack and fail-closed release preflight tests passed.");
