const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const artifact = JSON.parse(fs.readFileSync(path.join(root, "output/tarrant/development-readiness/tarrant-development-readiness.json"), "utf8"));
const byId = (id) => artifact.bindings.find((item) => item.sourceId === id);
assert.equal(artifact.schemaVersion, "wr-tarrant-development-readiness-v1");
assert.equal(byId("fort-worth-accela-permits").candidateRecordCount, 762483);
assert.equal(byId("arlington-issued-permits-three-year").candidateRecordCount, 18911);
assert.equal(byId("fort-worth-zoning-cases").candidateRecordCount, 109);
assert.equal(byId("arlington-zoning-cases-three-year").candidateRecordCount, 306);
assert.equal(artifact.coverage.candidateRecordCount, 781809);
assert.deepEqual(artifact.coverage.discoveredJurisdictionIds, ["arlington", "fort-worth"]);
assert.equal(artifact.coverage.certifiedJurisdictionIds.length, 0);
assert.equal(artifact.coverage.uncoveredOrUncertifiedJurisdictionIds.length, 42);
assert(artifact.bindings.every((item) => item.status === "candidate-only" && item.candidateRecordsAreSignals === false));
assert(artifact.classificationRules.every((item) => item.status === "draft" && item.modelGenerated === false));
assert.equal(artifact.signalAudit.counts.ineligibleRecords, 781809);
assert.equal(artifact.signalAudit.counts.emittedSignals, 0);
assert.equal(artifact.signalAudit.status, "rejected");
assert.equal(artifact.indexManifestCandidate.activationAuthorized, false);
for (const field of ["recordsCaptured", "eventsNormalized", "parcelLinksBuilt", "lifecycleAggregatesBuilt", "signalsEmitted", "activationAuthorized"]) assert.equal(artifact[field], false);
console.log("White Rabbit Tarrant development federation preserves 781,809 candidates as non-signals and remains fail-closed.");
