const assert = require("assert");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

(async () => {
  const root = path.resolve(__dirname, "..");
  const capture = await import("../src/operations/countySourceCapture.mjs");
  const report = JSON.parse(fs.readFileSync(path.join(root, "output/tarrant/lineage-audit/tarrant-output-lineage-audit.json"), "utf8"));
  const manifestBytes = fs.readFileSync(path.join(root, report.outputManifest.relativePath));
  const manifest = JSON.parse(manifestBytes.toString("utf8"));
  assert.equal(report.schemaVersion, "wr-tarrant-output-lineage-report-v1");
  assert.equal(report.countyId, "tarrant-county-tad");
  assert.equal(report.pageDesignChanged, false);
  assert.equal(report.productionActivationAuthorized, false);
  assert.equal(crypto.createHash("sha256").update(manifestBytes).digest("hex"), report.outputManifest.sha256);
  assert.equal(manifest.featureCount, 758633);
  assert.equal(manifest.chunkCount, 1608);
  for (const field of ["observedOutputCount", "uniqueCountyParcelIdCount", "uniqueSourceParcelIdCount", "completeSourceReferenceCount", "canonicalIdentityMatchCount"]) assert.equal(report.counts[field], 758633, `${field} must certify every output`);
  for (const field of ["duplicateCountyParcelIdCount", "duplicateSourceParcelIdCount", "invalidRecordCount"]) assert.equal(report.counts[field], 0, `${field} must remain zero`);
  assert.deepEqual(report.invalidReasonCounts, {});
  assert.equal(report.chunkInventory.length, 1608);
  assert.equal(new Set(report.chunkInventory.map((item) => item.id)).size, 1608);
  assert.equal(report.chunkInventory.reduce((sum, item) => sum + item.observedCount, 0), 758633);
  assert(report.chunkInventory.every((item) => item.declaredCount === item.observedCount && item.bytes > 0 && /^[a-f0-9]{64}$/.test(item.sha256)));
  const byId = new Map(manifest.chunks.map((item) => [item.id, item]));
  assert(report.chunkInventory.every((item) => byId.get(item.id)?.count === item.observedCount));
  assert.equal(capture.verifyCountyOutputLineageAudit(report.audit).valid, true);
  assert.equal(report.audit.outputLineageCertified, true);
  assert.equal(report.audit.sourceToOutputCertified, false);
  assert.equal(report.audit.rawSourceMatchStatus, "unverified-no-raw-source-manifest");
  assert.equal(report.outcome.outputLineageCertified, true);
  assert.equal(report.outcome.sourceToOutputCertified, false);
  const markdown = fs.readFileSync(path.join(root, "output/tarrant/lineage-audit/tarrant-output-lineage-audit.md"), "utf8");
  assert(markdown.includes("758,633"));
  assert(markdown.includes("Raw source-to-output lineage certified: **no**"));
  const app = fs.readFileSync(path.join(root, "src/App.tsx"), "utf8");
  assert(!app.includes("countySourceCapture"));
  console.log("White Rabbit 758633-record Tarrant output-lineage audit verification tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
