const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const artifact = JSON.parse(fs.readFileSync(path.join(root, "output/tarrant/zoning-readiness/tarrant-zoning-readiness.json"), "utf8"));
const byId = (id) => artifact.probes.find((item) => item.sourceId === id);
const fw = byId("fort-worth-current-zoning");
const fwOverlay = byId("fort-worth-zoning-overlays");
const fwCases = byId("fort-worth-zoning-cases");
const ar = byId("arlington-current-zoning");
const arOverlay = byId("arlington-planning-overlays");
const arCases = byId("arlington-zoning-cases-three-year");
assert.equal(fw.featureCount, 10011);
assert.equal(fw.nonNullCounts.ZONING, 9971);
assert.equal(fw.nonNullCounts.BASE_ZONING, 1439);
assert.equal(fw.nonNullCounts.ORD_EFF_DATE, 1966);
assert.equal(fw.nullDistrictCount, 40);
assert.equal(fw.taxonomyTupleCount, 151);
assert.equal(fwOverlay.featureCount, 32);
assert.equal(fwOverlay.taxonomyTupleCount, 24);
assert.equal(fwCases.featureCount, 115);
assert.equal(fwCases.taxonomyTupleCount, 113);
assert.equal(ar.featureCount, 6283);
assert.equal(ar.nonNullCounts.ZONINGDETAIL, 6283);
assert.equal(ar.nonNullCounts.DISTRICT, 6283);
assert.equal(ar.nonNullCounts.EFFECTIVEDATE, 893);
assert.equal(ar.taxonomyTupleCount, 113);
assert.equal(arOverlay.featureCount, 8);
assert.equal(arCases.featureCount, 316);
assert(arCases.temporalCoverage.includes("rolling three-year"));
assert.deepEqual(artifact.reconciliation.discoveredCurrentZoningJurisdictionIds, ["arlington", "fort-worth"]);
assert.equal(artifact.reconciliation.certifiedCurrentZoningJurisdictionIds.length, 0);
assert.equal(artifact.reconciliation.uncoveredCurrentZoningJurisdictionIds.length, 42);
assert(artifact.snapshotPolicies.every((item) => item.status === "blocked"));
assert.equal(artifact.geometryCaptured, false);
assert.equal(artifact.parcelAssignmentsBuilt, false);
assert.equal(artifact.activationAuthorized, false);
console.log("White Rabbit Tarrant zoning sources remain role-separated, exact, metadata-only, and activation-blocked.");
