const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const readJson = (relativePath) => JSON.parse(fs.readFileSync(path.join(root, relativePath), "utf8").replace(/^\uFEFF/, ""));
const assert = (condition, message) => { if (!condition) throw new Error(message); };

const tarrant = readJson("data/county-adapters/tarrant/adapter.json");
const tarrantSource = readJson("data/county-adapters/tarrant/tarrant-county-tad-source-manifest.json");
const tarrantMap = readJson("data/county-adapters/tarrant/tarrant-county-tad-universal-field-map.json");
const collin = readJson("data/county-adapters/collin-county-tx/adapter.json");
const collinSource = readJson("data/county-adapters/collin-county-tx/collin-county-tx-source-manifest.json");
const collinMap = readJson("data/county-adapters/collin-county-tx/collin-county-tx-universal-field-map.json");
const tarrantService = readJson("public/data/counties/tarrant/parcels/manifest.json");
const tarrantSearch = readJson("public/data/counties/tarrant/parcels/search-index.json");
const collinService = readJson("public/data/counties/collin-county-tx/parcels/manifest.json");
const collinSearch = readJson("public/data/counties/collin-county-tx/parcels/search-index.json");
const denton = readJson("data/county-adapters/denton-county-tx/adapter.json");
const dentonSource = readJson("data/county-adapters/denton-county-tx/denton-county-tx-source-manifest.json");
const dentonMap = readJson("data/county-adapters/denton-county-tx/denton-county-tx-universal-field-map.json");
const dentonService = readJson("public/data/counties/denton-county-tx/parcels/manifest.json");
const dentonSearch = readJson("public/data/counties/denton-county-tx/parcels/search-index.json");

assert(tarrant.verifiedCounts.parcelGeometryFeatures === 758633, "Tarrant exact live parcel count must be preserved");
assert(tarrantSource.verified_counts.account_non_null_features === 758633, "Every audited Tarrant feature must have ACCOUNT");
assert(tarrantSource.verified_counts.account_max_observed_multiplicity === 1, "Tarrant ACCOUNT multiplicity evidence must be preserved");
assert(tarrant.joinKeys.primaryParcelAccount.includes("ACCOUNT"), "Tarrant primary join key must be ACCOUNT");
assert(tarrantMap.fields.parcelId === "ACCOUNT", "Tarrant universal map must use ACCOUNT as parcelId");
assert(tarrant.status === "pilot", "Tarrant must remain a pilot until production outputs are built");
assert(tarrantService.mode === "full", "Tarrant parcel service must be a full county build");
assert(tarrantService.activationStatus === "full-build-needs-qc-before-app-activation", "Tarrant full build must remain QC-gated");
assert(tarrantService.sourceVerifiedFeatureCount === 758633, "Tarrant service must preserve the exact official source count");
assert(tarrantService.featureCount === 758633 && tarrantService.skipped === 0, "Tarrant full build must contain every source parcel");
assert(tarrantService.chunkCount === 1608, "Tarrant full viewport chunk count must be locked");
assert(Object.keys(tarrantService.searchIndexShards.files).length === 1111, "Tarrant full search shard count must be locked");
assert(tarrantService.searchIndexCount === 758633, "Tarrant search count must match its parcel count");
assert(tarrantService.joinedAppraisalCount === 758633, "Every Tarrant parcel must carry direct appraisal fields");
assert(tarrantService.joinedParcelDimensionCount === 758633, "Every Tarrant parcel must carry land dimension fields");
assert(tarrantService.buildStrategy === "streamed-page-to-ndjson-to-viewport-service", "Tarrant full build must use the bounded-memory streaming strategy");
assert(Object.keys(tarrantService.searchIndexShards.files).length === tarrantSearch.shardCount, "Tarrant search shard manifest must match its index");
const firstTarrantChunk = readJson(`public/data/counties/tarrant/parcels/${tarrantService.chunks[0].file}`);
const firstTarrantParcel = firstTarrantChunk.parcels[0];
assert(firstTarrantParcel.countyParcelId.startsWith("tarrant-county-tad:"), "Tarrant records must have county-scoped parcel IDs");
assert(/^\d{8}$/.test(firstTarrantParcel.accountNum), "Tarrant ACCOUNT must remain an eight-character string with leading zeroes preserved");
assert(firstTarrantParcel.ownerPhone === "" && firstTarrantParcel.ownerEmail === "", "Tarrant must not infer owner contact fields");
assert(firstTarrantParcel.realGeometry?.geometry, "Tarrant sample parcels must retain real geometry");

assert(collin.verifiedCounts.parcelGeometryFeatures === 437063, "Collin exact live parcel count must be preserved");
assert(collinSource.verified_counts.prop_id_missing_features === 691, "Collin PROP_ID missing count must remain documented");
assert(collinSource.verified_counts.prop_id_nonzero_max_observed_multiplicity === 3, "Collin PROP_ID duplicate evidence must remain documented");
assert(collinSource.verified_counts.geo_id_max_observed_multiplicity === 3, "Collin geoID duplicate evidence must remain documented");
assert(collinSource.verified_counts.global_id_non_null_features === 437063, "Every Collin feature must have GlobalID");
assert(collinSource.verified_counts.global_id_max_observed_multiplicity === 1, "Collin GlobalID must remain duplicate-safe");
assert(collin.joinKeys.primaryParcelAccount.includes("GlobalID"), "Collin primary source identity must use GlobalID");
assert(collinMap.identityPolicy.businessKeyStatus === "verified-source-feature-key", "Collin field map must preserve the verified identity status");
assert(collinMap.fields.parcelId === "GlobalID", "Collin universal parcelId must use GlobalID");
assert(collin.status === "pilot", "Collin must remain a pilot until production identity and outputs are complete");
assert(collinService.mode === "full", "Collin parcel service must be a full county build");
assert(collinService.sourceVerifiedFeatureCount === 437063, "Collin service must preserve the exact official source count");
assert(collinService.featureCount === 437061 && collinService.skipped === 2, "Collin full build must preserve its exact geometry-normalization outcome");
assert(collinService.chunkCount === 1604, "Collin full viewport chunk count must be locked");
assert(Object.keys(collinService.searchIndexShards.files).length === 1095, "Collin full search shard count must be locked");
assert(collinService.searchIndexCount === 437061, "Collin search count must match its emitted parcel count");
assert(collinService.joinedAppraisalCount === 437061, "Every emitted Collin parcel must carry direct appraisal fields");
assert(collinService.joinedParcelDimensionCount === 437061, "Every emitted Collin parcel must carry direct parcel dimension fields");
assert(collinService.buildStrategy === "streamed-page-to-ndjson-to-viewport-service", "Collin full build must use bounded-memory streaming");
assert(Object.keys(collinService.searchIndexShards.files).length === collinSearch.shardCount, "Collin search shard manifest must match its index");
const firstCollinChunk = readJson(`public/data/counties/collin-county-tx/parcels/${collinService.chunks[0].file}`);
const firstCollinParcel = firstCollinChunk.parcels[0];
assert(/^collin-county-tx:[0-9a-f-]{36}$/.test(firstCollinParcel.countyParcelId), "Collin records must have county-scoped GlobalID parcel IDs");
assert(firstCollinParcel.ownerPhone === "" && firstCollinParcel.ownerEmail === "", "Collin must not infer owner contact fields");
assert(firstCollinParcel.realGeometry?.geometry, "Collin parcel records must retain real geometry");

assert(denton.verifiedCounts.parcelGeometryFeatures === 384684, "Denton exact live parcel count must be preserved");
assert(dentonSource.verified_counts.global_id_non_null_features === 384684, "Every Denton feature must have GlobalID");
assert(dentonSource.verified_counts.global_id_max_observed_multiplicity === 1, "Denton GlobalID must remain duplicate-safe");
assert(dentonSource.verified_counts.pid_nonzero_max_observed_multiplicity === 5, "Denton pid duplicate evidence must remain documented");
assert(dentonSource.verified_counts.geo_id_non_null_max_observed_multiplicity === 7, "Denton geoID duplicate evidence must remain documented");
assert(denton.joinKeys.primaryParcelAccount.includes("GlobalID"), "Denton source identity must use GlobalID");
assert(dentonMap.fields.parcelId === "GlobalID", "Denton universal parcelId must use GlobalID");
assert(dentonService.mode === "full", "Denton parcel service must be a full county build");
assert(dentonService.sourceVerifiedFeatureCount === 384684, "Denton service must preserve the official source count");
assert(dentonService.featureCount === 384684 && dentonService.skipped === 0, "Denton full build must contain every source feature");
assert(dentonService.chunkCount === 1400, "Denton viewport chunk count must be locked");
assert(Object.keys(dentonService.searchIndexShards.files).length === 1051, "Denton search shard count must be locked");
assert(dentonService.joinedAppraisalCount === 384684, "Every Denton parcel must carry direct appraisal fields");
assert(dentonService.joinedParcelDimensionCount === 384684, "Every Denton parcel must carry dimension fields");
assert(dentonService.buildStrategy === "streamed-page-to-ndjson-to-viewport-service", "Denton must use bounded-memory streaming");
assert(Object.keys(dentonService.searchIndexShards.files).length === dentonSearch.shardCount, "Denton search manifest must match its index");
const firstDentonChunk = readJson(`public/data/counties/denton-county-tx/parcels/${dentonService.chunks[0].file}`);
const firstDentonParcel = firstDentonChunk.parcels[0];
assert(/^denton-county-tx:[0-9a-f-]{36}$/.test(firstDentonParcel.countyParcelId), "Denton records must use county-scoped GlobalID parcel IDs");
assert(firstDentonParcel.ownerPhone === "" && firstDentonParcel.ownerEmail === "", "Denton must not infer owner contacts");
assert(firstDentonParcel.realGeometry?.geometry, "Denton parcel records must retain real geometry");

console.log("Tarrant, Collin, and Denton live-source audit tests passed.");
