const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const artifact = JSON.parse(fs.readFileSync(path.join(root, "output/tarrant/flood-readiness/tarrant-flood-readiness.json"), "utf8"));
const regulatory = artifact.probes.find((item) => item.role === "regulatory-candidate");
const estimated = artifact.probes.find((item) => item.role === "planning-estimate-only");
const historical = artifact.probes.filter((item) => item.role === "historical-only");
assert.equal(regulatory.featureCount, 18208);
assert.equal(regulatory.nonNullSourceIdCount, 18208);
assert.equal(regulatory.sourceIdUniqueness, "unverified");
assert.equal(regulatory.zoneTuples.length, 30);
assert.equal(regulatory.unknownZoneTupleCount, 0);
assert.equal(regulatory.inconsistentSfhaTupleCount, 0);
assert.equal(estimated.featureCount, 1149064);
assert.equal(estimated.nonNullSourceIdCount, 1149064);
assert.equal(estimated.zoneTuples.length, 8);
assert.equal(historical.reduce((sum, item) => sum + item.featureCount, 0), 4064);
assert.equal(artifact.reconciliation.selectedRegulatoryCandidateSourceId, "tarrant-fema-flood-hazards-2025");
assert.equal(artifact.reconciliation.status, "blocked");
assert(artifact.reconciliation.blockers.includes("regulatory-source-id-uniqueness-unverified"));
assert(artifact.reconciliation.blockers.includes("regulatory-geometry-capture-not-authorized"));
assert.equal(artifact.snapshotPolicy.status, "blocked");
assert.equal(artifact.geometryCaptured, false);
assert.equal(artifact.parcelClassificationAuthorized, false);
assert.equal(artifact.activationAuthorized, false);
console.log("White Rabbit Tarrant current, estimated, and legacy flood sources remain exact, role-separated, and activation-blocked.");
