const assert = require("assert");
const fs = require("fs");
const path = require("path");
const artifact = JSON.parse(fs.readFileSync(path.join(__dirname, "../output/tarrant/demand-readiness/tarrant-demand-readiness.json"), "utf8"));
assert.equal(artifact.schemaVersion, "wr-tarrant-demand-readiness-v1");
assert.equal(artifact.exactMigrationSummary.inflowReturns, 61211);
assert.equal(artifact.exactMigrationSummary.outflowReturns, 59215);
assert.equal(artifact.exactMigrationSummary.netReturns, 1996);
assert.equal(artifact.exactMigrationSummary.inflowExemptions, 107736);
assert.equal(artifact.exactMigrationSummary.outflowExemptions, 105694);
assert.equal(artifact.exactMigrationSummary.netExemptions, 2042);
assert.equal(artifact.exactMigrationSummary.inflowAgiThousands, 4310384);
assert.equal(artifact.exactMigrationSummary.outflowAgiThousands, 4371460);
assert.equal(artifact.exactMigrationSummary.netAgiThousands, -61076);
assert.deepEqual(artifact.coverage.observedDomains, ["migration"]);
assert.equal(artifact.coverage.certifiedDomains.length, 0);
assert.deepEqual(artifact.coverage.missingOrUncertifiedDomains, ["demographic", "housing", "labor", "migration", "supply"]);
assert.equal(artifact.observationCandidates.length, 6);
assert(artifact.featureDefinitions.every((item) => item.status === "draft" && item.localization === "source-geography-only"));
assert.equal(artifact.audit.status, "rejected");
assert.equal(artifact.audit.counts.invalidRows, 0);
assert.equal(artifact.audit.counts.duplicateRows, 0);
for (const field of ["rawContentPersisted", "pointInTimeVectorBuilt", "parcelDemandScoresBuilt", "activationAuthorized"]) assert.equal(artifact[field], false);
console.log("White Rabbit Tarrant IRS migration counts are exact, typed, county-level, and activation-blocked.");
