const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const artifact = JSON.parse(fs.readFileSync(path.join(root, "output/tarrant/boundary-readiness/tarrant-boundary-readiness.json"), "utf8"));
assert.equal(artifact.cityProbe.featureCount, 98);
assert.equal(artifact.cityProbe.distinctNameCount, 45);
assert.equal(artifact.cityProbe.missingExpectedNames.length, 0, "All 41 incorporated-area names must occur in the boundary service");
assert.deepEqual(artifact.cityProbe.additionalObservedNames, ["FT WORTH LIMITED PURPOSE", "ROANOKE", "UNINCORPORATED", "UNINCORPORATED DENTON"]);
assert.equal(artifact.etjProbe.featureCount, 107);
assert.equal(artifact.etjProbe.distinctNameCount, 14);
assert.deepEqual(artifact.reconciliation.missingFromService, ["CROWLEY ETJ"]);
assert.equal(artifact.reconciliation.serviceOnly.length, 9);
assert.equal(artifact.reconciliation.status, "inconsistent-needs-review");
assert.equal(artifact.snapshotPolicy.status, "blocked");
assert.equal(artifact.cityProbe.capturesGeometry, false);
assert.equal(artifact.etjProbe.capturesGeometry, false);
assert.equal(artifact.activationAuthorized, false);
console.log("White Rabbit Tarrant boundary counts and ETJ discrepancy remain metadata-only, exact, and activation-blocked.");
