import { createHash } from "node:crypto";

export const OPERATING_EVIDENCE_SOURCE_VERSION = "wr-operating-evidence-source-v1";
export const ASSET_RECORD_VERSION = "wr-asset-record-v1";
export const LEASE_RECORD_VERSION = "wr-lease-record-v1";
export const LEASE_AMENDMENT_VERSION = "wr-lease-amendment-v1";
export const OPERATING_STATEMENT_VERSION = "wr-operating-statement-v1";
export const ASSET_BUDGET_VERSION = "wr-asset-budget-v1";
export const DEBT_COVENANT_VERSION = "wr-debt-covenant-v1";
export const ASSET_PLAN_VERSION = "wr-asset-plan-v1";
export const ASSET_OPERATIONS_STATE_VERSION = "wr-asset-operations-state-v1";

function required(value, name) { const normalized = String(value || "").trim(); if (!normalized) throw new TypeError(`${name} is required`); return normalized; }
function iso(value, name) { const date = new Date(value); if (!Number.isFinite(date.getTime())) throw new TypeError(`${name} must be a valid date`); return date.toISOString(); }
function dateOnly(value, name) { const normalized = String(value || ""); if (!/^\d{4}-\d{2}-\d{2}$/.test(normalized) || new Date(`${normalized}T00:00:00.000Z`).toISOString().slice(0, 10) !== normalized) throw new TypeError(`${name} must be YYYY-MM-DD`); return normalized; }
function canonicalJson(value) { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`; return JSON.stringify(value ?? null); }
export function assetOperationsSha256(value) { return createHash("sha256").update(typeof value === "string" || Buffer.isBuffer(value) ? value : canonicalJson(value)).digest("hex"); }
function stableId(prefix, seed) { return `${prefix}_${assetOperationsSha256(seed).slice(0, 24)}`; }
function digest(value, name) { const normalized = required(value, name); if (!/^[a-f0-9]{64}$/.test(normalized)) throw new TypeError(`${name} must be a SHA-256 digest`); return normalized; }
function error(code, message) { const value = new Error(message); value.code = code; return value; }
function tenantError(message) { return error("WR_TENANT_ISOLATION_VIOLATION", message); }
function seal(input, body, field, code, label) { const value = assetOperationsSha256(body); if (input[field] && input[field] !== value) throw error(code, `${label} digest verification failed`); return Object.freeze({ ...body, [field]: value }); }
function propertyId(value) { const normalized = required(value, "whiteRabbitPropertyId"); if (!/^wrp:v1:[^:]+:.+$/.test(normalized)) throw new TypeError("whiteRabbitPropertyId must use wrp:v1 canonical identity"); return normalized; }
function currency(value) { const normalized = required(value, "currency").toUpperCase(); if (!/^[A-Z]{3}$/.test(normalized)) throw new TypeError("currency must be an ISO 4217 code"); return normalized; }
function observedNumber(value, name, options = {}) { const status = value?.status === "observed" ? "observed" : "unknown"; if (status === "unknown") return Object.freeze({ status, value: null, sourceField: "" }); const number = Number(value.value); if (!Number.isFinite(number) || (options.minimum !== undefined && number < options.minimum)) throw new TypeError(`${name}.value is invalid`); return Object.freeze({ status, value: number, sourceField: required(value.sourceField, `${name}.sourceField`) }); }

export function createOperatingEvidenceSource(input = {}) {
  const observedAt = iso(input.observedAt, "source.observedAt"), availableAt = iso(input.availableAt, "source.availableAt"), expiresAt = input.expiresAt ? iso(input.expiresAt, "source.expiresAt") : "";
  if (new Date(availableAt) < new Date(observedAt)) throw new TypeError("source.availableAt cannot precede source.observedAt"); if (expiresAt && new Date(expiresAt) <= new Date(availableAt)) throw new TypeError("source.expiresAt must follow availability");
  const sourceRef = required(input.sourceRef, "source.sourceRef"); if (!sourceRef.startsWith("source-ref:")) throw new TypeError("sourceRef must be opaque");
  const body = { schemaVersion: OPERATING_EVIDENCE_SOURCE_VERSION, datasetId: required(input.datasetId, "source.datasetId"), recordId: required(input.recordId, "source.recordId"), sourceRef, licenseId: required(input.licenseId, "source.licenseId"), licenseStatus: ["authorized", "restricted", "expired", "unknown"].includes(input.licenseStatus) ? input.licenseStatus : "unknown", observedAt, availableAt, expiresAt, sourceVersion: required(input.sourceVersion, "source.sourceVersion"), fieldMap: Object.fromEntries(Object.entries(input.fieldMap || {}).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => [key, String(value)])), contentSha256: digest(input.contentSha256, "source.contentSha256") };
  return seal(input, body, "sourceSha256", "WR_OPERATING_SOURCE_INTEGRITY_FAILURE", "Operating evidence source");
}

function portfolioMembership(input = {}) { const effectiveFrom = dateOnly(input.effectiveFrom, "portfolioMembership.effectiveFrom"), effectiveTo = input.effectiveTo ? dateOnly(input.effectiveTo, "portfolioMembership.effectiveTo") : ""; if (effectiveTo && effectiveTo < effectiveFrom) throw new TypeError("Portfolio membership end cannot precede start"); return Object.freeze({ portfolioId: required(input.portfolioId, "portfolioMembership.portfolioId"), effectiveFrom, effectiveTo }); }

export function createAssetRecord(input = {}) {
  const organizationId = required(input.organizationId, "organizationId"), whiteRabbitPropertyId = propertyId(input.whiteRabbitPropertyId), acquiredOn = dateOnly(input.acquiredOn, "acquiredOn");
  const memberships = (input.portfolioMemberships || []).map(portfolioMembership).sort((a, b) => a.portfolioId.localeCompare(b.portfolioId) || a.effectiveFrom.localeCompare(b.effectiveFrom));
  for (let index = 1; index < memberships.length; index += 1) if (memberships[index].portfolioId === memberships[index - 1].portfolioId && (!memberships[index - 1].effectiveTo || memberships[index].effectiveFrom <= memberships[index - 1].effectiveTo)) throw new TypeError("Portfolio membership periods cannot overlap");
  const body = { schemaVersion: ASSET_RECORD_VERSION, id: String(input.id || stableId("asset", `${organizationId}|${whiteRabbitPropertyId}|${acquiredOn}`)), organizationId, whiteRabbitPropertyId, name: required(input.name, "name"), propertyType: required(input.propertyType, "propertyType").toLowerCase(), currency: currency(input.currency), acquiredOn, disposedOn: input.disposedOn ? dateOnly(input.disposedOn, "disposedOn") : "", rentableAreaSqFt: observedNumber(input.rentableAreaSqFt, "rentableAreaSqFt", { minimum: 0 }), unitCount: observedNumber(input.unitCount, "unitCount", { minimum: 0 }), portfolioMemberships: memberships, source: createOperatingEvidenceSource(input.source) };
  if (body.disposedOn && body.disposedOn < acquiredOn) throw new TypeError("disposedOn cannot precede acquiredOn");
  return seal(input, body, "assetSha256", "WR_ASSET_RECORD_INTEGRITY_FAILURE", "Asset record");
}

function rentSchedulePeriod(input = {}, index = 0) { const effectiveFrom = dateOnly(input.effectiveFrom, `baseRentSchedule[${index}].effectiveFrom`), effectiveTo = dateOnly(input.effectiveTo, `baseRentSchedule[${index}].effectiveTo`); if (effectiveTo < effectiveFrom) throw new TypeError("Rent schedule period end cannot precede start"); return Object.freeze({ effectiveFrom, effectiveTo, monthlyAmount: observedNumber(input.monthlyAmount, `baseRentSchedule[${index}].monthlyAmount`, { minimum: 0 }) }); }
function normalizeRentSchedule(input = []) { const periods = input.map(rentSchedulePeriod).sort((a, b) => a.effectiveFrom.localeCompare(b.effectiveFrom)); for (let index = 1; index < periods.length; index += 1) if (periods[index].effectiveFrom <= periods[index - 1].effectiveTo) throw error("WR_LEASE_RENT_SCHEDULE_OVERLAP", "Base-rent schedule periods cannot overlap"); return Object.freeze(periods); }

export function createLeaseRecord(input = {}) {
  const organizationId = required(input.organizationId, "organizationId"), commencementDate = dateOnly(input.commencementDate, "commencementDate"), expirationDate = dateOnly(input.expirationDate, "expirationDate"); if (expirationDate < commencementDate) throw new TypeError("Lease expiration cannot precede commencement");
  const body = { schemaVersion: LEASE_RECORD_VERSION, id: String(input.id || stableId("lease", `${organizationId}|${input.assetId}|${input.leaseId}|${commencementDate}`)), organizationId, assetId: required(input.assetId, "assetId"), whiteRabbitPropertyId: propertyId(input.whiteRabbitPropertyId), leaseId: required(input.leaseId, "leaseId"), tenantEntityId: required(input.tenantEntityId, "tenantEntityId"), tenantDisplayName: required(input.tenantDisplayName, "tenantDisplayName"), unitIds: [...new Set((input.unitIds || []).map(String).filter(Boolean))].sort(), executedAt: iso(input.executedAt, "executedAt"), commencementDate, expirationDate, areaSqFt: observedNumber(input.areaSqFt, "areaSqFt", { minimum: 0 }), currency: currency(input.currency), baseRentSchedule: normalizeRentSchedule(input.baseRentSchedule || []), recoveryStructure: ["gross", "modified-gross", "net", "triple-net", "unknown"].includes(input.recoveryStructure) ? input.recoveryStructure : "unknown", status: ["executed", "terminated", "expired"].includes(input.status) ? input.status : "executed", source: createOperatingEvidenceSource(input.source) };
  if (!body.unitIds.length) throw new TypeError("Lease must reference at least one unit");
  return seal(input, body, "leaseSha256", "WR_LEASE_RECORD_INTEGRITY_FAILURE", "Lease record");
}

export function createLeaseAmendment(input = {}) {
  const changes = { expirationDate: input.changes?.expirationDate ? dateOnly(input.changes.expirationDate, "changes.expirationDate") : "", areaSqFt: input.changes?.areaSqFt ? observedNumber(input.changes.areaSqFt, "changes.areaSqFt", { minimum: 0 }) : null, unitIds: input.changes?.unitIds ? [...new Set(input.changes.unitIds.map(String).filter(Boolean))].sort() : null, baseRentSchedule: input.changes?.baseRentSchedule ? normalizeRentSchedule(input.changes.baseRentSchedule) : null, recoveryStructure: input.changes?.recoveryStructure ? required(input.changes.recoveryStructure, "changes.recoveryStructure") : "", status: input.changes?.status ? required(input.changes.status, "changes.status") : "" };
  if (!Object.values(changes).some((value) => value && (!Array.isArray(value) || value.length))) throw new TypeError("Lease amendment must change at least one supported term");
  if (changes.recoveryStructure && !["gross", "modified-gross", "net", "triple-net", "unknown"].includes(changes.recoveryStructure)) throw new TypeError("Unsupported amended recoveryStructure");
  if (changes.status && !["executed", "terminated", "expired"].includes(changes.status)) throw new TypeError("Unsupported amended lease status");
  if (changes.unitIds && !changes.unitIds.length) throw new TypeError("Amended unitIds cannot be empty");
  const body = { schemaVersion: LEASE_AMENDMENT_VERSION, id: String(input.id || stableId("lease_amendment", `${input.organizationId}|${input.leaseId}|${input.sequence}|${input.effectiveDate}`)), organizationId: required(input.organizationId, "organizationId"), assetId: required(input.assetId, "assetId"), leaseId: required(input.leaseId, "leaseId"), sequence: Math.max(1, Math.trunc(Number(input.sequence) || 1)), effectiveDate: dateOnly(input.effectiveDate, "effectiveDate"), executedAt: iso(input.executedAt, "executedAt"), previousTermsSha256: digest(input.previousTermsSha256, "previousTermsSha256"), changes, source: createOperatingEvidenceSource(input.source) };
  return seal(input, body, "amendmentSha256", "WR_LEASE_AMENDMENT_INTEGRITY_FAILURE", "Lease amendment");
}

function financialEntry(input = {}, index = 0) { const status = input.status === "observed" ? "observed" : "unknown"; const amount = status === "observed" ? Number(input.amount) : null; if (status === "observed" && !Number.isFinite(amount)) throw new TypeError(`entries[${index}].amount must be finite`); return Object.freeze({ accountCode: required(input.accountCode, `entries[${index}].accountCode`), accountName: required(input.accountName, `entries[${index}].accountName`), category: ["revenue", "operating-expense", "debt-service", "capital-expenditure", "other"].includes(input.category) ? input.category : "other", status, amount, sourceField: status === "observed" ? required(input.sourceField, `entries[${index}].sourceField`) : "" }); }
function normalizeEntries(input = []) { const entries = input.map(financialEntry).sort((a, b) => a.accountCode.localeCompare(b.accountCode)); if (new Set(entries.map((item) => item.accountCode)).size !== entries.length) throw new TypeError("Financial account codes must be unique within a period"); return Object.freeze(entries); }
function financialRecord(input, schemaVersion, kind) { const periodStart = dateOnly(input.periodStart, "periodStart"), periodEnd = dateOnly(input.periodEnd, "periodEnd"); if (periodEnd < periodStart) throw new TypeError("Financial period end cannot precede start"); const entries = normalizeEntries(input.entries || []), expectedAccountCodes = [...new Set((input.expectedAccountCodes || []).map(String).filter(Boolean))].sort(); if (!expectedAccountCodes.length) throw new TypeError("Financial records require explicit expectedAccountCodes"); const missingAccountCodes = expectedAccountCodes.filter((code) => !entries.some((entry) => entry.accountCode === code && entry.status === "observed")); const body = { schemaVersion, id: String(input.id || stableId(kind, `${input.organizationId}|${input.assetId}|${periodStart}|${periodEnd}|${input.basis}`)), organizationId: required(input.organizationId, "organizationId"), assetId: required(input.assetId, "assetId"), whiteRabbitPropertyId: propertyId(input.whiteRabbitPropertyId), periodStart, periodEnd, basis: input.basis === "cash" ? "cash" : "accrual", currency: currency(input.currency), entries, expectedAccountCodes, completeness: { status: missingAccountCodes.length ? "partial" : "complete", missingAccountCodes }, source: createOperatingEvidenceSource(input.source) }; return body; }

export function createOperatingStatement(input = {}) { return seal(input, financialRecord(input, OPERATING_STATEMENT_VERSION, "operating_statement"), "statementSha256", "WR_OPERATING_STATEMENT_INTEGRITY_FAILURE", "Operating statement"); }
export function createAssetBudget(input = {}) { return seal(input, financialRecord(input, ASSET_BUDGET_VERSION, "asset_budget"), "budgetSha256", "WR_ASSET_BUDGET_INTEGRITY_FAILURE", "Asset budget"); }

export function createDebtCovenant(input = {}) {
  const metric = ["dscr", "debt-yield", "ltv", "occupancy"].includes(input.metric) ? input.metric : "dscr", comparator = input.comparator === "<=" ? "<=" : ">=", threshold = Number(input.threshold); if (!Number.isFinite(threshold)) throw new TypeError("Covenant threshold must be finite");
  const body = { schemaVersion: DEBT_COVENANT_VERSION, id: String(input.id || stableId("covenant", `${input.organizationId}|${input.assetId}|${metric}|${input.effectiveFrom}`)), organizationId: required(input.organizationId, "organizationId"), assetId: required(input.assetId, "assetId"), lenderId: required(input.lenderId, "lenderId"), metric, comparator, threshold, effectiveFrom: dateOnly(input.effectiveFrom, "effectiveFrom"), effectiveTo: input.effectiveTo ? dateOnly(input.effectiveTo, "effectiveTo") : "", testingFrequency: ["monthly", "quarterly", "annual"].includes(input.testingFrequency) ? input.testingFrequency : "quarterly", curePeriodDays: Math.max(0, Math.trunc(Number(input.curePeriodDays) || 0)), source: createOperatingEvidenceSource(input.source) };
  if (body.effectiveTo && body.effectiveTo < body.effectiveFrom) throw new TypeError("Covenant effective end cannot precede start");
  return seal(input, body, "covenantSha256", "WR_DEBT_COVENANT_INTEGRITY_FAILURE", "Debt covenant");
}

export function createAssetPlan(input = {}) {
  const createdAt = iso(input.createdAt, "createdAt"), actions = (input.actions || []).map((action, index) => Object.freeze({ id: String(action.id || `action-${index + 1}`), title: required(action.title, `actions[${index}].title`), ownerUserId: required(action.ownerUserId, `actions[${index}].ownerUserId`), targetDate: dateOnly(action.targetDate, `actions[${index}].targetDate`), targetMetric: required(action.targetMetric, `actions[${index}].targetMetric`), targetValue: Number.isFinite(Number(action.targetValue)) ? Number(action.targetValue) : null, evidenceRequirement: required(action.evidenceRequirement, `actions[${index}].evidenceRequirement`), status: ["planned", "in-progress", "completed", "cancelled"].includes(action.status) ? action.status : "planned" }));
  if (new Set(actions.map((action) => action.id)).size !== actions.length) throw new TypeError("Asset-plan action IDs must be unique");
  const body = { schemaVersion: ASSET_PLAN_VERSION, id: String(input.id || stableId("asset_plan", `${input.organizationId}|${input.assetId}|${input.planYear}|${createdAt}`)), organizationId: required(input.organizationId, "organizationId"), assetId: required(input.assetId, "assetId"), planYear: Math.trunc(Number(input.planYear)), strategy: required(input.strategy, "strategy"), actions, status: ["draft", "approved", "superseded"].includes(input.status) ? input.status : "draft", approvedByUserId: String(input.approvedByUserId || ""), approvedAt: input.approvedAt ? iso(input.approvedAt, "approvedAt") : "", createdByUserId: required(input.createdByUserId, "createdByUserId"), createdAt };
  if (!Number.isInteger(body.planYear) || body.planYear < 2000 || body.planYear > 2200) throw new TypeError("planYear is invalid"); if (body.status === "approved" && (!body.approvedByUserId || !body.approvedAt || body.approvedByUserId === body.createdByUserId)) throw error("WR_ASSET_PLAN_APPROVAL_SEPARATION_REQUIRED", "Approved asset plans require an independent approver");
  return seal(input, body, "planSha256", "WR_ASSET_PLAN_INTEGRITY_FAILURE", "Asset plan");
}

export function createAssetOperationsState(input = {}) {
  const organizationId = required(input.organizationId, "organizationId"), assets = (input.assets || []).map(createAssetRecord), leases = (input.leases || []).map(createLeaseRecord), amendments = (input.amendments || []).map(createLeaseAmendment), statements = (input.statements || []).map(createOperatingStatement), budgets = (input.budgets || []).map(createAssetBudget), covenants = (input.covenants || []).map(createDebtCovenant), assetPlans = (input.assetPlans || []).map(createAssetPlan);
  for (const record of [...assets, ...leases, ...amendments, ...statements, ...budgets, ...covenants, ...assetPlans]) if (record.organizationId !== organizationId) throw tenantError("Asset operations record belongs to another organization");
  for (const collection of [assets, leases, amendments, statements, budgets, covenants, assetPlans]) if (new Set(collection.map((item) => item.id)).size !== collection.length) throw error("WR_ASSET_OPERATIONS_RECORD_CONFLICT", "Asset operations record IDs must be unique within each collection");
  if (new Set(leases.map((item) => `${item.assetId}|${item.leaseId}`)).size !== leases.length) throw error("WR_LEASE_IDENTITY_CONFLICT", "Lease IDs must be unique within an asset");
  for (const lease of leases) { const asset = assets.find((item) => item.id === lease.assetId); if (!asset || asset.whiteRabbitPropertyId !== lease.whiteRabbitPropertyId || asset.currency !== lease.currency) throw error("WR_ASSET_LEASE_SCOPE_MISMATCH", "Lease does not match its asset identity and currency"); }
  for (const amendment of amendments) { const lease = leases.find((item) => item.leaseId === amendment.leaseId && item.assetId === amendment.assetId); if (!lease) throw new TypeError(`Amendment references unknown lease: ${amendment.leaseId}`); }
  validateAmendmentChains(leases, amendments);
  for (const record of [...statements, ...budgets, ...covenants, ...assetPlans]) { const asset = assets.find((item) => item.id === record.assetId); if (!asset || (record.whiteRabbitPropertyId && record.whiteRabbitPropertyId !== asset.whiteRabbitPropertyId) || (record.currency && record.currency !== asset.currency)) throw error("WR_ASSET_RECORD_SCOPE_MISMATCH", "Operating record does not match its asset identity or currency"); }
  return { schemaVersion: ASSET_OPERATIONS_STATE_VERSION, organizationId, revision: Math.max(1, Math.trunc(Number(input.revision) || 1)), assets, leases, amendments, statements, budgets, covenants, assetPlans, updatedAt: iso(input.updatedAt, "updatedAt") };
}

function amendmentTermsDigest(lease, amendments) { return assetOperationsSha256({ leaseSha256: lease.leaseSha256, amendments: amendments.map((item) => item.amendmentSha256) }); }
function validateAmendmentChains(leases, amendments) { for (const lease of leases) { const chain = amendments.filter((item) => item.leaseId === lease.leaseId && item.assetId === lease.assetId).sort((a, b) => a.sequence - b.sequence); let previousDigest = amendmentTermsDigest(lease, []), expirationDate = lease.expirationDate; for (let index = 0; index < chain.length; index += 1) { const amendment = chain[index]; if (amendment.sequence !== index + 1 || amendment.previousTermsSha256 !== previousDigest) throw error("WR_LEASE_AMENDMENT_CHAIN_INVALID", `Lease amendment chain is invalid for ${lease.leaseId}`); if (index > 0 && (amendment.effectiveDate < chain[index - 1].effectiveDate || amendment.source.availableAt < chain[index - 1].source.availableAt)) throw error("WR_LEASE_AMENDMENT_CHAIN_INVALID", "Lease amendment effective and availability times must be monotonic"); expirationDate = amendment.changes.expirationDate || expirationDate; if (expirationDate < lease.commencementDate) throw error("WR_LEASE_AMENDMENT_CHAIN_INVALID", "Amended expiration cannot precede lease commencement"); previousDigest = amendmentTermsDigest(lease, chain.slice(0, index + 1)); } } }
export function expectedLeaseAmendmentPreviousTermsSha256(leaseInput, amendmentsInput = []) { const lease = createLeaseRecord(leaseInput), amendments = amendmentsInput.map(createLeaseAmendment).sort((a, b) => a.sequence - b.sequence); return amendmentTermsDigest(lease, amendments); }

function assertMutation(state, context, grant) { if (context.organizationId !== state.organizationId) throw tenantError("Asset operations mutation tenant mismatch"); if (!(context.grants || []).includes(grant)) throw error("WR_ASSET_OPERATIONS_PERMISSION_DENIED", `${grant} grant is required`); if (Number(context.expectedRevision) !== state.revision) throw error("WR_REVISION_CONFLICT", `Asset operations state revision conflict: expected ${context.expectedRevision}, found ${state.revision}`); const occurredAt = iso(context.occurredAt, "context.occurredAt"); if (new Date(occurredAt) < new Date(state.updatedAt)) throw error("WR_ASSET_OPERATIONS_TIME_REGRESSION", "Asset operations state cannot move backward in time"); return occurredAt; }
function mutate(stateInput, collection, record, context) { const state = createAssetOperationsState(stateInput), occurredAt = assertMutation(state, context, "asset-operations:write"); if (record.organizationId !== state.organizationId) throw tenantError("Asset operations record belongs to another organization"); if (state[collection].some((item) => item.id === record.id)) throw error("WR_ASSET_OPERATIONS_RECORD_CONFLICT", `Record already exists: ${record.id}`); return createAssetOperationsState({ ...state, revision: state.revision + 1, [collection]: [...state[collection], record], updatedAt: occurredAt }); }
export function addAssetRecord(state, input, context = {}) { return mutate(state, "assets", createAssetRecord(input), context); }
export function addLeaseRecord(state, input, context = {}) { return mutate(state, "leases", createLeaseRecord(input), context); }
export function addLeaseAmendment(state, input, context = {}) { return mutate(state, "amendments", createLeaseAmendment(input), context); }
export function addOperatingStatement(state, input, context = {}) { return mutate(state, "statements", createOperatingStatement(input), context); }
export function addAssetBudget(state, input, context = {}) { return mutate(state, "budgets", createAssetBudget(input), context); }
export function addDebtCovenant(state, input, context = {}) { return mutate(state, "covenants", createDebtCovenant(input), context); }
export function addAssetPlan(state, input, context = {}) { return mutate(state, "assetPlans", createAssetPlan(input), context); }
