export const OPERATING_EVIDENCE_SOURCE_VERSION: "wr-operating-evidence-source-v1";
export const ASSET_RECORD_VERSION: "wr-asset-record-v1";
export const LEASE_RECORD_VERSION: "wr-lease-record-v1";
export const LEASE_AMENDMENT_VERSION: "wr-lease-amendment-v1";
export const OPERATING_STATEMENT_VERSION: "wr-operating-statement-v1";
export const ASSET_BUDGET_VERSION: "wr-asset-budget-v1";
export const DEBT_COVENANT_VERSION: "wr-debt-covenant-v1";
export const ASSET_PLAN_VERSION: "wr-asset-plan-v1";
export const ASSET_OPERATIONS_STATE_VERSION: "wr-asset-operations-state-v1";
export function assetOperationsSha256(value: unknown): string;
export function createOperatingEvidenceSource(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createAssetRecord(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createLeaseRecord(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createLeaseAmendment(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createOperatingStatement(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createAssetBudget(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createDebtCovenant(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createAssetPlan(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createAssetOperationsState(input?: Record<string, any>): Record<string, any>;
export function expectedLeaseAmendmentPreviousTermsSha256(lease: Record<string, any>, amendments?: Array<Record<string, any>>): string;
export function addAssetRecord(state: Record<string, any>, input: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function addLeaseRecord(state: Record<string, any>, input: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function addLeaseAmendment(state: Record<string, any>, input: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function addOperatingStatement(state: Record<string, any>, input: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function addAssetBudget(state: Record<string, any>, input: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function addDebtCovenant(state: Record<string, any>, input: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function addAssetPlan(state: Record<string, any>, input: Record<string, any>, context?: Record<string, any>): Record<string, any>;
