import { createHash } from "node:crypto";
import { createAssetOperationsState, createOperatingEvidenceSource, createOperatingStatement } from "./assetOperations.mjs";
import { materializeLeaseAsOf, deriveOperatingMetrics } from "./portfolioIntelligence.mjs";

export const FORECAST_ASSUMPTION_VERSION = "wr-forecast-assumption-v1";
export const LEASE_ROLLOVER_REPORT_VERSION = "wr-lease-rollover-report-v1";
export const CAPITAL_PROJECT_VERSION = "wr-capital-project-v1";
export const CASH_FLOW_FORECAST_VERSION = "wr-cash-flow-forecast-v1";
export const STRESS_SCENARIO_VERSION = "wr-portfolio-stress-scenario-v1";
export const STRESS_REPORT_VERSION = "wr-portfolio-stress-report-v1";
export const FORWARD_STRATEGY_STATE_VERSION = "wr-forward-strategy-state-v1";

function required(value, name) { const normalized = String(value || "").trim(); if (!normalized) throw new TypeError(`${name} is required`); return normalized; }
function iso(value, name) { const date = new Date(value); if (!Number.isFinite(date.getTime())) throw new TypeError(`${name} must be a valid date`); return date.toISOString(); }
function dateOnly(value, name) { const normalized = String(value || ""); if (!/^\d{4}-\d{2}-\d{2}$/.test(normalized) || new Date(`${normalized}T00:00:00.000Z`).toISOString().slice(0, 10) !== normalized) throw new TypeError(`${name} must be YYYY-MM-DD`); return normalized; }
function canonicalJson(value) { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`; return JSON.stringify(value ?? null); }
export function forwardStrategySha256(value) { return createHash("sha256").update(typeof value === "string" || Buffer.isBuffer(value) ? value : canonicalJson(value)).digest("hex"); }
function stableId(prefix, seed) { return `${prefix}_${forwardStrategySha256(seed).slice(0, 24)}`; }
function seal(input, body, field, code) { const digest = forwardStrategySha256(body); if (input?.[field] && input[field] !== digest) { const error = new Error(`${field} verification failed`); error.code = code; throw error; } return Object.freeze({ ...body, [field]: digest }); }
function error(code, message) { const value = new Error(message); value.code = code; return value; }
function round(value, digits = 6) { return Number(Number(value).toFixed(digits)); }
function sourceEligibility(source, evaluatedAt) { const at = new Date(evaluatedAt).getTime(), reasons = []; if (source.licenseStatus !== "authorized") reasons.push(`license-${source.licenseStatus}`); if (new Date(source.observedAt).getTime() > at || new Date(source.availableAt).getTime() > at) reasons.push("future-evidence"); if (source.expiresAt && new Date(source.expiresAt).getTime() <= at) reasons.push("evidence-expired"); return { eligible: !reasons.length, reasons }; }
function monthStart(value) { return `${value.slice(0, 7)}-01`; }
function addMonths(value, count) { const date = new Date(`${monthStart(value)}T00:00:00.000Z`); date.setUTCMonth(date.getUTCMonth() + count); return date.toISOString().slice(0, 10); }
function daysInPeriod(start, end) { return Math.round((new Date(`${end}T00:00:00.000Z`) - new Date(`${start}T00:00:00.000Z`)) / 86400000) + 1; }

const ASSUMPTION_METRICS = Object.freeze(["renewal-probability-pct", "downtime-months", "market-rent-monthly", "rent-growth-pct", "expense-growth-pct", "capital-cost-multiplier-pct"]);
export function createForecastAssumption(input = {}) {
  const status = ["observed", "assumed", "scenario-derived", "unknown"].includes(input.status) ? input.status : "unknown", value = status === "unknown" ? null : Number(input.value);
  if (status !== "unknown" && !Number.isFinite(value)) throw new TypeError("Forecast assumption value must be finite");
  const metric = required(input.metric, "metric"); if (!ASSUMPTION_METRICS.includes(metric)) throw new TypeError(`Unsupported forecast assumption metric: ${metric}`);
  if (metric === "renewal-probability-pct" && status !== "unknown" && (value < 0 || value > 100)) throw new TypeError("Renewal probability must be between 0 and 100");
  if (["downtime-months", "market-rent-monthly", "capital-cost-multiplier-pct"].includes(metric) && status !== "unknown" && value < 0) throw new TypeError(`${metric} cannot be negative`);
  const body = { schemaVersion: FORECAST_ASSUMPTION_VERSION, id: String(input.id || stableId("forecast_assumption", `${input.organizationId}|${input.assetId}|${input.leaseId || "asset"}|${metric}|${input.effectiveFrom}`)), organizationId: required(input.organizationId, "organizationId"), assetId: required(input.assetId, "assetId"), leaseId: String(input.leaseId || ""), metric, status, value, unit: required(input.unit, "unit"), effectiveFrom: dateOnly(input.effectiveFrom, "effectiveFrom"), effectiveTo: input.effectiveTo ? dateOnly(input.effectiveTo, "effectiveTo") : "", rationale: status === "assumed" ? required(input.rationale, "rationale") : String(input.rationale || ""), approvedByUserId: status === "assumed" ? required(input.approvedByUserId, "approvedByUserId") : String(input.approvedByUserId || ""), createdByUserId: required(input.createdByUserId, "createdByUserId"), createdAt: iso(input.createdAt, "createdAt"), source: createOperatingEvidenceSource(input.source) };
  if (body.effectiveTo && body.effectiveTo < body.effectiveFrom) throw new TypeError("Assumption effective end cannot precede start");
  if (status === "assumed" && body.approvedByUserId === body.createdByUserId) throw error("WR_FORECAST_ASSUMPTION_APPROVAL_SEPARATION_REQUIRED", "Assumed forecast values require an independent approver");
  return seal(input, body, "assumptionSha256", "WR_FORECAST_ASSUMPTION_INTEGRITY_FAILURE");
}

function capitalScheduleLine(input = {}, index = 0) { const status = ["observed", "assumed", "unknown"].includes(input.status) ? input.status : "unknown", amount = status === "unknown" ? null : Number(input.amount); if (status !== "unknown" && (!Number.isFinite(amount) || amount < 0)) throw new TypeError(`schedule[${index}].amount is invalid`); return Object.freeze({ id: String(input.id || `line-${index + 1}`), date: dateOnly(input.date, `schedule[${index}].date`), status, amount, sourceField: status === "unknown" ? "" : required(input.sourceField, `schedule[${index}].sourceField`) }); }
export function createCapitalProject(input = {}) {
  const startDate = dateOnly(input.startDate, "startDate"), endDate = dateOnly(input.endDate, "endDate"), schedule = (input.schedule || []).map(capitalScheduleLine).sort((a, b) => a.date.localeCompare(b.date));
  if (endDate < startDate || schedule.some((line) => line.date < startDate || line.date > endDate)) throw new TypeError("Capital schedule must fall within the project period");
  if (!schedule.length || new Set(schedule.map((line) => line.id)).size !== schedule.length) throw new TypeError("Capital projects require uniquely identified schedule lines");
  const status = ["planned", "approved", "in-progress", "completed", "cancelled"].includes(input.status) ? input.status : "planned";
  const body = { schemaVersion: CAPITAL_PROJECT_VERSION, id: String(input.id || stableId("capital_project", `${input.organizationId}|${input.assetId}|${input.name}|${startDate}`)), organizationId: required(input.organizationId, "organizationId"), assetId: required(input.assetId, "assetId"), name: required(input.name, "name"), category: required(input.category, "category"), startDate, endDate, dependencyProjectIds: [...new Set((input.dependencyProjectIds || []).map(String).filter(Boolean))].sort(), schedule, contingencyPct: Number.isFinite(Number(input.contingencyPct)) && Number(input.contingencyPct) >= 0 ? Number(input.contingencyPct) : 0, status, createdByUserId: required(input.createdByUserId, "createdByUserId"), approvedByUserId: String(input.approvedByUserId || ""), approvedAt: input.approvedAt ? iso(input.approvedAt, "approvedAt") : "", source: createOperatingEvidenceSource(input.source) };
  if (["approved", "in-progress", "completed"].includes(status) && (!body.approvedByUserId || !body.approvedAt || body.approvedByUserId === body.createdByUserId)) throw error("WR_CAPITAL_PROJECT_APPROVAL_SEPARATION_REQUIRED", "Approved capital projects require an independent approver");
  return seal(input, body, "projectSha256", "WR_CAPITAL_PROJECT_INTEGRITY_FAILURE");
}

export function createStressScenario(input = {}) {
  const shocks = (input.shocks || []).map((shock, index) => { const metric = ASSUMPTION_METRICS.includes(shock.metric) ? shock.metric : required(shock.metric, `shocks[${index}].metric`), operation = shock.operation === "multiply" ? "multiply" : "add", value = Number(shock.value); if (!Number.isFinite(value)) throw new TypeError(`shocks[${index}].value must be finite`); return Object.freeze({ metric, leaseId: String(shock.leaseId || ""), operation, value, rationale: required(shock.rationale, `shocks[${index}].rationale`) }); });
  if (!shocks.length) throw new TypeError("Stress scenarios require at least one shock");
  const body = { schemaVersion: STRESS_SCENARIO_VERSION, id: String(input.id || stableId("stress_scenario", `${input.organizationId}|${input.assetId}|${input.name}|${input.createdAt}`)), organizationId: required(input.organizationId, "organizationId"), assetId: required(input.assetId, "assetId"), name: required(input.name, "name"), description: required(input.description, "description"), shocks, probabilityAssigned: false, createdByUserId: required(input.createdByUserId, "createdByUserId"), createdAt: iso(input.createdAt, "createdAt") };
  return seal(input, body, "scenarioSha256", "WR_STRESS_SCENARIO_INTEGRITY_FAILURE");
}

function validateProjectDependencies(projects) { const byId = new Map(projects.map((item) => [item.id, item])); for (const project of projects) for (const id of project.dependencyProjectIds) if (!byId.has(id) || id === project.id) throw error("WR_CAPITAL_PROJECT_DEPENDENCY_INVALID", `Invalid capital-project dependency: ${id}`); const visiting = new Set(), visited = new Set(); function visit(id) { if (visiting.has(id)) throw error("WR_CAPITAL_PROJECT_DEPENDENCY_CYCLE", "Capital-project dependencies must be acyclic"); if (visited.has(id)) return; visiting.add(id); for (const dependency of byId.get(id).dependencyProjectIds) visit(dependency); visiting.delete(id); visited.add(id); } for (const id of byId.keys()) visit(id); }
export function createForwardStrategyState(input = {}) {
  const organizationId = required(input.organizationId, "organizationId"), assumptions = (input.assumptions || []).map(createForecastAssumption), capitalProjects = (input.capitalProjects || []).map(createCapitalProject), stressScenarios = (input.stressScenarios || []).map(createStressScenario);
  for (const record of [...assumptions, ...capitalProjects, ...stressScenarios]) if (record.organizationId !== organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Forward-strategy record belongs to another organization");
  for (const collection of [assumptions, capitalProjects, stressScenarios]) if (new Set(collection.map((item) => item.id)).size !== collection.length) throw error("WR_FORWARD_STRATEGY_RECORD_CONFLICT", "Forward-strategy record IDs must be unique");
  if (new Set(assumptions.map((item) => `${item.assetId}|${item.leaseId}|${item.metric}|${item.effectiveFrom}`)).size !== assumptions.length) throw error("WR_FORECAST_ASSUMPTION_CONFLICT", "Forecast assumptions conflict at the same effective date");
  validateProjectDependencies(capitalProjects);
  return { schemaVersion: FORWARD_STRATEGY_STATE_VERSION, organizationId, revision: Math.max(1, Math.trunc(Number(input.revision) || 1)), assumptions, capitalProjects, stressScenarios, updatedAt: iso(input.updatedAt, "updatedAt") };
}

function activeAssumption(strategy, assetId, leaseId, metric, date, evaluatedAt) { const candidates = strategy.assumptions.filter((item) => item.assetId === assetId && item.metric === metric && (item.leaseId === leaseId || !item.leaseId) && item.effectiveFrom <= date && (!item.effectiveTo || item.effectiveTo >= date)).sort((a, b) => Number(Boolean(b.leaseId)) - Number(Boolean(a.leaseId)) || b.effectiveFrom.localeCompare(a.effectiveFrom)); const item = candidates[0]; if (!item) return { value: null, reason: `${metric}-missing`, assumptionSha256: "" }; const eligibility = sourceEligibility(item.source, evaluatedAt); return item.status !== "unknown" && eligibility.eligible ? { value: item.value, reason: "", assumptionSha256: item.assumptionSha256 } : { value: null, reason: item.status === "unknown" ? `${metric}-unknown` : eligibility.reasons.map((reason) => `${metric}-${reason}`).join(","), assumptionSha256: item.assumptionSha256 }; }

export function buildLeaseRolloverReport(operationsInput, strategyInput, input = {}) {
  const operations = createAssetOperationsState(operationsInput), strategy = createForwardStrategyState(strategyInput), assetId = required(input.assetId, "assetId"), asOf = dateOnly(input.asOf, "asOf"), evaluatedAt = iso(input.evaluatedAt, "evaluatedAt"), horizonMonths = Math.min(240, Math.max(1, Math.trunc(Number(input.horizonMonths) || 60))), horizonEnd = addMonths(asOf, horizonMonths);
  if (operations.organizationId !== strategy.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Operations and strategy tenants do not match");
  if (!operations.assets.some((item) => item.id === assetId)) throw new TypeError(`Unknown asset: ${assetId}`);
  const expirations = operations.leases.filter((item) => item.assetId === assetId).map((lease) => ({ current: materializeLeaseAsOf(operations, lease.id, { asOf, evaluatedAt }), horizon: materializeLeaseAsOf(operations, lease.id, { asOf: horizonEnd, evaluatedAt }) })).filter(({ horizon }) => horizon.terms && horizon.terms.expirationDate >= asOf && horizon.terms.expirationDate <= horizonEnd).map(({ current, horizon }) => { const renewal = activeAssumption(strategy, assetId, horizon.leaseId, "renewal-probability-pct", horizon.terms.expirationDate, evaluatedAt); return { leaseId: horizon.leaseId, tenantEntityId: horizon.tenantEntityId, expirationDate: horizon.terms.expirationDate, year: Number(horizon.terms.expirationDate.slice(0, 4)), areaSqFt: horizon.terms.areaSqFt.status === "observed" ? horizon.terms.areaSqFt.value : null, monthlyBaseRent: current.monthlyBaseRent.status === "observed" ? current.monthlyBaseRent.value : null, renewalProbabilityPct: renewal.value, finding: renewal.reason, evidenceSha256s: [...new Set([...(current.evidenceSha256s || []), ...(horizon.evidenceSha256s || []), renewal.assumptionSha256].filter(Boolean))].sort() }; });
  const years = [...new Set(expirations.map((item) => item.year))].sort().map((year) => { const items = expirations.filter((item) => item.year === year), allArea = items.every((item) => item.areaSqFt !== null), allRent = items.every((item) => item.monthlyBaseRent !== null); return { year, leaseCount: items.length, knownAreaSqFt: round(items.reduce((sum, item) => sum + (item.areaSqFt || 0), 0)), totalAreaSqFt: allArea ? round(items.reduce((sum, item) => sum + item.areaSqFt, 0)) : null, knownMonthlyBaseRent: round(items.reduce((sum, item) => sum + (item.monthlyBaseRent || 0), 0)), totalMonthlyBaseRent: allRent ? round(items.reduce((sum, item) => sum + item.monthlyBaseRent, 0)) : null, unknownRenewalCount: items.filter((item) => item.renewalProbabilityPct === null).length }; });
  const body = { schemaVersion: LEASE_ROLLOVER_REPORT_VERSION, organizationId: operations.organizationId, assetId, asOf, evaluatedAt, horizonMonths, horizonEnd, status: expirations.some((item) => item.areaSqFt === null || item.monthlyBaseRent === null || item.renewalProbabilityPct === null) ? "partial" : "complete", expirations, years, coverage: { expirationCount: expirations.length, knownAreaCount: expirations.filter((item) => item.areaSqFt !== null).length, knownRentCount: expirations.filter((item) => item.monthlyBaseRent !== null).length, knownRenewalCount: expirations.filter((item) => item.renewalProbabilityPct !== null).length } };
  return seal({}, body, "reportSha256", "WR_LEASE_ROLLOVER_REPORT_INTEGRITY_FAILURE");
}

function baselineMonthlyExpenses(statementInput, evaluatedAt) { if (!statementInput) return { value: null, evidenceSha256: "", reason: "baseline-statement-missing" }; const statement = createOperatingStatement(statementInput), metrics = deriveOperatingMetrics(statement, { evaluatedAt }); if (metrics.metrics.operatingExpense === null) return { value: null, evidenceSha256: statement.statementSha256, reason: "baseline-operating-expense-incomplete" }; return { value: metrics.metrics.operatingExpense / Math.max(1, daysInPeriod(statement.periodStart, statement.periodEnd)) * 365.25 / 12, evidenceSha256: statement.statementSha256, reason: "" }; }
function monthlyCapitalCost(projects, date, evaluatedAt, multiplier) { const lines = projects.filter((project) => ["approved", "in-progress"].includes(project.status)).flatMap((project) => project.schedule.filter((line) => monthStart(line.date) === date).map((line) => ({ project, line, eligibility: sourceEligibility(project.source, evaluatedAt) }))); if (!lines.length) return { known: 0, total: 0, evidenceSha256s: [], reasons: [] }; const reasons = lines.flatMap(({ eligibility }) => eligibility.reasons.map((reason) => `capital-project-${reason}`)); const unknown = lines.some(({ line, eligibility }) => line.status === "unknown" || !eligibility.eligible) || multiplier.value === null; const known = lines.filter(({ line, eligibility }) => line.status !== "unknown" && eligibility.eligible).reduce((sum, { project, line }) => sum + line.amount * (1 + project.contingencyPct / 100), 0); return { known: round(known), total: unknown ? null : round(known * multiplier.value / 100), evidenceSha256s: lines.map(({ project }) => project.projectSha256), reasons }; }

export function buildCashFlowForecast(operationsInput, strategyInput, input = {}) {
  const operations = createAssetOperationsState(operationsInput), strategy = createForwardStrategyState(strategyInput), assetId = required(input.assetId, "assetId"), asOf = dateOnly(input.asOf, "asOf"), evaluatedAt = iso(input.evaluatedAt, "evaluatedAt"), horizonMonths = Math.min(120, Math.max(1, Math.trunc(Number(input.horizonMonths) || 60))), asset = operations.assets.find((item) => item.id === assetId);
  if (!asset) throw new TypeError(`Unknown asset: ${assetId}`); if (operations.organizationId !== strategy.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Operations and strategy tenants do not match");
  const baseline = baselineMonthlyExpenses(input.baselineStatement, evaluatedAt), months = [], findings = new Set(), evidence = new Set([baseline.evidenceSha256].filter(Boolean));
  for (let index = 0; index < horizonMonths; index += 1) { const date = addMonths(asOf, index), yearOffset = index / 12, rentGrowth = activeAssumption(strategy, assetId, "", "rent-growth-pct", date, evaluatedAt), expenseGrowth = activeAssumption(strategy, assetId, "", "expense-growth-pct", date, evaluatedAt), capitalMultiplier = activeAssumption(strategy, assetId, "", "capital-cost-multiplier-pct", date, evaluatedAt), leaseLines = [];
    for (const lease of operations.leases.filter((item) => item.assetId === assetId)) { const materialized = materializeLeaseAsOf(operations, lease.id, { asOf: date, evaluatedAt }); if (!materialized.terms) { leaseLines.push({ leaseId: lease.leaseId, status: "unknown", contractedRent: null, expectedRolloverRent: null, totalExpectedRent: null, finding: materialized.reasons.join(",") }); continue; } for (const hash of materialized.evidenceSha256s || []) evidence.add(hash); const expiration = materialized.terms.expirationDate, rent = materialized.monthlyBaseRent.status === "observed" ? materialized.monthlyBaseRent.value : null; if (materialized.status === "active") { leaseLines.push({ leaseId: lease.leaseId, status: rent === null ? "unknown" : "contracted", contractedRent: rent, expectedRolloverRent: 0, totalExpectedRent: rent, finding: rent === null ? "contracted-rent-unknown" : "" }); continue; }
      if (date <= expiration) { leaseLines.push({ leaseId: lease.leaseId, status: "inactive", contractedRent: 0, expectedRolloverRent: 0, totalExpectedRent: 0, finding: "lease-not-active" }); continue; }
      const renewal = activeAssumption(strategy, assetId, lease.leaseId, "renewal-probability-pct", date, evaluatedAt), downtime = activeAssumption(strategy, assetId, lease.leaseId, "downtime-months", date, evaluatedAt), marketRent = activeAssumption(strategy, assetId, lease.leaseId, "market-rent-monthly", date, evaluatedAt); for (const item of [renewal, downtime, marketRent, rentGrowth]) if (item.assumptionSha256) evidence.add(item.assumptionSha256); const missing = [renewal, downtime, marketRent, rentGrowth].filter((item) => item.value === null).map((item) => item.reason); if (missing.length) { missing.forEach((item) => findings.add(item)); leaseLines.push({ leaseId: lease.leaseId, status: "unknown", contractedRent: 0, expectedRolloverRent: null, totalExpectedRent: null, finding: missing.join(",") }); continue; }
      const monthsAfterExpiration = Math.max(0, Math.round((new Date(`${date}T00:00:00.000Z`) - new Date(`${monthStart(expiration)}T00:00:00.000Z`)) / 2629800000)), renewalWeight = renewal.value / 100, newLeaseAvailable = monthsAfterExpiration >= downtime.value ? 1 : 0, grownMarketRent = marketRent.value * (1 + rentGrowth.value / 100) ** yearOffset, expected = grownMarketRent * (renewalWeight + (1 - renewalWeight) * newLeaseAvailable); leaseLines.push({ leaseId: lease.leaseId, status: "assumption-driven", contractedRent: 0, expectedRolloverRent: round(expected), totalExpectedRent: round(expected), finding: "weighted-renewal-and-reletting-assumptions" }); }
    const knownRent = leaseLines.reduce((sum, item) => sum + (item.totalExpectedRent || 0), 0), allRentKnown = leaseLines.every((item) => item.totalExpectedRent !== null), operatingExpenses = baseline.value !== null && expenseGrowth.value !== null ? baseline.value * (1 + expenseGrowth.value / 100) ** yearOffset : null; if (baseline.reason) findings.add(baseline.reason); if (expenseGrowth.reason) findings.add(expenseGrowth.reason); const capex = monthlyCapitalCost(strategy.capitalProjects.filter((item) => item.assetId === assetId), date, evaluatedAt, capitalMultiplier); for (const hash of capex.evidenceSha256s) evidence.add(hash); for (const reason of capex.reasons) findings.add(reason); if (capitalMultiplier.reason) findings.add(capitalMultiplier.reason); const totalRent = allRentKnown ? round(knownRent) : null, cashFlow = totalRent !== null && operatingExpenses !== null && capex.total !== null ? round(totalRent - operatingExpenses - capex.total) : null; months.push({ month: date.slice(0, 7), leaseLines, knownRent: round(knownRent), totalRent, operatingExpenses: operatingExpenses === null ? null : round(operatingExpenses), knownCapitalCost: capex.known, totalCapitalCost: capex.total, cashFlowBeforeDebtService: cashFlow }); }
  const annual = [...new Set(months.map((item) => Number(item.month.slice(0, 4))))].map((year) => { const selected = months.filter((item) => Number(item.month.slice(0, 4)) === year), sumIfKnown = (field) => selected.every((item) => item[field] !== null) ? round(selected.reduce((sum, item) => sum + item[field], 0)) : null; return { year, monthCount: selected.length, knownRent: round(selected.reduce((sum, item) => sum + item.knownRent, 0)), totalRent: sumIfKnown("totalRent"), operatingExpenses: sumIfKnown("operatingExpenses"), totalCapitalCost: sumIfKnown("totalCapitalCost"), cashFlowBeforeDebtService: sumIfKnown("cashFlowBeforeDebtService") }; });
  const body = { schemaVersion: CASH_FLOW_FORECAST_VERSION, organizationId: operations.organizationId, assetId, asOf, evaluatedAt, horizonMonths, currency: asset.currency, status: months.every((item) => item.cashFlowBeforeDebtService !== null) ? "complete" : "partial", months, annual, findings: [...findings].filter(Boolean).sort(), evidenceSha256s: [...evidence].sort(), methodology: "contracted-rent-plus-deterministic-weighted-rollover-less-operating-expense-and-approved-capital-cost", probabilityClaim: false };
  return seal({}, body, "forecastSha256", "WR_CASH_FLOW_FORECAST_INTEGRITY_FAILURE");
}

function applyScenario(strategy, scenario) { const assumptions = strategy.assumptions.map((assumption) => { const shocks = scenario.shocks.filter((shock) => shock.metric === assumption.metric && (!shock.leaseId || shock.leaseId === assumption.leaseId)); if (!shocks.length || assumption.value === null) return assumption; const value = shocks.reduce((current, shock) => shock.operation === "multiply" ? current * shock.value : current + shock.value, assumption.value); return createForecastAssumption({ ...assumption, assumptionSha256: undefined, status: "scenario-derived", value, rationale: `Derived from ${assumption.assumptionSha256} under deterministic scenario ${scenario.id}` }); }); return createForwardStrategyState({ ...strategy, assumptions }); }
export function runStressScenario(operationsInput, strategyInput, scenarioInput, input = {}) {
  const strategy = createForwardStrategyState(strategyInput), scenario = createStressScenario(scenarioInput); if (scenario.organizationId !== strategy.organizationId || strategy.stressScenarios.every((item) => item.id !== scenario.id)) throw error("WR_STRESS_SCENARIO_SCOPE_MISMATCH", "Stress scenario must belong to the persisted strategy state");
  const base = buildCashFlowForecast(operationsInput, strategy, input), stressed = buildCashFlowForecast(operationsInput, applyScenario(strategy, scenario), input); if (base.assetId !== scenario.assetId) throw error("WR_STRESS_SCENARIO_SCOPE_MISMATCH", "Stress scenario asset does not match forecast asset");
  const years = base.annual.map((item) => { const stressedYear = stressed.annual.find((candidate) => candidate.year === item.year), baseValue = item.cashFlowBeforeDebtService, stressedValue = stressedYear?.cashFlowBeforeDebtService ?? null; return { year: item.year, baseCashFlow: baseValue, stressedCashFlow: stressedValue, delta: baseValue !== null && stressedValue !== null ? round(stressedValue - baseValue) : null, deltaPct: baseValue !== null && baseValue !== 0 && stressedValue !== null ? round((stressedValue - baseValue) / Math.abs(baseValue) * 100) : null }; });
  const body = { schemaVersion: STRESS_REPORT_VERSION, organizationId: strategy.organizationId, assetId: scenario.assetId, scenarioId: scenario.id, scenarioSha256: scenario.scenarioSha256, baseForecastSha256: base.forecastSha256, stressedForecastSha256: stressed.forecastSha256, evaluatedAt: base.evaluatedAt, status: years.every((item) => item.delta !== null) ? "complete" : "partial", deterministicScenario: true, probabilityAssigned: false, years };
  return seal({}, body, "reportSha256", "WR_STRESS_REPORT_INTEGRITY_FAILURE");
}

function assertMutation(state, context) { if (context.organizationId !== state.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Forward-strategy mutation tenant mismatch"); if (!(context.grants || []).includes("forward-strategy:write")) throw error("WR_FORWARD_STRATEGY_PERMISSION_DENIED", "forward-strategy:write grant is required"); if (Number(context.expectedRevision) !== state.revision) throw error("WR_REVISION_CONFLICT", `Forward-strategy revision conflict: expected ${context.expectedRevision}, found ${state.revision}`); const occurredAt = iso(context.occurredAt, "context.occurredAt"); if (occurredAt < state.updatedAt) throw error("WR_FORWARD_STRATEGY_TIME_REGRESSION", "Forward-strategy state cannot move backward in time"); return occurredAt; }
function addRecord(stateInput, collection, record, context) { const state = createForwardStrategyState(stateInput), occurredAt = assertMutation(state, context); if (record.organizationId !== state.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Forward-strategy record belongs to another tenant"); return createForwardStrategyState({ ...state, revision: state.revision + 1, [collection]: [...state[collection], record], updatedAt: occurredAt }); }
export function addForecastAssumption(state, input, context = {}) { return addRecord(state, "assumptions", createForecastAssumption(input), context); }
export function addCapitalProject(state, input, context = {}) { return addRecord(state, "capitalProjects", createCapitalProject(input), context); }
export function addStressScenario(state, input, context = {}) { return addRecord(state, "stressScenarios", createStressScenario(input), context); }
