export const OPERATING_CONNECTOR_VERSION: "wr-operating-connector-v1";
export const OPERATING_MAPPING_PROFILE_VERSION: "wr-operating-mapping-profile-v1";
export const OPERATING_RAW_PAGE_VERSION: "wr-operating-raw-page-v1";
export const OPERATING_MAPPING_RESULT_VERSION: "wr-operating-mapping-result-v1";
export const OPERATING_CONNECTOR_JOB_VERSION: "wr-operating-connector-job-v1";
export const OPERATING_CONNECTOR_WORKER_STATE_VERSION: "wr-operating-connector-worker-state-v1";
export const OPERATING_CONNECTOR_RUN_VERSION: "wr-operating-connector-run-v1";
export const OPERATING_CONNECTOR_DEAD_LETTER_VERSION: "wr-operating-connector-dead-letter-v1";
export const OPERATING_BACKFILL_PLAN_VERSION: "wr-operating-backfill-plan-v1";
export function connectorRuntimeSha256(value: unknown): string;
export function createOperatingConnector(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createOperatingMappingProfile(input?: Record<string, any>): Readonly<Record<string, any>>;
export function mapOperatingConnectorPage(connector: Record<string, any>, profile: Record<string, any>, page: Record<string, any>): Readonly<Record<string, any>>;
export function createOperatingConnectorJob(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createOperatingConnectorWorkerState(input?: Record<string, any>): Readonly<Record<string, any>>;
export function enqueueOperatingConnectorJobs(state: Record<string, any>, jobs?: Array<Record<string, any>>, options?: Record<string, any>): Readonly<Record<string, any>>;
export function leaseOperatingConnectorJobs(state: Record<string, any>, input?: Record<string, any>): Record<string, any>;
export function createOperatingBackfillPlan(connector: Record<string, any>, input?: Record<string, any>): Readonly<Record<string, any>>;
export function runOperatingConnectorWorkerCycle(options?: Record<string, any>): Promise<Record<string, any>>;
export function requeueOperatingConnectorDeadLetter(state: Record<string, any>, deadLetterId: string, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
