export const OPERATING_VENDOR_PROFILE_VERSION: "wr-operating-vendor-profile-v1";
export const MANAGED_SECRET_RESOLUTION_VERSION: "wr-managed-secret-resolution-v1";
export const PROVIDER_EXECUTION_POLICY_VERSION: "wr-provider-execution-policy-v1";
export const PROVIDER_EXECUTION_STATE_VERSION: "wr-provider-execution-state-v1";
export const PROVIDER_EXECUTION_PERMIT_VERSION: "wr-provider-execution-permit-v1";
export const VENDOR_SANDBOX_CERTIFICATION_PACK_VERSION: "wr-vendor-sandbox-certification-pack-v1";
export const OPERATING_VENDOR_SANDBOX_PROFILES: ReadonlyArray<Readonly<Record<string, any>>>;
export function operatingProviderSha256(value: unknown): string;
export function createOperatingVendorProfile(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createManagedSecretResolver(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createOperatingProviderAdapter(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createProviderExecutionPolicy(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createProviderExecutionState(input?: Record<string, any>): Readonly<Record<string, any>>;
export function beginProviderExecution(state: Record<string, any>, input?: Record<string, any>): Record<string, any>;
export function completeProviderExecution(state: Record<string, any>, permit: Record<string, any>, outcome?: Record<string, any>, options?: Record<string, any>): Readonly<Record<string, any>>;
export function createDurableProviderExecutionController(input?: Record<string, any>): Readonly<Record<string, any>>;
export function persistConnectorSchemaAssessment(repository: Record<string, any>, context: Record<string, any>, assessment: Record<string, any>, options?: Record<string, any>): Record<string, any>;
export function createDurableSchemaAssessmentJournal(input?: Record<string, any>): Readonly<Record<string, any>>;
export function buildVendorSandboxCertificationPack(input?: Record<string, any>): Readonly<Record<string, any>>;
export function validateVendorSandboxCertificationPack(input?: Record<string, any>): Readonly<Record<string, any>>;
