export const OPERATING_FEED_RECORD_VERSION: "wr-operating-feed-record-v1";
export const OPERATING_FEED_BATCH_VERSION: "wr-operating-feed-batch-v1";
export const OPERATING_FEED_CHECKPOINT_VERSION: "wr-operating-feed-checkpoint-v1";
export const OPERATING_RECONCILIATION_REPORT_VERSION: "wr-operating-reconciliation-report-v1";
export const OPERATING_FEED_APPLICATION_VERSION: "wr-operating-feed-application-v1";
export const ACCOUNTING_PERIOD_VERSION: "wr-accounting-period-v1";
export const OPERATING_CORRECTION_VERSION: "wr-operating-correction-v1";
export const OPERATING_RESTATEMENT_VERSION: "wr-operating-restatement-v1";
export const REFORECAST_REQUEST_VERSION: "wr-reforecast-request-v1";
export const OPERATING_CONTROL_STATE_VERSION: "wr-operating-control-state-v1";
export function operatingControlSha256(value: unknown): string;
export function createOperatingFeedRecord(input?: Record<string, any>): Readonly<Record<string, any>>;
export function ingestOperatingFeedBatch(input?: Record<string, any>): Readonly<Record<string, any>>;
export function reconcileOperatingFeedBatch(batch: Record<string, any>, operations: Record<string, any>, strategy: Record<string, any>, input?: Record<string, any>): Readonly<Record<string, any>>;
export function applyReconciledOperatingFeedBatch(batch: Record<string, any>, reconciliation: Record<string, any>, operations: Record<string, any>, strategy: Record<string, any>, controls: Record<string, any>, input?: Record<string, any>): Readonly<Record<string, any>>;
export function persistAppliedOperatingFeedBatch(repository: Record<string, any>, context: Record<string, any>, batch: Record<string, any>, reconciliation: Record<string, any>, applied: Record<string, any>, options?: Record<string, any>): Record<string, any>;
export function persistOperatingFeedBatch(repository: Record<string, any>, context: Record<string, any>, batch: Record<string, any>, reconciliation: Record<string, any>, options?: Record<string, any>): Record<string, any>;
export function createAccountingPeriod(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createOperatingCorrection(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createOperatingRestatement(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createReforecastRequest(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createOperatingControlState(input?: Record<string, any>): Readonly<Record<string, any>>;
export function addAccountingPeriod(state: Record<string, any>, period: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function closeAccountingPeriod(state: Record<string, any>, periodId: string, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function proposeOperatingCorrection(state: Record<string, any>, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function requestOperatingRestatement(state: Record<string, any>, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function approveOperatingRestatement(state: Record<string, any>, restatementId: string, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function applyOperatingRestatement(state: Record<string, any>, restatementId: string, context?: Record<string, any>): Readonly<Record<string, any>>;
export function approveOperatingCorrection(state: Record<string, any>, correctionId: string, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function applyOperatingCorrection(state: Record<string, any>, correctionId: string, operations: Record<string, any>, strategy: Record<string, any>, context?: Record<string, any>, options?: Record<string, any>): Readonly<Record<string, any>>;
export function persistOperatingCorrectionApplication(repository: Record<string, any>, context: Record<string, any>, applied: Record<string, any>, options?: Record<string, any>): Record<string, any>;
export function requestReforecast(state: Record<string, any>, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function approveReforecast(state: Record<string, any>, requestId: string, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function recordGeneratedReforecast(state: Record<string, any>, requestId: string, forecastSha256: string, context?: Record<string, any>): Readonly<Record<string, any>>;
