export const CONNECTOR_SCHEMA_BASELINE_VERSION: "wr-connector-schema-baseline-v1";
export const CONNECTOR_SCHEMA_ASSESSMENT_VERSION: "wr-connector-schema-assessment-v1";
export const CONNECTOR_CREDENTIAL_BINDING_VERSION: "wr-connector-credential-binding-v1";
export const CONNECTOR_CREDENTIAL_ROTATION_VERSION: "wr-connector-credential-rotation-v1";
export const CONNECTOR_DRILL_PLAN_VERSION: "wr-connector-drill-plan-v1";
export const CONNECTOR_DRILL_RESULT_VERSION: "wr-connector-drill-result-v1";
export const OPERATING_ADAPTER_CERTIFICATION_VERSION: "wr-operating-adapter-certification-v1";
export const CONNECTOR_HEALTH_REPORT_VERSION: "wr-connector-health-report-v1";
export const CONNECTOR_ASSURANCE_STATE_VERSION: "wr-connector-assurance-state-v1";
export function connectorAssuranceSha256(value: unknown): string;
export function createConnectorSchemaBaseline(input?: Record<string, any>): Readonly<Record<string, any>>;
export function assessConnectorSchemaPage(baseline: Record<string, any>, page: Record<string, any>, options?: Record<string, any>): Readonly<Record<string, any>>;
export function createConnectorSchemaGuard(state: Record<string, any>, connectorId: string, options?: Record<string, any>): (connector: Record<string, any>, page: Record<string, any>) => Record<string, any>;
export function createConnectorCredentialBinding(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createConnectorCredentialRotation(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createConnectorDrillPlan(input?: Record<string, any>): Readonly<Record<string, any>>;
export function runConnectorDrillSuite(plan: Record<string, any>, executeScenario: (input: Record<string, any>) => Promise<Record<string, any>> | Record<string, any>, options?: Record<string, any>): Promise<Readonly<Record<string, any>>>;
export function certifyOperatingAdapter(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createConnectorHealthReport(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createConnectorAssuranceState(input?: Record<string, any>): Readonly<Record<string, any>>;
export function applyApprovedCredentialRotation(workerState: Record<string, any>, assuranceState: Record<string, any>, rotationId: string, context?: Record<string, any>): Readonly<Record<string, any>>;
export function persistAppliedCredentialRotation(repository: Record<string, any>, context: Record<string, any>, result: Record<string, any>, options?: Record<string, any>): Record<string, any>;
