import { createHash } from "node:crypto";
import { createAssetOperationsState, createLeaseRecord, createLeaseAmendment, createOperatingStatement, createAssetBudget, createDebtCovenant, createAssetPlan, createOperatingEvidenceSource } from "./assetOperations.mjs";

export const RENT_ROLL_SNAPSHOT_VERSION = "wr-rent-roll-snapshot-v1";
export const OPERATING_METRICS_VERSION = "wr-operating-metrics-v1";
export const BUDGET_VARIANCE_VERSION = "wr-budget-variance-v1";
export const DEBT_COVENANT_REPORT_VERSION = "wr-debt-covenant-report-v1";
export const OPERATING_ANOMALY_REPORT_VERSION = "wr-operating-anomaly-report-v1";
export const FX_RATE_EVIDENCE_VERSION = "wr-fx-rate-evidence-v1";
export const PORTFOLIO_SNAPSHOT_VERSION = "wr-portfolio-snapshot-v1";
export const ASSET_PLAN_PROGRESS_VERSION = "wr-asset-plan-progress-v1";

function required(value, name) { const normalized = String(value || "").trim(); if (!normalized) throw new TypeError(`${name} is required`); return normalized; }
function iso(value, name) { const date = new Date(value); if (!Number.isFinite(date.getTime())) throw new TypeError(`${name} must be a valid date`); return date.toISOString(); }
function dateOnly(value, name) { const normalized = String(value || ""); if (!/^\d{4}-\d{2}-\d{2}$/.test(normalized) || new Date(`${normalized}T00:00:00.000Z`).toISOString().slice(0, 10) !== normalized) throw new TypeError(`${name} must be YYYY-MM-DD`); return normalized; }
function canonicalJson(value) { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`; return JSON.stringify(value ?? null); }
function sha256(value) { return createHash("sha256").update(typeof value === "string" || Buffer.isBuffer(value) ? value : canonicalJson(value)).digest("hex"); }
function seal(body, field) { return Object.freeze({ ...body, [field]: sha256(body) }); }
function round(value, digits = 6) { return Number(Number(value).toFixed(digits)); }
function sourceEligibility(source, evaluatedAt) { const at = new Date(evaluatedAt).getTime(), reasons = []; if (source.licenseStatus !== "authorized") reasons.push(`license-${source.licenseStatus}`); if (new Date(source.observedAt).getTime() > at || new Date(source.availableAt).getTime() > at) reasons.push("future-evidence"); if (source.expiresAt && new Date(source.expiresAt).getTime() <= at) reasons.push("evidence-expired"); return { eligible: reasons.length === 0, reasons }; }

function applyAmendment(terms, amendment) { return { ...terms, expirationDate: amendment.changes.expirationDate || terms.expirationDate, areaSqFt: amendment.changes.areaSqFt || terms.areaSqFt, unitIds: amendment.changes.unitIds || terms.unitIds, baseRentSchedule: amendment.changes.baseRentSchedule || terms.baseRentSchedule, recoveryStructure: amendment.changes.recoveryStructure || terms.recoveryStructure, status: amendment.changes.status || terms.status }; }
function rentAt(schedule, asOf) { const period = schedule.find((item) => item.effectiveFrom <= asOf && item.effectiveTo >= asOf); return period ? period.monthlyAmount : { status: "unknown", value: null, sourceField: "" }; }

export function materializeLeaseAsOf(stateInput, leaseId, options = {}) {
  const state = createAssetOperationsState(stateInput), asOf = dateOnly(options.asOf, "asOf"), evaluatedAt = iso(options.evaluatedAt, "evaluatedAt"), lease = state.leases.find((item) => item.id === leaseId || item.leaseId === leaseId); if (!lease) throw new TypeError(`Unknown lease: ${leaseId}`);
  const baseEligibility = sourceEligibility(lease.source, evaluatedAt); if (!baseEligibility.eligible) return Object.freeze({ leaseId: lease.leaseId, leaseRecordId: lease.id, assetId: lease.assetId, status: "unavailable", reasons: baseEligibility.reasons, appliedAmendmentIds: [], excludedAmendments: [], terms: null, monthlyBaseRent: { status: "unknown", value: null, sourceField: "" } });
  let terms = { commencementDate: lease.commencementDate, expirationDate: lease.expirationDate, areaSqFt: lease.areaSqFt, unitIds: lease.unitIds, baseRentSchedule: lease.baseRentSchedule, recoveryStructure: lease.recoveryStructure, status: lease.status }, chainBlocked = false; const appliedAmendmentIds = [], excludedAmendments = [];
  for (const amendment of state.amendments.filter((item) => item.leaseId === lease.leaseId && item.assetId === lease.assetId).sort((a, b) => a.sequence - b.sequence)) {
    if (amendment.effectiveDate > asOf) { excludedAmendments.push({ id: amendment.id, reason: "not-effective-as-of" }); continue; }
    const eligibility = sourceEligibility(amendment.source, evaluatedAt); if (chainBlocked || !eligibility.eligible) { chainBlocked = true; excludedAmendments.push({ id: amendment.id, reason: chainBlocked && eligibility.eligible ? "predecessor-unavailable" : eligibility.reasons.join(",") }); continue; }
    terms = applyAmendment(terms, amendment); appliedAmendmentIds.push(amendment.id);
  }
  const active = terms.status === "executed" && terms.commencementDate <= asOf && terms.expirationDate >= asOf; const monthlyBaseRent = active ? rentAt(terms.baseRentSchedule, asOf) : { status: "unknown", value: null, sourceField: "" };
  return Object.freeze({ leaseId: lease.leaseId, leaseRecordId: lease.id, assetId: lease.assetId, tenantEntityId: lease.tenantEntityId, tenantDisplayName: lease.tenantDisplayName, currency: lease.currency, status: active ? "active" : "inactive", reasons: active ? [] : [terms.status !== "executed" ? `lease-${terms.status}` : "outside-lease-term"], appliedAmendmentIds, excludedAmendments, terms: Object.freeze(terms), monthlyBaseRent, evidenceSha256s: [lease.leaseSha256, ...appliedAmendmentIds.map((id) => state.amendments.find((item) => item.id === id).amendmentSha256)] });
}

export function buildRentRollSnapshot(stateInput, assetId, options = {}) {
  const state = createAssetOperationsState(stateInput), asOf = dateOnly(options.asOf, "asOf"), evaluatedAt = iso(options.evaluatedAt, "evaluatedAt"), asset = state.assets.find((item) => item.id === assetId); if (!asset) throw new TypeError(`Unknown asset: ${assetId}`); const assetEligibility = sourceEligibility(asset.source, evaluatedAt), leases = state.leases.filter((item) => item.assetId === assetId).map((item) => materializeLeaseAsOf(state, item.id, { asOf, evaluatedAt })), activeLeases = leases.filter((item) => item.status === "active"), unitOwners = new Map(), conflicts = [];
  for (const lease of activeLeases) for (const unitId of lease.terms.unitIds) { if (unitOwners.has(unitId)) conflicts.push({ unitId, leaseIds: [unitOwners.get(unitId), lease.leaseId].sort() }); else unitOwners.set(unitId, lease.leaseId); }
  const knownRent = activeLeases.filter((item) => item.monthlyBaseRent.status === "observed").reduce((sum, item) => sum + item.monthlyBaseRent.value, 0), unknownRentLeaseCount = activeLeases.filter((item) => item.monthlyBaseRent.status !== "observed").length, allAreasKnown = activeLeases.every((item) => item.terms.areaSqFt.status === "observed"), occupiedArea = allAreasKnown ? activeLeases.reduce((sum, item) => sum + item.terms.areaSqFt.value, 0) : null, totalArea = asset.rentableAreaSqFt.status === "observed" ? asset.rentableAreaSqFt.value : null, areaConflict = occupiedArea !== null && totalArea !== null && occupiedArea > totalArea + 0.000001;
  const occupancyPct = assetEligibility.eligible && !conflicts.length && !areaConflict && occupiedArea !== null && totalArea !== null && totalArea > 0 ? round(occupiedArea / totalArea * 100) : null; const findings = [...(!assetEligibility.eligible ? assetEligibility.reasons.map((reason) => ({ code: `asset-${reason}` })) : []), ...conflicts.map((item) => ({ code: "unit-double-leased", ...item })), ...(areaConflict ? [{ code: "occupied-area-exceeds-rentable-area" }] : []), ...(unknownRentLeaseCount ? [{ code: "monthly-rent-unknown", leaseCount: unknownRentLeaseCount }] : []), ...(!allAreasKnown ? [{ code: "leased-area-unknown" }] : [])];
  const body = { schemaVersion: RENT_ROLL_SNAPSHOT_VERSION, organizationId: state.organizationId, assetId, whiteRabbitPropertyId: asset.whiteRabbitPropertyId, asOf, evaluatedAt, currency: asset.currency, status: conflicts.length || areaConflict ? "conflicted" : findings.length ? "partial" : "complete", activeLeaseCount: activeLeases.length, activeLeases, excludedLeases: leases.filter((item) => item.status !== "active").map((item) => ({ leaseId: item.leaseId, status: item.status, reasons: item.reasons })), metrics: { knownMonthlyBaseRent: round(knownRent), totalMonthlyBaseRent: assetEligibility.eligible && !unknownRentLeaseCount ? round(knownRent) : null, unknownRentLeaseCount, occupiedAreaSqFt: occupiedArea, rentableAreaSqFt: totalArea, occupancyPct }, coverage: { totalLeaseCount: leases.length, activeLeaseCount: activeLeases.length, knownRentLeaseCount: activeLeases.length - unknownRentLeaseCount, knownAreaLeaseCount: activeLeases.filter((item) => item.terms.areaSqFt.status === "observed").length }, findings, sourceEvidenceSha256s: [...new Set([asset.assetSha256, ...activeLeases.flatMap((item) => item.evidenceSha256s || [])])].sort() };
  return seal(body, "snapshotSha256");
}

function eligibleFinancial(record, evaluatedAt) { const eligibility = sourceEligibility(record.source, evaluatedAt); return { record, ...eligibility }; }
export function deriveOperatingMetrics(statementInput, options = {}) {
  const statement = createOperatingStatement(statementInput), evaluatedAt = iso(options.evaluatedAt, "evaluatedAt"), eligibility = sourceEligibility(statement.source, evaluatedAt), entries = statement.entries.filter((item) => item.status === "observed"), sum = (category) => entries.filter((item) => item.category === category).reduce((total, item) => total + item.amount, 0), revenue = sum("revenue"), operatingExpense = sum("operating-expense"), debtService = sum("debt-service"), capitalExpenditure = sum("capital-expenditure"), complete = eligibility.eligible && statement.completeness.status === "complete";
  const body = { schemaVersion: OPERATING_METRICS_VERSION, organizationId: statement.organizationId, assetId: statement.assetId, statementId: statement.id, statementSha256: statement.statementSha256, periodStart: statement.periodStart, periodEnd: statement.periodEnd, evaluatedAt, currency: statement.currency, status: complete ? "complete" : "partial", metrics: { knownRevenue: round(revenue), revenue: complete ? round(revenue) : null, knownOperatingExpense: round(operatingExpense), operatingExpense: complete ? round(operatingExpense) : null, noi: complete ? round(revenue - operatingExpense) : null, debtService: complete ? round(debtService) : null, capitalExpenditure: complete ? round(capitalExpenditure) : null }, missingAccountCodes: statement.completeness.missingAccountCodes, findings: [...eligibility.reasons] };
  return seal(body, "metricsSha256");
}

export function analyzeBudgetVariance(statementInput, budgetInput, options = {}) {
  const statement = createOperatingStatement(statementInput), budget = createAssetBudget(budgetInput), evaluatedAt = iso(options.evaluatedAt, "evaluatedAt"); if (statement.organizationId !== budget.organizationId || statement.assetId !== budget.assetId) throw new TypeError("Statement and budget scope do not match"); if (statement.periodStart !== budget.periodStart || statement.periodEnd !== budget.periodEnd || statement.currency !== budget.currency || statement.basis !== budget.basis) throw new TypeError("Statement and budget periods, currency, and basis must match"); const actualEligibility = eligibleFinancial(statement, evaluatedAt), budgetEligibility = eligibleFinancial(budget, evaluatedAt), codes = [...new Set([...statement.expectedAccountCodes, ...budget.expectedAccountCodes])].sort();
  const lines = codes.map((accountCode) => { const actual = statement.entries.find((item) => item.accountCode === accountCode), planned = budget.entries.find((item) => item.accountCode === accountCode), known = actualEligibility.eligible && budgetEligibility.eligible && actual?.status === "observed" && planned?.status === "observed"; const variance = known ? actual.amount - planned.amount : null; return { accountCode, accountName: actual?.accountName || planned?.accountName || accountCode, category: actual?.category || planned?.category || "other", status: known ? "calculated" : "indeterminate", actual: known ? actual.amount : null, budget: known ? planned.amount : null, variance: known ? round(variance) : null, variancePct: known && planned.amount !== 0 ? round(variance / Math.abs(planned.amount) * 100) : null, explanation: !known ? "Actual or budget evidence is missing/unavailable." : planned.amount === 0 ? "Percentage variance is undefined because budget is zero." : variance > 0 ? "Actual is above budget." : variance < 0 ? "Actual is below budget." : "Actual matches budget." }; }); const indeterminateLineCount = lines.filter((item) => item.status === "indeterminate").length;
  const body = { schemaVersion: BUDGET_VARIANCE_VERSION, organizationId: statement.organizationId, assetId: statement.assetId, statementId: statement.id, statementSha256: statement.statementSha256, budgetId: budget.id, budgetSha256: budget.budgetSha256, periodStart: statement.periodStart, periodEnd: statement.periodEnd, evaluatedAt, currency: statement.currency, status: indeterminateLineCount ? "partial" : "complete", lines, coverage: { totalLineCount: lines.length, calculatedLineCount: lines.length - indeterminateLineCount, indeterminateLineCount }, findings: [...actualEligibility.reasons.map((item) => `actual-${item}`), ...budgetEligibility.reasons.map((item) => `budget-${item}`)] };
  return seal(body, "varianceSha256");
}

function observedEnvelope(input, name, evaluatedAt) { if (!input || input.status !== "observed") return { status: "unknown", value: null, sourceSha256: "", reasons: [`${name}-unknown`] }; const value = Number(input.value); if (!Number.isFinite(value) || value < 0) throw new TypeError(`${name}.value is invalid`); const source = createOperatingEvidenceSource(input.source), eligibility = sourceEligibility(source, evaluatedAt); return eligibility.eligible ? { status: "observed", value, sourceSha256: source.sourceSha256, reasons: [] } : { status: "unknown", value: null, sourceSha256: source.sourceSha256, reasons: eligibility.reasons.map((reason) => `${name}-${reason}`) }; }

export function evaluateDebtCovenants(input = {}) {
  const evaluatedAt = iso(input.evaluatedAt, "evaluatedAt"), asOf = dateOnly(input.asOf, "asOf"), statement = createOperatingStatement(input.statement), statementMetrics = deriveOperatingMetrics(statement, { evaluatedAt }), rentRoll = input.rentRoll, loanBalance = observedEnvelope(input.loanBalance, "loan-balance", evaluatedAt), valuation = observedEnvelope(input.valuation, "valuation", evaluatedAt), covenants = (input.covenants || []).map(createDebtCovenant).filter((item) => item.effectiveFrom <= asOf && (!item.effectiveTo || item.effectiveTo >= asOf)); if (!covenants.length) throw new TypeError("No active debt covenants were supplied");
  if (covenants.some((item) => item.organizationId !== covenants[0].organizationId || item.assetId !== covenants[0].assetId) || statement.organizationId !== covenants[0].organizationId || statement.assetId !== covenants[0].assetId || (rentRoll && (rentRoll.organizationId !== covenants[0].organizationId || rentRoll.assetId !== covenants[0].assetId))) throw new TypeError("Covenant evidence scope does not match");
  const metric = (name) => { if (name === "dscr") return statementMetrics.metrics.noi !== null && statementMetrics.metrics.debtService > 0 ? { value: statementMetrics.metrics.noi / statementMetrics.metrics.debtService, reasons: [] } : { value: null, reasons: ["noi-or-debt-service-unknown"] }; if (name === "debt-yield") return statementMetrics.metrics.noi !== null && loanBalance.value > 0 ? { value: statementMetrics.metrics.noi / loanBalance.value * 100, reasons: loanBalance.reasons } : { value: null, reasons: ["noi-or-loan-balance-unknown", ...loanBalance.reasons] }; if (name === "ltv") return loanBalance.value !== null && valuation.value > 0 ? { value: loanBalance.value / valuation.value * 100, reasons: [...loanBalance.reasons, ...valuation.reasons] } : { value: null, reasons: ["loan-balance-or-valuation-unknown", ...loanBalance.reasons, ...valuation.reasons] }; return rentRoll?.metrics?.occupancyPct !== null && rentRoll?.metrics?.occupancyPct !== undefined ? { value: rentRoll.metrics.occupancyPct, reasons: [] } : { value: null, reasons: ["occupancy-unknown"] }; };
  const results = covenants.map((covenant) => { const source = sourceEligibility(covenant.source, evaluatedAt), measured = metric(covenant.metric), value = source.eligible ? measured.value : null, passed = value === null ? null : covenant.comparator === ">=" ? value >= covenant.threshold : value <= covenant.threshold; return { covenantId: covenant.id, covenantSha256: covenant.covenantSha256, metric: covenant.metric, comparator: covenant.comparator, threshold: covenant.threshold, measuredValue: value === null ? null : round(value), status: passed === null ? "indeterminate" : passed ? "passed" : "failed", curePeriodDays: covenant.curePeriodDays, findings: [...source.reasons, ...measured.reasons] }; });
  const body = { schemaVersion: DEBT_COVENANT_REPORT_VERSION, organizationId: covenants[0].organizationId, assetId: covenants[0].assetId, asOf, evaluatedAt, status: results.some((item) => item.status === "failed") ? "failed" : results.some((item) => item.status === "indeterminate") ? "indeterminate" : "passed", results, statementMetricsSha256: statementMetrics.metricsSha256, rentRollSnapshotSha256: String(rentRoll?.snapshotSha256 || ""), supportingEvidenceSha256s: [loanBalance.sourceSha256, valuation.sourceSha256].filter(Boolean).sort() };
  return seal(body, "reportSha256");
}

function median(values) { const sorted = [...values].sort((a, b) => a - b), mid = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2; }
export function detectOperatingAnomalies(input = {}) {
  const evaluatedAt = iso(input.evaluatedAt, "evaluatedAt"), asOf = dateOnly(input.asOf, "asOf"), thresholdPct = Math.max(0, Number(input.thresholdPct) || 20), minimumPriorPeriods = Math.max(2, Math.trunc(Number(input.minimumPriorPeriods) || 3)); const statements = (input.statements || []).map(createOperatingStatement).filter((item) => item.periodEnd <= asOf && sourceEligibility(item.source, evaluatedAt).eligible).sort((a, b) => a.periodEnd.localeCompare(b.periodEnd)); const latest = statements.at(-1); if (!latest) return seal({ schemaVersion: OPERATING_ANOMALY_REPORT_VERSION, organizationId: required(input.organizationId, "organizationId"), assetId: required(input.assetId, "assetId"), asOf, evaluatedAt, status: "insufficient-evidence", anomalies: [], findings: ["no-eligible-statements"] }, "reportSha256");
  if (statements.some((item) => item.organizationId !== latest.organizationId || item.assetId !== latest.assetId)) throw new TypeError("Anomaly statement histories must share one organization and asset");
  const prior = statements.slice(0, -1), anomalies = [], findings = [];
  for (const entry of latest.entries.filter((item) => item.status === "observed")) { const history = prior.map((statement) => statement.entries.find((item) => item.accountCode === entry.accountCode && item.status === "observed")?.amount).filter(Number.isFinite); if (history.length < minimumPriorPeriods) { findings.push({ accountCode: entry.accountCode, code: "insufficient-history", observedPeriods: history.length }); continue; } const baseline = median(history); if (baseline === 0) { findings.push({ accountCode: entry.accountCode, code: "zero-baseline-percent-undefined" }); continue; } const changePct = (entry.amount - baseline) / Math.abs(baseline) * 100; if (Math.abs(changePct) >= thresholdPct) anomalies.push({ accountCode: entry.accountCode, accountName: entry.accountName, category: entry.category, currentAmount: entry.amount, trailingMedian: round(baseline), changePct: round(changePct), thresholdPct, direction: changePct > 0 ? "increase" : "decrease", explanation: `Current observed amount differs from the trailing median by ${round(Math.abs(changePct), 2)}%.`, evidenceStatementIds: [latest.id, ...prior.filter((statement) => statement.entries.some((item) => item.accountCode === entry.accountCode && item.status === "observed")).map((item) => item.id)] }); }
  const body = { schemaVersion: OPERATING_ANOMALY_REPORT_VERSION, organizationId: latest.organizationId, assetId: latest.assetId, asOf, evaluatedAt, status: anomalies.length ? "anomalies-detected" : findings.length ? "partial" : "no-anomalies", method: "trailing-median-threshold", statisticalConfidenceInterval: false, thresholdPct, minimumPriorPeriods, anomalies, findings };
  return seal(body, "reportSha256");
}

export function createFxRateEvidence(input = {}) { const rate = Number(input.rate); if (!Number.isFinite(rate) || rate <= 0) throw new TypeError("FX rate must be positive"); const body = { schemaVersion: FX_RATE_EVIDENCE_VERSION, fromCurrency: required(input.fromCurrency, "fromCurrency").toUpperCase(), toCurrency: required(input.toCurrency, "toCurrency").toUpperCase(), rate, asOf: dateOnly(input.asOf, "asOf"), source: createOperatingEvidenceSource(input.source) }; return seal(body, "fxRateSha256"); }
function activeMembership(asset, portfolioId, asOf) { return asset.portfolioMemberships.some((item) => item.portfolioId === portfolioId && item.effectiveFrom <= asOf && (!item.effectiveTo || item.effectiveTo >= asOf)); }
function rateFor(currency, baseCurrency, rates, asOf, evaluatedAt) { if (currency === baseCurrency) return { rate: 1, evidenceSha256: "" }; const evidence = rates.filter((item) => item.fromCurrency === currency && item.toCurrency === baseCurrency && item.asOf <= asOf && sourceEligibility(item.source, evaluatedAt).eligible).sort((a, b) => b.asOf.localeCompare(a.asOf))[0]; return evidence ? { rate: evidence.rate, evidenceSha256: evidence.fxRateSha256 } : null; }

export function buildPortfolioSnapshot(stateInput, input = {}) {
  const state = createAssetOperationsState(stateInput), portfolioId = required(input.portfolioId, "portfolioId"), asOf = dateOnly(input.asOf, "asOf"), evaluatedAt = iso(input.evaluatedAt, "evaluatedAt"), baseCurrency = required(input.baseCurrency, "baseCurrency").toUpperCase(), fxRates = (input.fxRates || []).map(createFxRateEvidence), assets = state.assets.filter((item) => activeMembership(item, portfolioId, asOf) && item.acquiredOn <= asOf && (!item.disposedOn || item.disposedOn > asOf)), assetSummaries = [];
  for (const asset of assets) { const assetEligibility = sourceEligibility(asset.source, evaluatedAt), rentRoll = buildRentRollSnapshot(state, asset.id, { asOf, evaluatedAt }), statement = assetEligibility.eligible ? state.statements.filter((item) => item.assetId === asset.id && item.periodEnd <= asOf && sourceEligibility(item.source, evaluatedAt).eligible).sort((a, b) => b.periodEnd.localeCompare(a.periodEnd))[0] || null : null, operatingMetrics = statement ? deriveOperatingMetrics(statement, { evaluatedAt }) : null, fx = assetEligibility.eligible ? rateFor(asset.currency, baseCurrency, fxRates, asOf, evaluatedAt) : null; assetSummaries.push({ assetId: asset.id, whiteRabbitPropertyId: asset.whiteRabbitPropertyId, currency: asset.currency, fxRate: fx?.rate ?? null, fxRateEvidenceSha256: fx?.evidenceSha256 || "", rentRollSnapshotSha256: rentRoll.snapshotSha256, operatingMetricsSha256: operatingMetrics?.metricsSha256 || "", monthlyBaseRent: rentRoll.metrics.totalMonthlyBaseRent, monthlyBaseRentBaseCurrency: fx && rentRoll.metrics.totalMonthlyBaseRent !== null ? round(rentRoll.metrics.totalMonthlyBaseRent * fx.rate) : null, noi: operatingMetrics?.metrics.noi ?? null, noiBaseCurrency: fx && operatingMetrics?.metrics.noi !== null && operatingMetrics?.metrics.noi !== undefined ? round(operatingMetrics.metrics.noi * fx.rate) : null, occupancyPct: rentRoll.metrics.occupancyPct, rentableAreaSqFt: rentRoll.metrics.rentableAreaSqFt, findings: [...rentRoll.findings.map((item) => item.code), ...assetEligibility.reasons.map((item) => `asset-${item}`), ...(!statement ? ["operating-statement-missing"] : []), ...(!fx ? ["fx-rate-missing"] : [])] }); }
  const knownRentAssets = assetSummaries.filter((item) => item.monthlyBaseRentBaseCurrency !== null), knownNoiAssets = assetSummaries.filter((item) => item.noiBaseCurrency !== null), occupancyAssets = assetSummaries.filter((item) => item.occupancyPct !== null && item.rentableAreaSqFt !== null), totalArea = occupancyAssets.reduce((sum, item) => sum + item.rentableAreaSqFt, 0), weightedOccupancy = totalArea > 0 ? occupancyAssets.reduce((sum, item) => sum + item.occupancyPct * item.rentableAreaSqFt, 0) / totalArea : null, fullRent = knownRentAssets.length === assets.length, fullNoi = knownNoiAssets.length === assets.length, fullOccupancy = occupancyAssets.length === assets.length;
  const body = { schemaVersion: PORTFOLIO_SNAPSHOT_VERSION, organizationId: state.organizationId, portfolioId, asOf, evaluatedAt, baseCurrency, status: assets.length && fullRent && fullNoi && fullOccupancy ? "complete" : assets.length ? "partial" : "insufficient-evidence", assetCount: assets.length, assets: assetSummaries, metrics: { knownMonthlyBaseRent: assets.length ? round(knownRentAssets.reduce((sum, item) => sum + item.monthlyBaseRentBaseCurrency, 0)) : null, totalMonthlyBaseRent: assets.length && fullRent ? round(knownRentAssets.reduce((sum, item) => sum + item.monthlyBaseRentBaseCurrency, 0)) : null, knownNoi: assets.length ? round(knownNoiAssets.reduce((sum, item) => sum + item.noiBaseCurrency, 0)) : null, totalNoi: assets.length && fullNoi ? round(knownNoiAssets.reduce((sum, item) => sum + item.noiBaseCurrency, 0)) : null, knownWeightedOccupancyPct: weightedOccupancy === null ? null : round(weightedOccupancy), weightedOccupancyPct: assets.length && fullOccupancy && weightedOccupancy !== null ? round(weightedOccupancy) : null }, coverage: { rentAssetCount: knownRentAssets.length, noiAssetCount: knownNoiAssets.length, occupancyAssetCount: occupancyAssets.length, totalAssetCount: assets.length }, fxRateEvidenceSha256s: [...new Set(assetSummaries.map((item) => item.fxRateEvidenceSha256).filter(Boolean))].sort() };
  return seal(body, "snapshotSha256");
}

export function evaluateAssetPlanProgress(planInput, input = {}) {
  const plan = createAssetPlan(planInput), evaluatedAt = iso(input.evaluatedAt, "evaluatedAt"), metrics = input.metrics || {}, evidence = input.evidenceByActionId || {}, actions = plan.actions.map((action) => { const observed = metrics[action.targetMetric]; const evidenceRefs = [...new Set((evidence[action.id] || []).map(String).filter((item) => item.startsWith("evidence-ref:")))]; if (!observed || observed.status !== "observed") return { actionId: action.id, status: "indeterminate", targetMetric: action.targetMetric, targetValue: action.targetValue, observedValue: null, evidenceRefs, finding: "target-metric-unknown" }; const meets = action.targetValue === null ? null : Number(observed.value) >= action.targetValue; return { actionId: action.id, status: meets === null ? "indeterminate" : meets && evidenceRefs.length ? "verified-on-track" : meets ? "evidence-missing" : "off-track", targetMetric: action.targetMetric, targetValue: action.targetValue, observedValue: Number(observed.value), evidenceRefs, finding: meets && !evidenceRefs.length ? "completion-evidence-missing" : meets ? "target-met" : "target-not-met" }; }); const body = { schemaVersion: ASSET_PLAN_PROGRESS_VERSION, organizationId: plan.organizationId, assetId: plan.assetId, planId: plan.id, planSha256: plan.planSha256, evaluatedAt, status: actions.some((item) => item.status === "off-track") ? "off-track" : actions.some((item) => ["indeterminate", "evidence-missing"].includes(item.status)) ? "partial" : "on-track", actions }; return seal(body, "progressSha256");
}
