export const CANONICAL_ACCOUNT_TAXONOMY_VERSION: "wr-canonical-real-estate-account-taxonomy-v1";
export const VENDOR_ACCOUNT_MAPPING_VERSION: "wr-vendor-account-mapping-v1";
export const CANONICAL_ACCOUNTING_RESULT_VERSION: "wr-canonical-accounting-result-v1";
export const RECONCILIATION_QUALITY_REPORT_VERSION: "wr-reconciliation-quality-report-v1";
export const PROVIDER_ONBOARDING_WORKFLOW_VERSION: "wr-provider-onboarding-workflow-v1";
export const PROVIDER_ONBOARDING_READINESS_VERSION: "wr-provider-onboarding-readiness-v1";
export const PROVIDER_INCIDENT_POLICY_VERSION: "wr-provider-incident-policy-v1";
export const PROVIDER_INCIDENT_VERSION: "wr-provider-incident-v1";
export const CERTIFICATION_LIFECYCLE_POLICY_VERSION: "wr-certification-lifecycle-policy-v1";
export const CERTIFICATION_LIFECYCLE_REPORT_VERSION: "wr-certification-lifecycle-report-v1";
export const PROVIDER_GOVERNANCE_STATE_VERSION: "wr-provider-governance-state-v1";
export const WHITE_RABBIT_ACCOUNT_TAXONOMY: Readonly<Record<string, any>>;
export function providerGovernanceSha256(value: unknown): string;
export function createCanonicalAccountTaxonomy(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createVendorAccountMappingProfile(input?: Record<string, any>): Readonly<Record<string, any>>;
export function mapVendorAccountingStatement(mapping: Record<string, any>, statement?: Record<string, any>, options?: Record<string, any>): Readonly<Record<string, any>>;
export function evaluateAccountingReconciliationQuality(result: Record<string, any>, input?: Record<string, any>): Readonly<Record<string, any>>;
export function createCanonicalStatementNormalizer(mapping: Record<string, any>, options?: Record<string, any>): Readonly<Record<string, any>>;
export function createProviderIncidentRoutingPolicy(input?: Record<string, any>): Readonly<Record<string, any>>;
export function routeProviderIncident(policy: Record<string, any>, input?: Record<string, any>, existing?: Record<string, any> | null): Readonly<Record<string, any>>;
export function createProviderOnboardingWorkflow(input?: Record<string, any>): Readonly<Record<string, any>>;
export function approveProviderOnboardingStage(workflow: Record<string, any>, stageId: string, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function evaluateProviderOnboardingReadiness(workflow: Record<string, any>, connector: Record<string, any>, options?: Record<string, any>): Readonly<Record<string, any>>;
export function createCertificationLifecyclePolicy(input?: Record<string, any>): Readonly<Record<string, any>>;
export function evaluateProviderCertificationLifecycle(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createProviderGovernanceState(input?: Record<string, any>): Readonly<Record<string, any>>;
export function acknowledgeProviderIncident(state: Record<string, any>, incidentId: string, context?: Record<string, any>): Readonly<Record<string, any>>;
export function resolveProviderIncident(state: Record<string, any>, incidentId: string, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function createDurableProviderIncidentRouter(input?: Record<string, any>): Readonly<Record<string, any>>;
