import { createHash } from "node:crypto";
import { createOperatingConnector, createOperatingMappingProfile } from "./operatingConnectorRuntime.mjs";
import { validateVendorSandboxCertificationPack } from "./operatingProviderSdk.mjs";
import { connectorAssuranceSha256 } from "./operatingConnectorAssurance.mjs";

export const CANONICAL_ACCOUNT_TAXONOMY_VERSION = "wr-canonical-real-estate-account-taxonomy-v1";
export const VENDOR_ACCOUNT_MAPPING_VERSION = "wr-vendor-account-mapping-v1";
export const CANONICAL_ACCOUNTING_RESULT_VERSION = "wr-canonical-accounting-result-v1";
export const RECONCILIATION_QUALITY_REPORT_VERSION = "wr-reconciliation-quality-report-v1";
export const PROVIDER_ONBOARDING_WORKFLOW_VERSION = "wr-provider-onboarding-workflow-v1";
export const PROVIDER_ONBOARDING_READINESS_VERSION = "wr-provider-onboarding-readiness-v1";
export const PROVIDER_INCIDENT_POLICY_VERSION = "wr-provider-incident-policy-v1";
export const PROVIDER_INCIDENT_VERSION = "wr-provider-incident-v1";
export const CERTIFICATION_LIFECYCLE_POLICY_VERSION = "wr-certification-lifecycle-policy-v1";
export const CERTIFICATION_LIFECYCLE_REPORT_VERSION = "wr-certification-lifecycle-report-v1";
export const PROVIDER_GOVERNANCE_STATE_VERSION = "wr-provider-governance-state-v1";

const DEFAULT_ACCOUNTS = Object.freeze([
  ["RENT_BASE", "Base rent", "revenue", "credit", true], ["RENT_PERCENTAGE", "Percentage rent", "revenue", "credit", true], ["RECOVERY_INCOME", "Expense recovery income", "revenue", "credit", true], ["OTHER_INCOME", "Other property income", "revenue", "credit", true],
  ["PROPERTY_TAX", "Property taxes", "operating-expense", "debit", true], ["INSURANCE", "Property insurance", "operating-expense", "debit", true], ["UTILITIES", "Utilities", "operating-expense", "debit", true], ["REPAIRS_MAINTENANCE", "Repairs and maintenance", "operating-expense", "debit", true], ["MANAGEMENT_FEE", "Property management fees", "operating-expense", "debit", true], ["PAYROLL", "Property payroll", "operating-expense", "debit", true], ["OTHER_OPEX", "Other operating expense", "operating-expense", "debit", true],
  ["CAPITAL_EXPENDITURE", "Capital expenditure", "capital", "debit", false], ["TENANT_IMPROVEMENTS", "Tenant improvements", "capital", "debit", false], ["LEASING_COMMISSIONS", "Leasing commissions", "capital", "debit", false], ["DEBT_SERVICE", "Debt service", "debt", "debit", false], ["INTEREST_EXPENSE", "Interest expense", "debt", "debit", false], ["OTHER_NON_OPERATING", "Other non-operating", "other", "debit", false],
]);
const ONBOARDING_STAGES = Object.freeze(["provider-selection", "commercial-legal", "sandbox-access", "mapping-governance", "data-quality", "security-privacy", "operations-readiness"]);
function required(value, name) { const normalized = String(value || "").trim(); if (!normalized) throw new TypeError(`${name} is required`); return normalized; }
function iso(value, name) { const date = new Date(value); if (!Number.isFinite(date.getTime())) throw new TypeError(`${name} must be a valid date`); return date.toISOString(); }
function canonicalJson(value) { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`; return JSON.stringify(value ?? null); }
export function providerGovernanceSha256(value) { return createHash("sha256").update(typeof value === "string" || Buffer.isBuffer(value) ? value : canonicalJson(value)).digest("hex"); }
function error(code, message) { const value = new Error(message); value.code = code; return value; }
function seal(input, body, field, code) { const digest = providerGovernanceSha256(body); if (input?.[field] && input[field] !== digest) throw error(code, `${field} verification failed`); return Object.freeze({ ...body, [field]: digest }); }
function evidenceRefs(values, name, allowEmpty = false) { const refs = [...new Set((values || []).map(String).filter(Boolean))].sort(); if ((!allowEmpty && !refs.length) || refs.some((item) => !item.startsWith("evidence-ref:"))) throw new TypeError(`${name} requires opaque evidence-ref values`); return refs; }
function percentage(value) { return Number(Math.max(0, Math.min(100, value)).toFixed(6)); }

export function createCanonicalAccountTaxonomy(input = {}) {
  const accountsInput = input.accounts || DEFAULT_ACCOUNTS.map(([code, name, financialClass, normalBalance, includedInNoi]) => ({ code, name, financialClass, normalBalance, includedInNoi }));
  const accounts = accountsInput.map((item) => Object.freeze({ code: required(item.code, "account.code").toUpperCase(), name: required(item.name, "account.name"), financialClass: ["revenue", "operating-expense", "capital", "debt", "other"].includes(item.financialClass) ? item.financialClass : "other", normalBalance: item.normalBalance === "credit" ? "credit" : "debit", includedInNoi: item.includedInNoi === true }));
  if (new Set(accounts.map((item) => item.code)).size !== accounts.length) throw new TypeError("Canonical account codes must be unique");
  const body = { schemaVersion: CANONICAL_ACCOUNT_TAXONOMY_VERSION, id: String(input.id || "white-rabbit-real-estate-accounts"), version: Math.max(1, Math.trunc(Number(input.version) || 1)), accounts: accounts.sort((a, b) => a.code.localeCompare(b.code)), createdAt: iso(input.createdAt || "2026-08-15T00:00:00.000Z", "createdAt") };
  return seal(input, body, "taxonomySha256", "WR_ACCOUNT_TAXONOMY_INTEGRITY_FAILURE");
}

export const WHITE_RABBIT_ACCOUNT_TAXONOMY = createCanonicalAccountTaxonomy();

export function createVendorAccountMappingProfile(input = {}) {
  const taxonomy = createCanonicalAccountTaxonomy(input.taxonomy || WHITE_RABBIT_ACCOUNT_TAXONOMY), createdAt = iso(input.createdAt, "createdAt"), approvedAt = iso(input.approvedAt, "approvedAt"), effectiveFrom = String(input.effectiveFrom || approvedAt.slice(0, 10)), effectiveTo = String(input.effectiveTo || "");
  if (!/^\d{4}-\d{2}-\d{2}$/.test(effectiveFrom) || effectiveTo && (!/^\d{4}-\d{2}-\d{2}$/.test(effectiveTo) || effectiveTo < effectiveFrom)) throw new TypeError("Mapping effective dates are invalid");
  const mappings = (input.mappings || []).map((item, index) => { const canonicalCode = required(item.canonicalCode, `mappings[${index}].canonicalCode`).toUpperCase(); if (!taxonomy.accounts.some((account) => account.code === canonicalCode)) throw new TypeError(`Unknown canonical account: ${canonicalCode}`); const multiplier = Number(item.multiplier ?? 1); if (![1, -1].includes(multiplier)) throw new TypeError("Account mapping multiplier must be 1 or -1"); return Object.freeze({ sourceAccountCode: required(item.sourceAccountCode, `mappings[${index}].sourceAccountCode`), sourceAccountName: String(item.sourceAccountName || ""), canonicalCode, multiplier, required: item.required === true }); });
  if (!mappings.length || new Set(mappings.map((item) => item.sourceAccountCode)).size !== mappings.length) throw new TypeError("Vendor account mappings require unique source account codes");
  const body = { schemaVersion: VENDOR_ACCOUNT_MAPPING_VERSION, id: required(input.id, "id"), organizationId: required(input.organizationId, "organizationId"), connectorId: required(input.connectorId, "connectorId"), providerId: required(input.providerId, "providerId"), vendorProfileId: required(input.vendorProfileId, "vendorProfileId"), version: Math.max(1, Math.trunc(Number(input.version) || 1)), taxonomyId: taxonomy.id, taxonomyVersion: taxonomy.version, taxonomySha256: taxonomy.taxonomySha256, mappings: mappings.sort((a, b) => a.sourceAccountCode.localeCompare(b.sourceAccountCode)), effectiveFrom, effectiveTo, createdByUserId: required(input.createdByUserId, "createdByUserId"), createdAt, approvedByUserId: required(input.approvedByUserId, "approvedByUserId"), approvedAt };
  if (body.createdByUserId === body.approvedByUserId) throw error("WR_ACCOUNT_MAPPING_APPROVAL_SEPARATION_REQUIRED", "Vendor account mappings require an independent approver");
  return seal(input, body, "mappingSha256", "WR_VENDOR_ACCOUNT_MAPPING_INTEGRITY_FAILURE");
}

export function mapVendorAccountingStatement(mappingInput, statement = {}, options = {}) {
  const mapping = createVendorAccountMappingProfile(mappingInput), taxonomy = createCanonicalAccountTaxonomy(options.taxonomy || WHITE_RABBIT_ACCOUNT_TAXONOMY), periodStart = required(statement.periodStart, "statement.periodStart"), periodEnd = required(statement.periodEnd, "statement.periodEnd"), asOf = required(options.asOf || periodEnd, "asOf");
  if (mapping.taxonomySha256 !== taxonomy.taxonomySha256 || mapping.taxonomyVersion !== taxonomy.version) throw error("WR_ACCOUNT_TAXONOMY_MISMATCH", "Vendor mapping does not match the canonical taxonomy");
  if (asOf < mapping.effectiveFrom || mapping.effectiveTo && asOf > mapping.effectiveTo) throw error("WR_ACCOUNT_MAPPING_NOT_EFFECTIVE", "Vendor mapping is not effective for the statement date");
  const sourceEntries = (statement.entries || []).map((item, index) => { const amount = Number(item.amount); return { sourceAccountCode: required(item.sourceAccountCode, `entries[${index}].sourceAccountCode`), sourceAccountName: String(item.sourceAccountName || ""), amount: Number.isFinite(amount) ? amount : null, status: item.status === "observed" ? "observed" : "unknown" }; });
  const mappedEntries = [], unmappedEntries = [], duplicates = [];
  const seen = new Set(); for (const entry of sourceEntries) { if (seen.has(entry.sourceAccountCode)) duplicates.push(entry.sourceAccountCode); seen.add(entry.sourceAccountCode); const rule = mapping.mappings.find((item) => item.sourceAccountCode === entry.sourceAccountCode); if (!rule || entry.status !== "observed" || !Number.isFinite(entry.amount)) { unmappedEntries.push({ ...entry, reason: !rule ? "mapping-missing" : "amount-unavailable" }); continue; } const account = taxonomy.accounts.find((item) => item.code === rule.canonicalCode), amount = entry.amount * rule.multiplier, existing = mappedEntries.find((item) => item.accountCode === account.code); if (existing) { existing.amount += amount; existing.sourceAccountCodes.push(entry.sourceAccountCode); } else mappedEntries.push({ accountCode: account.code, accountName: account.name, category: account.financialClass, status: "observed", amount, sourceField: `vendorAccounts.${entry.sourceAccountCode}`, sourceAccountCodes: [entry.sourceAccountCode], includedInNoi: account.includedInNoi }); }
  for (const entry of mappedEntries) { entry.amount = Number(entry.amount.toFixed(6)); entry.sourceAccountCodes.sort(); Object.freeze(entry); }
  const requiredSourceCodes = mapping.mappings.filter((item) => item.required).map((item) => item.sourceAccountCode), missingRequiredSourceCodes = requiredSourceCodes.filter((code) => !sourceEntries.some((item) => item.sourceAccountCode === code && item.status === "observed" && Number.isFinite(item.amount)));
  const body = { schemaVersion: CANONICAL_ACCOUNTING_RESULT_VERSION, organizationId: mapping.organizationId, connectorId: mapping.connectorId, providerId: mapping.providerId, mappingProfileId: mapping.id, mappingSha256: mapping.mappingSha256, taxonomySha256: taxonomy.taxonomySha256, sourceStatementId: required(statement.id, "statement.id"), assetId: required(statement.assetId, "statement.assetId"), periodStart, periodEnd, currency: required(statement.currency, "statement.currency"), mappedEntries: mappedEntries.sort((a, b) => a.accountCode.localeCompare(b.accountCode)), unmappedEntries, duplicateSourceAccountCodes: [...new Set(duplicates)].sort(), missingRequiredSourceCodes, sourceEntryCount: sourceEntries.length, mappedSourceEntryCount: sourceEntries.length - unmappedEntries.length, status: unmappedEntries.length || duplicates.length || missingRequiredSourceCodes.length ? "partial" : "complete" };
  return seal({}, body, "resultSha256", "WR_CANONICAL_ACCOUNTING_RESULT_INTEGRITY_FAILURE");
}

function createCanonicalAccountingResult(input = {}) { const body = { schemaVersion: CANONICAL_ACCOUNTING_RESULT_VERSION, organizationId: required(input.organizationId, "organizationId"), connectorId: required(input.connectorId, "connectorId"), providerId: required(input.providerId, "providerId"), mappingProfileId: required(input.mappingProfileId, "mappingProfileId"), mappingSha256: required(input.mappingSha256, "mappingSha256"), taxonomySha256: required(input.taxonomySha256, "taxonomySha256"), sourceStatementId: required(input.sourceStatementId, "sourceStatementId"), assetId: required(input.assetId, "assetId"), periodStart: required(input.periodStart, "periodStart"), periodEnd: required(input.periodEnd, "periodEnd"), currency: required(input.currency, "currency"), mappedEntries: structuredClone(input.mappedEntries || []), unmappedEntries: structuredClone(input.unmappedEntries || []), duplicateSourceAccountCodes: structuredClone(input.duplicateSourceAccountCodes || []), missingRequiredSourceCodes: structuredClone(input.missingRequiredSourceCodes || []), sourceEntryCount: Math.max(0, Number(input.sourceEntryCount) || 0), mappedSourceEntryCount: Math.max(0, Number(input.mappedSourceEntryCount) || 0), status: input.status === "complete" ? "complete" : "partial" }; return seal(input, body, "resultSha256", "WR_CANONICAL_ACCOUNTING_RESULT_INTEGRITY_FAILURE"); }

export function evaluateAccountingReconciliationQuality(resultInput, input = {}) {
  const result = createCanonicalAccountingResult(resultInput), evaluatedAt = iso(input.evaluatedAt, "evaluatedAt"), threshold = Math.max(0, Math.min(100, Number(input.minimumScore) || 95)), tolerance = Math.max(0, Number(input.controlTolerance) || 0.01), mappedAmount = result.mappedEntries.reduce((sum, item) => sum + Math.abs(Number(item.amount) || 0), 0), unmappedAmount = result.unmappedEntries.reduce((sum, item) => sum + Math.abs(Number(item.amount) || 0), 0), totalAmount = mappedAmount + unmappedAmount, entryCoveragePct = result.sourceEntryCount ? percentage(result.mappedSourceEntryCount / result.sourceEntryCount * 100) : 0, amountCoveragePct = totalAmount ? percentage(mappedAmount / totalAmount * 100) : result.sourceEntryCount ? 0 : 100, requiredCoveragePct = result.missingRequiredSourceCodes.length ? 0 : 100;
  const controlTotals = input.controlTotals || {}, canonicalTotals = { revenue: 0, operatingExpense: 0, noi: 0 }; for (const entry of result.mappedEntries) { if (entry.category === "revenue") canonicalTotals.revenue += entry.amount; if (entry.category === "operating-expense") canonicalTotals.operatingExpense += entry.amount; } canonicalTotals.noi = canonicalTotals.revenue - canonicalTotals.operatingExpense;
  const controlChecks = Object.entries({ revenue: controlTotals.revenue, operatingExpense: controlTotals.operatingExpense, noi: controlTotals.noi }).filter(([, value]) => Number.isFinite(Number(value))).map(([metric, expected]) => { const actual = canonicalTotals[metric], variance = actual - Number(expected); return { metric, expected: Number(expected), actual: Number(actual.toFixed(6)), variance: Number(variance.toFixed(6)), passed: Math.abs(variance) <= tolerance }; });
  const controlPct = controlChecks.length ? percentage(controlChecks.filter((item) => item.passed).length / controlChecks.length * 100) : 0, duplicatePenalty = Math.min(20, result.duplicateSourceAccountCodes.length * 5), score = percentage(entryCoveragePct * 0.3 + amountCoveragePct * 0.3 + requiredCoveragePct * 0.2 + controlPct * 0.2 - duplicatePenalty), blockers = [];
  if (score < threshold) blockers.push("score-below-threshold"); if (result.unmappedEntries.length) blockers.push("unmapped-accounts"); if (result.missingRequiredSourceCodes.length) blockers.push("required-accounts-missing"); if (result.duplicateSourceAccountCodes.length) blockers.push("duplicate-source-accounts"); if (!controlChecks.length || controlChecks.some((item) => !item.passed)) blockers.push("control-totals-not-reconciled");
  const body = { schemaVersion: RECONCILIATION_QUALITY_REPORT_VERSION, organizationId: result.organizationId, connectorId: result.connectorId, mappingProfileId: result.mappingProfileId, mappingSha256: result.mappingSha256, canonicalResultSha256: result.resultSha256, evaluatedAt, status: blockers.length ? "failed" : "passed", activationAuthorized: blockers.length === 0, score, minimumScore: threshold, metrics: { entryCoveragePct, amountCoveragePct, requiredCoveragePct, controlReconciliationPct: controlPct, duplicatePenalty }, canonicalTotals, controlChecks, blockers };
  return seal({}, body, "qualitySha256", "WR_RECONCILIATION_QUALITY_INTEGRITY_FAILURE");
}

function createQualityReport(input = {}) { const body = { schemaVersion: RECONCILIATION_QUALITY_REPORT_VERSION, organizationId: required(input.organizationId, "organizationId"), connectorId: required(input.connectorId, "connectorId"), mappingProfileId: required(input.mappingProfileId, "mappingProfileId"), mappingSha256: required(input.mappingSha256, "mappingSha256"), canonicalResultSha256: required(input.canonicalResultSha256, "canonicalResultSha256"), evaluatedAt: iso(input.evaluatedAt, "evaluatedAt"), status: input.status === "passed" ? "passed" : "failed", activationAuthorized: input.activationAuthorized === true, score: percentage(Number(input.score) || 0), minimumScore: percentage(Number(input.minimumScore) || 0), metrics: structuredClone(input.metrics || {}), canonicalTotals: structuredClone(input.canonicalTotals || {}), controlChecks: structuredClone(input.controlChecks || []), blockers: structuredClone(input.blockers || []) }; const sealed = seal(input, body, "qualitySha256", "WR_RECONCILIATION_QUALITY_INTEGRITY_FAILURE"); if (sealed.activationAuthorized !== (sealed.status === "passed" && !sealed.blockers.length && sealed.score >= sealed.minimumScore)) throw new TypeError("Quality activation authorization does not match report evidence"); return sealed; }

export function createCanonicalStatementNormalizer(mappingInput, options = {}) {
  const mapping = createVendorAccountMappingProfile(mappingInput), taxonomy = createCanonicalAccountTaxonomy(options.taxonomy || WHITE_RABBIT_ACCOUNT_TAXONOMY);
  return Object.freeze({ normalize(fields, context = {}) { const result = mapVendorAccountingStatement(mapping, { id: required(fields.statement_id || fields.id, "statement id"), assetId: required(fields.asset_id || fields.assetId, "asset id"), periodStart: required(fields.period_start || fields.periodStart, "period start"), periodEnd: required(fields.period_end || fields.periodEnd, "period end"), currency: required(fields.currency || options.currency || "USD", "currency"), entries: fields.vendor_entries || fields.entries || [] }, { taxonomy, asOf: context.asOf || fields.period_end || fields.periodEnd }); return { ...structuredClone(fields), statement_id: fields.statement_id || fields.id, asset_id: fields.asset_id || fields.assetId, period_start: fields.period_start || fields.periodStart, period_end: fields.period_end || fields.periodEnd, currency: fields.currency || options.currency || "USD", expected_accounts: result.mappedEntries.map((item) => item.accountCode), entries: result.mappedEntries.map(({ sourceAccountCodes, includedInNoi, ...entry }) => entry), canonicalAccountingResultSha256: result.resultSha256 }; } });
}

export function createProviderIncidentRoutingPolicy(input = {}) { const rules = (input.rules || []).map((item, index) => ({ codePrefix: required(item.codePrefix, `rules[${index}].codePrefix`), severity: ["critical", "high", "medium", "low"].includes(item.severity) ? item.severity : "medium", queue: required(item.queue, `rules[${index}].queue`), acknowledgeWithinMinutes: Math.max(1, Math.trunc(Number(item.acknowledgeWithinMinutes) || 30)), resolveWithinMinutes: Math.max(1, Math.trunc(Number(item.resolveWithinMinutes) || 240)) })); if (!rules.length) throw new TypeError("Provider incident policy requires routing rules"); const body = { schemaVersion: PROVIDER_INCIDENT_POLICY_VERSION, id: required(input.id, "id"), organizationId: required(input.organizationId, "organizationId"), rules, createdAt: iso(input.createdAt, "createdAt") }; return seal(input, body, "policySha256", "WR_PROVIDER_INCIDENT_POLICY_INTEGRITY_FAILURE"); }

function createProviderIncident(input = {}) { const body = { schemaVersion: PROVIDER_INCIDENT_VERSION, id: required(input.id, "id"), organizationId: required(input.organizationId, "organizationId"), connectorId: required(input.connectorId, "connectorId"), errorCode: required(input.errorCode, "errorCode"), severity: ["critical", "high", "medium", "low"].includes(input.severity) ? input.severity : "medium", queue: required(input.queue, "queue"), fingerprint: required(input.fingerprint, "fingerprint"), status: ["open", "acknowledged", "resolved"].includes(input.status) ? input.status : "open", occurrenceCount: Math.max(1, Math.trunc(Number(input.occurrenceCount) || 1)), firstOccurredAt: iso(input.firstOccurredAt, "firstOccurredAt"), lastOccurredAt: iso(input.lastOccurredAt, "lastOccurredAt"), acknowledgeBy: iso(input.acknowledgeBy, "acknowledgeBy"), resolveBy: iso(input.resolveBy, "resolveBy"), evidenceRefs: evidenceRefs(input.evidenceRefs, "incident"), acknowledgedByUserId: String(input.acknowledgedByUserId || ""), acknowledgedAt: input.acknowledgedAt ? iso(input.acknowledgedAt, "acknowledgedAt") : "", resolvedByUserId: String(input.resolvedByUserId || ""), resolvedAt: input.resolvedAt ? iso(input.resolvedAt, "resolvedAt") : "", resolutionEvidenceRefs: evidenceRefs(input.resolutionEvidenceRefs, "incident resolution", true) }; return seal(input, body, "incidentSha256", "WR_PROVIDER_INCIDENT_INTEGRITY_FAILURE"); }

export function routeProviderIncident(policyInput, input = {}, existingInput = null) {
  const policy = createProviderIncidentRoutingPolicy(policyInput), organizationId = required(input.organizationId, "organizationId"), connectorId = required(input.connectorId, "connectorId"), errorCode = required(input.errorCode, "errorCode"), occurredAt = iso(input.occurredAt, "occurredAt"); if (organizationId !== policy.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Provider incident policy tenant mismatch"); const rule = policy.rules.find((item) => errorCode.startsWith(item.codePrefix)) || policy.rules.find((item) => item.codePrefix === "*"); if (!rule) throw error("WR_PROVIDER_INCIDENT_ROUTE_MISSING", `No incident route for ${errorCode}`); const fingerprint = providerGovernanceSha256(`${organizationId}|${connectorId}|${errorCode}|${rule.queue}`), existing = existingInput ? createProviderIncident(existingInput) : null;
  if (existing && (existing.fingerprint !== fingerprint || existing.status === "resolved")) throw error("WR_PROVIDER_INCIDENT_DEDUPE_CONFLICT", "Existing incident cannot accept this occurrence");
  return createProviderIncident({ id: existing?.id || `provider_incident_${fingerprint.slice(0, 24)}`, organizationId, connectorId, errorCode, severity: rule.severity, queue: rule.queue, fingerprint, status: existing?.status || "open", occurrenceCount: (existing?.occurrenceCount || 0) + 1, firstOccurredAt: existing?.firstOccurredAt || occurredAt, lastOccurredAt: occurredAt, acknowledgeBy: existing?.acknowledgeBy || new Date(new Date(occurredAt).getTime() + rule.acknowledgeWithinMinutes * 60000).toISOString(), resolveBy: existing?.resolveBy || new Date(new Date(occurredAt).getTime() + rule.resolveWithinMinutes * 60000).toISOString(), evidenceRefs: [...(existing?.evidenceRefs || []), ...evidenceRefs(input.evidenceRefs, "incident")], acknowledgedByUserId: existing?.acknowledgedByUserId, acknowledgedAt: existing?.acknowledgedAt, resolutionEvidenceRefs: [] });
}

function onboardingStage(input = {}) { return Object.freeze({ id: required(input.id, "stage.id"), status: ["pending", "approved", "rejected"].includes(input.status) ? input.status : "pending", submittedByUserId: String(input.submittedByUserId || ""), approvedByUserId: String(input.approvedByUserId || ""), approvedAt: input.approvedAt ? iso(input.approvedAt, "stage.approvedAt") : "", expiresAt: input.expiresAt ? iso(input.expiresAt, "stage.expiresAt") : "", evidenceRefs: evidenceRefs(input.evidenceRefs, "onboarding stage", input.status !== "approved"), artifactSha256s: [...new Set((input.artifactSha256s || []).map((item) => required(item, "artifactSha256")))].sort() }); }
export function createProviderOnboardingWorkflow(input = {}) { const connector = createOperatingConnector(input.connector), stages = (input.stages || ONBOARDING_STAGES.map((id) => ({ id }))).map(onboardingStage); if (canonicalJson(stages.map((item) => item.id)) !== canonicalJson(ONBOARDING_STAGES)) throw new TypeError("Provider onboarding stages must use the required ordered sequence"); const body = { schemaVersion: PROVIDER_ONBOARDING_WORKFLOW_VERSION, id: String(input.id || `provider_onboarding_${connector.connectorId}`), organizationId: connector.organizationId, connectorId: connector.connectorId, connectorSha256: connector.connectorSha256, vendorProfileId: required(input.vendorProfileId, "vendorProfileId"), revision: Math.max(1, Math.trunc(Number(input.revision) || 1)), status: input.status === "production-ready" ? "production-ready" : "in-progress", stages, createdByUserId: required(input.createdByUserId, "createdByUserId"), createdAt: iso(input.createdAt, "createdAt"), updatedAt: iso(input.updatedAt || input.createdAt, "updatedAt") }; const ready = stages.every((item) => item.status === "approved"); if (body.status === "production-ready" && !ready) throw new TypeError("Production-ready onboarding requires every stage approved"); return seal(input, body, "workflowSha256", "WR_PROVIDER_ONBOARDING_WORKFLOW_INTEGRITY_FAILURE"); }

export function approveProviderOnboardingStage(workflowInput, stageId, input = {}, context = {}) { const workflow = createProviderOnboardingWorkflow({ ...workflowInput, connector: input.connector }), occurredAt = iso(context.occurredAt, "occurredAt"); if (context.organizationId !== workflow.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Provider onboarding tenant mismatch"); if (!(context.grants || []).includes("provider:onboarding-approve")) throw error("WR_PROVIDER_ONBOARDING_PERMISSION_DENIED", "provider:onboarding-approve grant is required"); if (Number(context.expectedRevision) !== workflow.revision) throw error("WR_REVISION_CONFLICT", "Provider onboarding revision conflict"); const index = workflow.stages.findIndex((item) => item.id === stageId); if (index < 0 || workflow.stages[index].status !== "pending") throw new TypeError(`Unknown pending onboarding stage: ${stageId}`); if (workflow.stages.slice(0, index).some((item) => item.status !== "approved" || item.expiresAt <= occurredAt)) throw error("WR_PROVIDER_ONBOARDING_DEPENDENCY_NOT_READY", "Earlier onboarding stages must be approved and unexpired"); const submittedByUserId = required(input.submittedByUserId, "submittedByUserId"), approvedByUserId = required(context.actorUserId, "context.actorUserId"); if (submittedByUserId === approvedByUserId) throw error("WR_PROVIDER_ONBOARDING_APPROVAL_SEPARATION_REQUIRED", "Onboarding submitter and approver must be different users"); const expiresAt = iso(input.expiresAt, "expiresAt"); if (expiresAt <= occurredAt) throw new TypeError("Onboarding approval expiry must follow approval");
  const artifactSha256s = [], evidence = evidenceRefs(input.evidenceRefs, "onboarding approval"); if (stageId === "mapping-governance") { const mapping = createVendorAccountMappingProfile(input.mappingProfile); if (mapping.organizationId !== workflow.organizationId || mapping.connectorId !== workflow.connectorId) throw error("WR_PROVIDER_ONBOARDING_ARTIFACT_MISMATCH", "Account mapping does not match onboarding scope"); artifactSha256s.push(mapping.mappingSha256); } if (stageId === "data-quality") { const quality = createQualityReport(input.qualityReport); if (!quality.activationAuthorized || quality.organizationId !== workflow.organizationId || quality.connectorId !== workflow.connectorId) throw error("WR_PROVIDER_ONBOARDING_QUALITY_FAILED", "Passing reconciliation quality is required"); artifactSha256s.push(quality.qualitySha256); } if (stageId === "security-privacy") { const pack = validateVendorSandboxCertificationPack(input.vendorPack); if (!pack.activationAuthorized || pack.organizationId !== workflow.organizationId || pack.connectorId !== workflow.connectorId) throw error("WR_PROVIDER_ONBOARDING_VENDOR_CERTIFICATION_FAILED", "Certified vendor sandbox evidence is required"); artifactSha256s.push(pack.packSha256); } if (stageId === "operations-readiness") { const lifecycle = createCertificationLifecycleReport(input.lifecycleReport); if (lifecycle.status !== "current" || lifecycle.organizationId !== workflow.organizationId || lifecycle.connectorId !== workflow.connectorId) throw error("WR_PROVIDER_ONBOARDING_LIFECYCLE_NOT_CURRENT", "Current certification lifecycle evidence is required"); artifactSha256s.push(lifecycle.reportSha256); }
  const stages = workflow.stages.map((item, currentIndex) => currentIndex === index ? onboardingStage({ ...item, status: input.decision === "rejected" ? "rejected" : "approved", submittedByUserId, approvedByUserId, approvedAt: occurredAt, expiresAt, evidenceRefs: evidence, artifactSha256s }) : item), status = stages.every((item) => item.status === "approved") ? "production-ready" : "in-progress"; return createProviderOnboardingWorkflow({ ...workflow, connector: input.connector, workflowSha256: undefined, revision: workflow.revision + 1, status, stages, updatedAt: occurredAt }); }

export function evaluateProviderOnboardingReadiness(workflowInput, connectorInput, options = {}) { const workflow = createProviderOnboardingWorkflow({ ...workflowInput, connector: connectorInput }), evaluatedAt = iso(options.evaluatedAt, "evaluatedAt"), expiredStageIds = workflow.stages.filter((item) => item.status === "approved" && item.expiresAt <= evaluatedAt).map((item) => item.id), unapprovedStageIds = workflow.stages.filter((item) => item.status !== "approved").map((item) => item.id), status = !unapprovedStageIds.length && !expiredStageIds.length ? "production-ready" : expiredStageIds.length ? "suspended" : "in-progress", body = { schemaVersion: PROVIDER_ONBOARDING_READINESS_VERSION, organizationId: workflow.organizationId, connectorId: workflow.connectorId, workflowId: workflow.id, workflowSha256: workflow.workflowSha256, evaluatedAt, status, activationAuthorized: status === "production-ready", expiredStageIds, unapprovedStageIds }; return seal({}, body, "readinessSha256", "WR_PROVIDER_ONBOARDING_READINESS_INTEGRITY_FAILURE"); }

export function createCertificationLifecyclePolicy(input = {}) { return Object.freeze({ schemaVersion: CERTIFICATION_LIFECYCLE_POLICY_VERSION, adapterMaximumAgeDays: Math.max(1, Number(input.adapterMaximumAgeDays) || 30), vendorPackMaximumAgeDays: Math.max(1, Number(input.vendorPackMaximumAgeDays) || 90), mappingMaximumAgeDays: Math.max(1, Number(input.mappingMaximumAgeDays) || 180), qualityMaximumAgeDays: Math.max(1, Number(input.qualityMaximumAgeDays) || 30), drillMaximumAgeDays: Math.max(1, Number(input.drillMaximumAgeDays) || 30), sloMaximumAgeDays: Math.max(1, Number(input.sloMaximumAgeDays) || 7), warningDays: Math.max(0, Number(input.warningDays) || 7) }); }
function sealedIntegrity(value, field, hash, code) { if (!value?.[field]) return false; const { [field]: ignored, ...body } = value; return hash(body) === value[field]; }
function artifactStatus(id, observedAt, maximumAgeDays, evaluatedAt, passing) { const observed = new Date(observedAt), evaluated = new Date(evaluatedAt), valid = Number.isFinite(observed.getTime()), ageDays = valid ? (evaluated - observed) / 86400000 : Number.POSITIVE_INFINITY, remainingDays = valid ? maximumAgeDays - ageDays : Number.NEGATIVE_INFINITY, status = !passing || !valid || ageDays < 0 || remainingDays < 0 ? "expired" : "current"; return { id, observedAt: String(observedAt || ""), maximumAgeDays, ageDays: Number.isFinite(ageDays) ? Number(ageDays.toFixed(6)) : null, remainingDays: Number.isFinite(remainingDays) ? Number(remainingDays.toFixed(6)) : null, status }; }
export function evaluateProviderCertificationLifecycle(input = {}) { const connector = createOperatingConnector(input.connector), adapter = input.adapterCertification || {}, vendorPack = validateVendorSandboxCertificationPack(input.vendorPack), mapping = createVendorAccountMappingProfile(input.mappingProfile), quality = createQualityReport(input.qualityReport), drill = input.drillResult || {}, slo = input.sloReport || {}, evaluatedAt = iso(input.evaluatedAt, "evaluatedAt"), policy = createCertificationLifecyclePolicy(input.policy), adapterValid = sealedIntegrity(adapter, "certificationSha256", connectorAssuranceSha256), drillValid = sealedIntegrity(drill, "resultSha256", connectorAssuranceSha256), artifacts = [artifactStatus("adapter-certification", adapter.certifiedAt, policy.adapterMaximumAgeDays, evaluatedAt, adapterValid && adapter.status === "certified" && adapter.activationAuthorized === true && adapter.organizationId === connector.organizationId && adapter.connectorSha256 === connector.connectorSha256), artifactStatus("vendor-pack", vendorPack.evaluatedAt, policy.vendorPackMaximumAgeDays, evaluatedAt, vendorPack.activationAuthorized === true && vendorPack.organizationId === connector.organizationId && vendorPack.connectorSha256 === connector.connectorSha256), artifactStatus("account-mapping", mapping.approvedAt, policy.mappingMaximumAgeDays, evaluatedAt, mapping.organizationId === connector.organizationId && mapping.connectorId === connector.connectorId && mapping.providerId === connector.providerId), artifactStatus("reconciliation-quality", quality.evaluatedAt, policy.qualityMaximumAgeDays, evaluatedAt, quality.activationAuthorized === true && quality.organizationId === connector.organizationId && quality.connectorId === connector.connectorId && quality.mappingSha256 === mapping.mappingSha256), artifactStatus("resilience-drill", drill.completedAt, policy.drillMaximumAgeDays, evaluatedAt, drillValid && drill.status === "passed" && drill.organizationId === connector.organizationId && drill.connectorId === connector.connectorId), artifactStatus("connector-slo", slo.evaluatedAt, policy.sloMaximumAgeDays, evaluatedAt, slo.status === "passed" && slo.organizationId === connector.organizationId && slo.serviceName === "operating-connector")], expired = artifacts.filter((item) => item.status === "expired"), warning = artifacts.filter((item) => item.status === "current" && item.remainingDays <= policy.warningDays), status = expired.length ? "suspended" : warning.length ? "warning" : "current";
  const body = { schemaVersion: CERTIFICATION_LIFECYCLE_REPORT_VERSION, organizationId: connector.organizationId, connectorId: connector.connectorId, connectorSha256: connector.connectorSha256, evaluatedAt, status, activationAuthorized: status === "current", artifacts, blockers: expired.map((item) => item.id), warnings: warning.map((item) => item.id), policy };
  return seal({}, body, "reportSha256", "WR_CERTIFICATION_LIFECYCLE_INTEGRITY_FAILURE"); }
function createCertificationLifecycleReport(input = {}) { const body = { schemaVersion: CERTIFICATION_LIFECYCLE_REPORT_VERSION, organizationId: required(input.organizationId, "organizationId"), connectorId: required(input.connectorId, "connectorId"), connectorSha256: required(input.connectorSha256, "connectorSha256"), evaluatedAt: iso(input.evaluatedAt, "evaluatedAt"), status: ["current", "warning", "suspended"].includes(input.status) ? input.status : "suspended", activationAuthorized: input.activationAuthorized === true, artifacts: structuredClone(input.artifacts || []), blockers: structuredClone(input.blockers || []), warnings: structuredClone(input.warnings || []), policy: createCertificationLifecyclePolicy(input.policy) }; if (body.activationAuthorized !== (body.status === "current" && !body.blockers.length)) throw new TypeError("Lifecycle activation authorization does not match report"); return seal(input, body, "reportSha256", "WR_CERTIFICATION_LIFECYCLE_INTEGRITY_FAILURE"); }

export function createProviderGovernanceState(input = {}) { const organizationId = required(input.organizationId, "organizationId"), onboardingWorkflows = (input.onboardingWorkflows || []).map((item) => createProviderOnboardingWorkflow({ ...item, connector: (input.connectors || []).find((connector) => connector.connectorId === item.connectorId) || item.connector })), incidents = (input.incidents || []).map(createProviderIncident), lifecycleReports = (input.lifecycleReports || []).map(createCertificationLifecycleReport), accountMappings = (input.accountMappings || []).map(createVendorAccountMappingProfile), qualityReports = (input.qualityReports || []).map(createQualityReport); for (const item of [...onboardingWorkflows, ...incidents, ...lifecycleReports, ...accountMappings, ...qualityReports]) if (item.organizationId !== organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Provider governance records must share one tenant"); for (const collection of [onboardingWorkflows, incidents, accountMappings]) if (new Set(collection.map((item) => item.id)).size !== collection.length) throw new TypeError("Provider governance IDs must be unique"); const body = { schemaVersion: PROVIDER_GOVERNANCE_STATE_VERSION, organizationId, revision: Math.max(1, Math.trunc(Number(input.revision) || 1)), connectors: (input.connectors || []).map(createOperatingConnector), onboardingWorkflows, incidents, lifecycleReports, accountMappings, qualityReports, updatedAt: iso(input.updatedAt, "updatedAt") }; return seal(input, body, "stateSha256", "WR_PROVIDER_GOVERNANCE_STATE_INTEGRITY_FAILURE"); }

function incidentMutation(stateInput, incidentId, context, status, evidence) { const state = createProviderGovernanceState(stateInput), occurredAt = iso(context.occurredAt, "occurredAt"); if (context.organizationId !== state.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Provider incident mutation tenant mismatch"); if (!(context.grants || []).includes("provider:incident-manage")) throw error("WR_PROVIDER_INCIDENT_PERMISSION_DENIED", "provider:incident-manage grant is required"); if (Number(context.expectedRevision) !== state.revision) throw error("WR_REVISION_CONFLICT", "Provider governance revision conflict"); const incident = state.incidents.find((item) => item.id === incidentId); if (!incident || incident.status === "resolved" || status === "resolved" && incident.status !== "acknowledged") throw error("WR_PROVIDER_INCIDENT_TRANSITION_INVALID", "Provider incident transition is invalid"); const actor = required(context.actorUserId, "actorUserId"), updated = createProviderIncident({ ...incident, incidentSha256: undefined, status, acknowledgedByUserId: status === "acknowledged" ? actor : incident.acknowledgedByUserId, acknowledgedAt: status === "acknowledged" ? occurredAt : incident.acknowledgedAt, resolvedByUserId: status === "resolved" ? actor : "", resolvedAt: status === "resolved" ? occurredAt : "", resolutionEvidenceRefs: status === "resolved" ? evidenceRefs(evidence, "incident resolution") : incident.resolutionEvidenceRefs }); return createProviderGovernanceState({ ...state, stateSha256: undefined, revision: state.revision + 1, incidents: state.incidents.map((item) => item.id === incident.id ? updated : item), updatedAt: occurredAt }); }
export function acknowledgeProviderIncident(state, incidentId, context = {}) { return incidentMutation(state, incidentId, context, "acknowledged", []); }
export function resolveProviderIncident(state, incidentId, input = {}, context = {}) { return incidentMutation(state, incidentId, context, "resolved", input.evidenceRefs); }

export function createDurableProviderIncidentRouter({ repository, context, policy: policyInput } = {}) { if (!repository?.readRecord || !repository?.commit) throw new TypeError("A durable repository is required"); const policy = createProviderIncidentRoutingPolicy(policyInput); return Object.freeze({ record(input = {}, options = {}) { const occurredAt = iso(input.occurredAt, "occurredAt"), stored = repository.readRecord(context, "operating-feed", "provider-governance-state", { now: occurredAt }), connector = createOperatingConnector(input.connector), state = stored?.value ? createProviderGovernanceState(stored.value) : createProviderGovernanceState({ organizationId: context.organizationId, connectors: [connector], updatedAt: occurredAt }); if (state.organizationId !== connector.organizationId || connector.organizationId !== context.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Incident router connector tenant mismatch"); const fingerprint = providerGovernanceSha256(`${context.organizationId}|${connector.connectorId}|${input.errorCode}|${(policy.rules.find((item) => String(input.errorCode).startsWith(item.codePrefix)) || policy.rules.find((item) => item.codePrefix === "*"))?.queue || ""}`), existing = state.incidents.find((item) => item.fingerprint === fingerprint && item.status !== "resolved"), incident = routeProviderIncident(policy, { organizationId: context.organizationId, connectorId: connector.connectorId, errorCode: input.errorCode, occurredAt, evidenceRefs: input.evidenceRefs }, existing), connectors = state.connectors.some((item) => item.connectorId === connector.connectorId) ? state.connectors : [...state.connectors, connector], next = createProviderGovernanceState({ ...state, stateSha256: undefined, revision: state.revision + 1, connectors, incidents: existing ? state.incidents.map((item) => item.id === existing.id ? incident : item) : [...state.incidents, incident], updatedAt: occurredAt }), receipt = repository.commit({ context, namespace: "operating-feed", key: "provider-governance-state", value: next, expectedTenantRevision: options.expectedTenantRevision, expectedRecordRevision: Number(stored?.revision || 0), idempotencyKey: options.idempotencyKey || `provider-incident:${incident.incidentSha256}`, occurredAt }, { now: occurredAt }); return { incident, state: next, receipt, tenantRevision: receipt.tenantRevision }; } }); }
