export const PLATFORM_PERSISTENCE_SERVICE_VERSION: "wr-platform-persistence-service-v1";
export function persistUserIntelligenceState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadUserIntelligenceState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistCollaborationState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadCollaborationState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistAlertRoutingState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadAlertRoutingState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistPropertySnapshot(repository: Record<string, unknown>, context: Record<string, unknown>, snapshotInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function listPropertySnapshots(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Array<Record<string, unknown>>;
export function persistDeliveryAttempt(repository: Record<string, unknown>, context: Record<string, unknown>, attemptInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function listDeliveryAttempts(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Array<Record<string, unknown>>;
export function persistAlertWorkerState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadAlertWorkerState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistUnderwritingGovernanceState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadUnderwritingGovernanceState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistDealRoomState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadDealRoomState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistDocumentEvidenceState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadDocumentEvidenceState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistDiligenceWorkflow(repository: Record<string, unknown>, context: Record<string, unknown>, workflowInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadDiligenceWorkflow(repository: Record<string, unknown>, context: Record<string, unknown>, workflowId: string, options?: Record<string, unknown>): Record<string, unknown> | null;
export function listDiligenceWorkflows(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function persistAssetOperationsState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadAssetOperationsState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistForwardStrategyState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadForwardStrategyState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistOperatingControlState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadOperatingControlState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistOperatingConnectorWorkerState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadOperatingConnectorWorkerState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistConnectorAssuranceState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadConnectorAssuranceState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistProviderExecutionState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadProviderExecutionState(repository: Record<string, unknown>, context: Record<string, unknown>, connectorId: string, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistVendorSandboxCertificationPack(repository: Record<string, unknown>, context: Record<string, unknown>, packInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadVendorSandboxCertificationPack(repository: Record<string, unknown>, context: Record<string, unknown>, packId: string, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistProviderGovernanceState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadProviderGovernanceState(repository: Record<string, unknown>, context: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown> | null;
export function persistCountyReleaseState(repository: Record<string, unknown>, context: Record<string, unknown>, stateInput: Record<string, unknown>, options?: Record<string, unknown>): Record<string, unknown>;
export function loadCountyReleaseState(repository: Record<string, unknown>, context: Record<string, unknown>, countyId: string, options?: Record<string, unknown>): Record<string, unknown> | null;
