import { Bot, CheckCircle2, LockKeyhole, Network, ShieldCheck } from "lucide-react";
import { HUMAN_APPROVAL_ACTIONS, SAVANT_ORCHESTRATOR_VERSION, SAVANT_SPECIALISTS } from "../agents/savantOrchestrator.mjs";

export default function AgentControlCenter() {
  return <section className="p-4 sm:p-6" data-savant-agent-control-center="true">
    <div className="rounded-xl border border-cyan-200 bg-gradient-to-r from-cyan-50 to-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-cyan-600 text-white"><Network size={21} /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-cyan-700">Master coordination layer</p><h2 className="mt-1 text-lg font-semibold">Savant Orchestrator</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-600">Routes platform events to specialist agents, maintains dependencies and audit records, and stops external or material actions until a member approves them.</p></div></div><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-100 px-3 py-1.5 text-[10px] font-bold text-emerald-700"><CheckCircle2 size={12} /> Architecture locked</span></div><p className="mt-4 text-[9px] font-mono text-slate-400">{SAVANT_ORCHESTRATOR_VERSION}</p></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-3">{SAVANT_SPECIALISTS.map((agent) => <article key={agent.id as string} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-slate-700"><Bot size={18} /></span><span className="rounded-full bg-cyan-50 px-2 py-1 text-[9px] font-bold uppercase text-cyan-700">Specialist</span></div><h3 className="mt-3 text-sm font-bold">{agent.name as string}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{agent.purpose as string}</p><div className="mt-3 border-t border-slate-100 pt-3"><p className="text-[9px] font-bold uppercase tracking-wide text-slate-400">Listens for</p><p className="mt-1 text-[10px] font-mono text-slate-600">{(agent.eventTypes as string[]).join(" · ")}</p></div></article>)}</div>
    <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4" data-savant-human-approval-gate="true"><div className="flex items-start gap-3"><ShieldCheck size={20} className="mt-0.5 shrink-0 text-amber-700" /><div><h3 className="text-sm font-bold text-amber-950">Human approval gate</h3><p className="mt-1 text-xs leading-5 text-amber-900">Agents may analyze, prioritize, draft, and propose. A member must approve publishing, communications, spending, deletion, equation changes, and production-code changes.</p><div className="mt-3 flex flex-wrap gap-1.5">{HUMAN_APPROVAL_ACTIONS.map((action) => <span key={action} className="inline-flex items-center gap-1 rounded-full border border-amber-200 bg-white px-2 py-1 text-[9px] font-semibold text-amber-800"><LockKeyhole size={10} />{action}</span>)}</div></div></div></div>
  </section>;
}
