import { useEffect, useMemo, useState } from "react";
import { Building2, MessageSquare, Plus, Search, Send, UserSearch, X } from "lucide-react";
import { createExchangePost, createMemberMessage, findMemberMatches } from "../collaboration/memberExchange.mjs";

const STORAGE_KEY = "real-estate-savant:member-exchange:v1";
type ExchangePost = { id: string; kind: "listing" | "buyer-need"; memberId: string; memberName: string; title: string; propertyType: string; market: string; price: number; minPrice: number; maxPrice: number; details: string; createdAt: string; status: string };
type ExchangeMessage = { id: string; threadId: string; authorMemberId: string; authorName: string; body: string; createdAt: string };
type DirectThread = { id: string; memberName: string; createdAt: string };
type ExchangeState = { posts: ExchangePost[]; messages: ExchangeMessage[]; directThreads: DirectThread[] };
type PostDraft = { kind: "listing" | "buyer-need"; title: string; propertyType: string; market: string; price: string; minPrice: string; maxPrice: string; details: string };
const EMPTY_POST: PostDraft = { kind: "listing", title: "", propertyType: "", market: "", price: "", minPrice: "", maxPrice: "", details: "" };

function loadState(): ExchangeState {
  try { const value = JSON.parse(window.localStorage.getItem(STORAGE_KEY) || "{}"); return { posts: Array.isArray(value.posts) ? value.posts : [], messages: Array.isArray(value.messages) ? value.messages : [], directThreads: Array.isArray(value.directThreads) ? value.directThreads : [] }; } catch { return { posts: [], messages: [], directThreads: [] }; }
}
function currency(value: number) { return value ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value) : "Price not provided"; }

export default function MemberExchange() {
  const [state, setState] = useState<ExchangeState>(loadState);
  const [memberName, setMemberName] = useState("Current member");
  const [showPost, setShowPost] = useState(false);
  const [draft, setDraft] = useState<PostDraft>(EMPTY_POST);
  const [activeThread, setActiveThread] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const [recipient, setRecipient] = useState("");
  useEffect(() => { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [state]);
  const matches = useMemo(() => findMemberMatches(state.posts), [state.posts]);
  const selectedMatch = matches.find((match) => match.id === activeThread);
  const selectedDirect = state.directThreads.find((thread) => thread.id === activeThread);
  const threadMessages = state.messages.filter((item) => item.threadId === activeThread);
  const post = (event: React.FormEvent) => {
    event.preventDefault();
    const normalizedName = memberName.trim();
    if (!normalizedName || !draft.title.trim()) return;
    const record = createExchangePost({ ...draft, memberId: normalizedName.toLowerCase().replace(/[^a-z0-9]+/g, "-"), memberName: normalizedName });
    setState((current) => ({ ...current, posts: [record as ExchangePost, ...current.posts] })); setDraft(EMPTY_POST); setShowPost(false);
  };
  const send = (event: React.FormEvent) => {
    event.preventDefault();
    if (!activeThread || !message.trim() || !memberName.trim()) return;
    const record = createMemberMessage({ threadId: activeThread, authorMemberId: memberName.toLowerCase().replace(/[^a-z0-9]+/g, "-"), authorName: memberName, body: message });
    setState((current) => ({ ...current, messages: [...current.messages, record as ExchangeMessage] })); setMessage("");
  };
  const startDirectConversation = (event: React.FormEvent) => {
    event.preventDefault();
    const name = recipient.trim();
    if (!name || !memberName.trim()) return;
    const participants = [memberName, name].map((value) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-")).sort();
    const id = `direct:${participants.join(":")}`;
    setState((current) => current.directThreads.some((thread) => thread.id === id) ? current : { ...current, directThreads: [{ id, memberName: name, createdAt: new Date().toISOString() }, ...current.directThreads] });
    setActiveThread(id); setRecipient("");
  };
  return <section className="p-4 sm:p-6" data-crm-member-exchange="true">
    <div className="rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-xs text-violet-950"><strong>Member Exchange preview:</strong> posts and conversations are stored on this device. Secure cross-member syncing will activate with the production member account service.</div>
    <div className="mt-4 flex flex-wrap items-end justify-between gap-3"><label><span className="block text-[10px] font-bold uppercase tracking-wide text-slate-500">Posting as</span><input value={memberName} onChange={(event) => setMemberName(event.target.value)} className="mt-1.5 h-9 rounded-md border border-slate-300 bg-white px-3 text-xs" /></label><button type="button" onClick={() => setShowPost(true)} className="inline-flex items-center gap-2 rounded-md bg-cyan-600 px-3 py-2 text-xs font-semibold text-white"><Plus size={14} /> Post listing or buyer need</button></div>
    <div className="mt-5 rounded-xl border border-cyan-200 bg-white p-4 shadow-sm" data-member-direct-chat="true"><div className="flex items-center gap-2"><MessageSquare size={17} className="text-cyan-600" /><div><h2 className="text-sm font-bold">Talk to a member or real estate agent</h2><p className="mt-0.5 text-[10px] text-slate-500">Enter their name or email and start talking.</p></div></div><form onSubmit={startDirectConversation} className="mt-3 flex flex-col gap-2 sm:flex-row"><label className="relative min-w-0 flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="Member or agent name or email" className="h-11 w-full rounded-md border border-slate-300 pl-9 pr-3 text-sm outline-none focus:border-cyan-500" aria-label="Find a member or real estate agent" /></label><button type="submit" disabled={!recipient.trim()} className="rounded-md bg-cyan-600 px-5 py-2 text-sm font-semibold text-white disabled:opacity-40">Start conversation</button></form>{state.directThreads.length > 0 && <div className="mt-4 border-t border-slate-100 pt-3"><p className="text-[9px] font-bold uppercase tracking-wide text-slate-400">Recent conversations</p><div className="mt-2 flex flex-wrap gap-2">{state.directThreads.map((thread) => <button key={thread.id} type="button" onClick={() => setActiveThread(thread.id)} className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:border-cyan-300 hover:bg-cyan-50"><MessageSquare size={12} />{thread.memberName}</button>)}</div></div>}</div>
    <div className="mt-5 grid gap-4 lg:grid-cols-3">
      <div className="lg:col-span-2"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">Listing and buyer matches</h2><span className="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-700">{matches.length} matches</span></div><div className="mt-3 space-y-3">{matches.map((match) => <article key={match.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2"><div><p className="text-[9px] font-bold uppercase text-cyan-700">Listing · {match.listing.memberName}</p><p className="mt-1 text-sm font-semibold">{match.listing.title}</p><p className="mt-1 text-xs text-slate-500">{match.listing.propertyType} · {match.listing.market} · {currency(match.listing.price)}</p></div><div><p className="text-[9px] font-bold uppercase text-violet-700">Buyer need · {match.buyerNeed.memberName}</p><p className="mt-1 text-sm font-semibold">{match.buyerNeed.title}</p><p className="mt-1 text-xs text-slate-500">{match.buyerNeed.propertyType} · {match.buyerNeed.market}</p></div></div><button type="button" onClick={() => setActiveThread(match.id)} className="mt-3 inline-flex items-center gap-1.5 rounded-md border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50"><MessageSquare size={13} /> Message members</button></article>)}{!matches.length && <div className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><UserSearch size={25} className="mx-auto text-slate-300" /><p className="mt-3 text-sm font-semibold text-slate-700">No member matches yet</p><p className="mt-1 text-xs text-slate-400">Post listings and buyer requirements. Compatible property type, market, and price ranges will match automatically.</p></div>}</div></div>
      <div><h2 className="text-sm font-bold">Exchange activity</h2><div className="mt-3 space-y-2">{state.posts.map((item) => <article key={item.id} className="rounded-lg border border-slate-200 bg-white p-3"><div className="flex items-center gap-2">{item.kind === "listing" ? <Building2 size={14} className="text-cyan-600" /> : <UserSearch size={14} className="text-violet-600" />}<p className="text-[9px] font-bold uppercase text-slate-400">{item.kind === "listing" ? "Listing" : "Buyer need"}</p></div><p className="mt-2 text-xs font-semibold">{item.title}</p><p className="mt-1 text-[10px] text-slate-500">{item.memberName} · {item.market || "Any market"}</p></article>)}{!state.posts.length && <p className="rounded-lg border border-dashed border-slate-300 p-5 text-center text-xs text-slate-400">No posts yet.</p>}</div></div>
    </div>
    {showPost && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 p-4"><form onSubmit={post} className="w-full max-w-xl rounded-xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Post to Member Exchange</h2><button type="button" onClick={() => setShowPost(false)} aria-label="Close" className="p-2"><X size={18} /></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="text-[10px] font-bold uppercase text-slate-500">Post type</span><select value={draft.kind} onChange={(event) => setDraft((current) => ({ ...current, kind: event.target.value as "listing" | "buyer-need" }))} className="mt-1 h-10 w-full rounded border border-slate-300 px-3 text-xs"><option value="listing">Listing for sale</option><option value="buyer-need">Buyer need</option></select></label>{[["title", "Title"], ["propertyType", "Property type"], ["market", "Market / county"], ["price", "Listing price"], ["minPrice", "Buyer minimum"], ["maxPrice", "Buyer maximum"]].map(([key, label]) => <label key={key}><span className="text-[10px] font-bold uppercase text-slate-500">{label}</span><input value={String(draft[key as keyof typeof draft])} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.target.value }))} className="mt-1 h-10 w-full rounded border border-slate-300 px-3 text-xs" /></label>)}<label className="sm:col-span-2"><span className="text-[10px] font-bold uppercase text-slate-500">Details</span><textarea value={draft.details} onChange={(event) => setDraft((current) => ({ ...current, details: event.target.value }))} className="mt-1 min-h-24 w-full rounded border border-slate-300 p-3 text-xs" /></label></div><button type="submit" className="mt-4 w-full rounded-md bg-cyan-600 py-2.5 text-xs font-semibold text-white">Publish to members</button></form></div>}
    {activeThread && (selectedMatch || selectedDirect) && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/45" onMouseDown={(event) => { if (event.target === event.currentTarget) setActiveThread(null); }}><aside className="flex h-full w-full max-w-md flex-col bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-4"><div><p className="text-[9px] font-bold uppercase text-cyan-700">{selectedDirect ? "Direct conversation" : "Private match conversation"}</p><h2 className="mt-1 text-sm font-semibold">{selectedDirect ? selectedDirect.memberName : `${selectedMatch.listing.memberName} + ${selectedMatch.buyerNeed.memberName}`}</h2></div><button type="button" onClick={() => setActiveThread(null)} aria-label="Close conversation"><X size={18} /></button></div><div className="flex-1 space-y-3 overflow-y-auto p-4">{threadMessages.map((item) => <div key={item.id} className="rounded-lg bg-slate-100 p-3"><p className="text-[9px] font-bold text-cyan-700">{item.authorName}</p><p className="mt-1 text-xs text-slate-700">{item.body}</p></div>)}{!threadMessages.length && <p className="py-10 text-center text-xs text-slate-400">Send the first message to start this conversation.</p>}</div><form onSubmit={send} className="flex gap-2 border-t p-4"><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Type a message" className="h-10 min-w-0 flex-1 rounded-md border border-slate-300 px-3 text-xs" /><button type="submit" aria-label="Send message" className="flex h-10 w-10 items-center justify-center rounded-md bg-cyan-600 text-white"><Send size={15} /></button></form></aside></div>}
  </section>;
}
