export const DEAL_ROOM_VERSION: "wr-deal-room-v1";
export const DEAL_ROOM_DOCUMENT_VERSION: "wr-deal-room-document-version-v1";
export const MALWARE_SCAN_EVIDENCE_VERSION: "wr-malware-scan-evidence-v1";
export const DEAL_ROOM_SHARE_VERSION: "wr-deal-room-share-v1";
export const DEAL_ROOM_LEGAL_HOLD_VERSION: "wr-deal-room-legal-hold-v1";
export const DEAL_ROOM_ACCESS_EVENT_VERSION: "wr-deal-room-access-event-v1";
export const DEAL_ROOM_DELETION_REQUEST_VERSION: "wr-deal-room-deletion-request-v1";
export const DEAL_ROOM_STATE_VERSION: "wr-deal-room-state-v1";
export const DOCUMENT_CLASSIFICATIONS: readonly string[];
export const MALWARE_SCAN_RESULTS: readonly string[];
export function dealRoomSha256(value: unknown): string;
export function createDealRoom(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createMalwareScanEvidence(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createDealRoomDocumentVersion(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createExpiringDealRoomShare(input?: Record<string, any>, options?: Record<string, any>): Readonly<Record<string, any>>;
export function createLegalHold(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createDealRoomState(input?: Record<string, any>): Record<string, any>;
export function addDealRoom(state: Record<string, any>, room: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function addDealRoomDocumentVersion(state: Record<string, any>, version: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function addDealRoomShare(state: Record<string, any>, share: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function revokeDealRoomShare(state: Record<string, any>, shareId: string, context?: Record<string, any>): Record<string, any>;
export function addLegalHold(state: Record<string, any>, hold: Record<string, any>, context?: Record<string, any>): Record<string, any>;
export function releaseLegalHold(state: Record<string, any>, holdId: string, context?: Record<string, any>): Record<string, any>;
export function requestDocumentDeletion(state: Record<string, any>, documentId: string, context?: Record<string, any>): Record<string, any>;
export function evaluateSharedDocumentAccess(state: Record<string, any>, input?: Record<string, any>): Readonly<Record<string, any>>;
