import { createDiligenceWorkflow, diligenceSha256 } from "./transactionDiligence.mjs";

export const DILIGENCE_REMINDER_JOB_VERSION = "wr-diligence-reminder-job-v1";
export const DILIGENCE_REMINDER_WORKER_STATE_VERSION = "wr-diligence-reminder-worker-state-v1";
export const DILIGENCE_REMINDER_WORKER_CYCLE_VERSION = "wr-diligence-reminder-worker-cycle-v1";
export const DILIGENCE_REMINDER_DEAD_LETTER_VERSION = "wr-diligence-reminder-dead-letter-v1";
export const DILIGENCE_REMINDER_RUN_VERSION = "wr-diligence-reminder-run-v1";

const JOB_STATUSES = Object.freeze(["queued", "leased", "retry-scheduled", "emitted", "dead-lettered", "cancelled"]);
function required(value, name) { const normalized = String(value || "").trim(); if (!normalized) throw new TypeError(`${name} is required`); return normalized; }
function iso(value, name) { const date = new Date(value); if (!Number.isFinite(date.getTime())) throw new TypeError(`${name} must be a valid date`); return date.toISOString(); }
function stableId(prefix, seed) { return `${prefix}_${diligenceSha256(seed).slice(0, 24)}`; }
function error(code, message) { const value = new Error(message); value.code = code; return value; }
function opaque(value, name, prefix) { const normalized = required(value, name); if (!normalized.startsWith(prefix)) throw new TypeError(`${name} must be an opaque ${prefix} reference`); return normalized; }
function normalizeLease(value) { if (!value) return null; return Object.freeze({ token: required(value.token, "lease.token"), workerId: required(value.workerId, "lease.workerId"), leasedAt: iso(value.leasedAt, "lease.leasedAt"), expiresAt: iso(value.expiresAt, "lease.expiresAt") }); }

export function createDiligenceReminderJob(input = {}) {
  const organizationId = required(input.organizationId, "organizationId"), workflowId = required(input.workflowId, "workflowId"), taskId = required(input.taskId, "taskId"), kind = input.kind === "escalation" ? "escalation" : "reminder", scheduledAt = iso(input.scheduledAt, "scheduledAt"), createdAt = iso(input.createdAt, "createdAt");
  return {
    schemaVersion: DILIGENCE_REMINDER_JOB_VERSION,
    id: String(input.id || stableId("diligence_reminder", `${organizationId}|${workflowId}|${taskId}|${kind}|${scheduledAt}`)),
    organizationId, workflowId, workflowSha256: required(input.workflowSha256, "workflowSha256"), taskId, kind, scheduledAt,
    recipientRef: opaque(input.recipientRef, "recipientRef", "recipient-ref:"), subscriptionId: required(input.subscriptionId, "subscriptionId"),
    channelType: ["in-app", "email", "webhook"].includes(input.channelType) ? input.channelType : "in-app", providerId: required(input.providerId || input.channelType || "in-app", "providerId"),
    endpointRef: input.channelType === "in-app" || !input.channelType ? String(input.endpointRef || "") : opaque(input.endpointRef, "endpointRef", "secret-ref:"), payloadRef: opaque(input.payloadRef, "payloadRef", "payload-ref:"),
    alertIdempotencyKey: String(input.alertIdempotencyKey || `diligence-reminder:${organizationId}:${workflowId}:${taskId}:${kind}:${scheduledAt}`),
    status: JOB_STATUSES.includes(input.status) ? input.status : "queued", attemptNumber: Math.max(0, Math.trunc(Number(input.attemptNumber) || 0)), maxAttempts: Math.max(1, Math.trunc(Number(input.maxAttempts) || 5)), nextAttemptAt: iso(input.nextAttemptAt || scheduledAt, "nextAttemptAt"), lease: normalizeLease(input.lease),
    alertDeliveryAttemptId: String(input.alertDeliveryAttemptId || ""), lastErrorCode: String(input.lastErrorCode || ""), lastErrorMessage: String(input.lastErrorMessage || ""), createdAt, updatedAt: iso(input.updatedAt || createdAt, "updatedAt"), emittedAt: input.emittedAt ? iso(input.emittedAt, "emittedAt") : "",
  };
}

export function createDiligenceReminderWorkerState(input = {}) {
  const organizationId = required(input.organizationId, "organizationId"); const jobs = (input.jobs || []).map(createDiligenceReminderJob);
  if (jobs.some((item) => item.organizationId !== organizationId)) throw error("WR_TENANT_ISOLATION_VIOLATION", "Reminder job belongs to another organization");
  return { schemaVersion: DILIGENCE_REMINDER_WORKER_STATE_VERSION, organizationId, revision: Math.max(1, Math.trunc(Number(input.revision) || 1)), jobs, deadLetters: (input.deadLetters || []).map((item) => ({ ...item, schemaVersion: DILIGENCE_REMINDER_DEAD_LETTER_VERSION })), updatedAt: iso(input.updatedAt, "updatedAt") };
}

export function buildDiligenceReminderJobs(workflowInput, options = {}) {
  const workflow = createDiligenceWorkflow(workflowInput), createdAt = iso(options.createdAt, "createdAt"); if (typeof options.recipientForTask !== "function") throw new TypeError("recipientForTask is required"); if (typeof options.payloadRefForJob !== "function") throw new TypeError("payloadRefForJob is required"); const jobs = [];
  for (const task of workflow.tasks.filter((item) => !["completed", "waived"].includes(item.status) && item.criticalDate.status === "calculated")) {
    const routing = options.recipientForTask(task); if (!routing) continue;
    const schedules = [...task.reminderOffsetsSeconds.map((offset) => ({ kind: "reminder", scheduledAt: new Date(new Date(task.criticalDate.dueAt).getTime() - offset * 1000).toISOString() })), { kind: "escalation", scheduledAt: new Date(new Date(task.criticalDate.dueAt).getTime() + task.escalationAfterSeconds * 1000).toISOString() }];
    for (const schedule of schedules) jobs.push(createDiligenceReminderJob({ organizationId: workflow.organizationId, workflowId: workflow.id, workflowSha256: workflow.workflowSha256, taskId: task.id, kind: schedule.kind, scheduledAt: schedule.scheduledAt, recipientRef: routing.recipientRef, subscriptionId: routing.subscriptionId, channelType: routing.channelType, providerId: routing.providerId, endpointRef: routing.endpointRef, payloadRef: options.payloadRefForJob({ workflow, task, ...schedule }), createdAt, maxAttempts: options.maxAttempts }));
  }
  return Object.freeze(jobs.sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt) || a.id.localeCompare(b.id)));
}

export function enqueueDiligenceReminderJobs(stateInput, jobsInput = [], options = {}) {
  const state = createDiligenceReminderWorkerState(stateInput), additions = [];
  for (const raw of jobsInput) { const job = createDiligenceReminderJob(raw); if (job.organizationId !== state.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Reminder job belongs to another organization"); const existing = [...state.jobs, ...additions].find((item) => item.id === job.id || item.alertIdempotencyKey === job.alertIdempotencyKey); if (existing) { if (existing.workflowSha256 !== job.workflowSha256 || existing.payloadRef !== job.payloadRef || existing.recipientRef !== job.recipientRef) throw error("WR_DILIGENCE_REMINDER_IDEMPOTENCY_CONFLICT", "Reminder idempotency key was reused with different evidence"); continue; } additions.push(job); }
  if (!additions.length) return state; const updatedAt = iso(options.updatedAt || additions[0].createdAt, "updatedAt"); if (new Date(updatedAt) < new Date(state.updatedAt)) throw error("WR_DILIGENCE_REMINDER_TIME_REGRESSION", "Reminder state cannot move backward in time"); return { ...state, revision: state.revision + 1, jobs: [...state.jobs, ...additions], updatedAt };
}

export function cancelStaleDiligenceReminders(stateInput, workflowInput, options = {}) {
  const state = createDiligenceReminderWorkerState(stateInput), workflow = createDiligenceWorkflow(workflowInput); if (state.organizationId !== workflow.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Reminder state and workflow organizations do not match"); const cancelledAt = iso(options.cancelledAt, "cancelledAt"), taskMap = new Map(workflow.tasks.map((item) => [item.id, item])); let changed = false;
  const jobs = state.jobs.map((job) => { const task = taskMap.get(job.taskId); const stale = job.workflowId === workflow.id && !["emitted", "dead-lettered", "cancelled"].includes(job.status) && (job.workflowSha256 !== workflow.workflowSha256 || !task || ["completed", "waived"].includes(task.status)); if (!stale) return job; changed = true; return { ...job, status: "cancelled", lease: null, updatedAt: cancelledAt, lastErrorCode: "workflow-superseded", lastErrorMessage: "Workflow revision or task status superseded this reminder" }; });
  return changed ? { ...state, revision: state.revision + 1, jobs, updatedAt: cancelledAt } : state;
}

export function leaseDiligenceReminderJobs(stateInput, options = {}) {
  const state = createDiligenceReminderWorkerState(stateInput), now = iso(options.now, "now"), nowMs = new Date(now).getTime(), workerId = required(options.workerId, "workerId"), leaseSeconds = Math.max(1, Number(options.leaseSeconds) || 60), limit = Math.max(1, Math.trunc(Number(options.limit) || 25)), jobs = state.jobs.map((item) => ({ ...item }));
  const candidates = jobs.filter((job) => !["emitted", "dead-lettered", "cancelled"].includes(job.status) && !(job.status === "leased" && new Date(job.lease?.expiresAt || 0).getTime() > nowMs) && new Date(job.nextAttemptAt).getTime() <= nowMs).sort((a, b) => a.nextAttemptAt.localeCompare(b.nextAttemptAt) || a.id.localeCompare(b.id)); const leasedJobs = [], recoveredLeaseJobIds = [];
  for (const job of candidates.slice(0, limit)) { if (job.status === "leased") recoveredLeaseJobIds.push(job.id); job.status = "leased"; job.attemptNumber += 1; job.lease = Object.freeze({ token: stableId("diligence_lease", `${job.id}|${workerId}|${now}|${state.revision}`), workerId, leasedAt: now, expiresAt: new Date(nowMs + leaseSeconds * 1000).toISOString() }); job.updatedAt = now; leasedJobs.push(createDiligenceReminderJob(job)); }
  return Object.freeze({ schemaVersion: DILIGENCE_REMINDER_WORKER_CYCLE_VERSION, state: leasedJobs.length ? { ...state, revision: state.revision + 1, jobs, updatedAt: now } : state, workerId, evaluatedAt: now, leasedJobs, recoveredLeaseJobIds });
}

export async function emitDiligenceReminder(jobInput, adapter) {
  const job = createDiligenceReminderJob(jobInput); if (job.status !== "leased" || !job.lease) throw new TypeError("Only a leased reminder job can emit"); if (!adapter?.resolveWorkflow) throw new TypeError("adapter.resolveWorkflow is required"); if (!adapter?.enqueueDeliveryAttempt) throw new TypeError("adapter.enqueueDeliveryAttempt is required");
  try { const workflow = createDiligenceWorkflow(await adapter.resolveWorkflow(job.workflowId, job.organizationId)); const task = workflow.tasks.find((item) => item.id === job.taskId); if (workflow.organizationId !== job.organizationId) throw error("WR_TENANT_ISOLATION_VIOLATION", "Resolved reminder workflow belongs to another organization"); if (workflow.workflowSha256 !== job.workflowSha256 || !task || ["completed", "waived"].includes(task.status)) return Object.freeze({ success: false, cancelled: true, retryable: false, deliveryAttemptId: "", errorCode: "workflow-superseded", errorMessage: "Workflow revision or task status superseded this reminder" }); } catch (cause) { if (cause?.code === "WR_TENANT_ISOLATION_VIOLATION") return Object.freeze({ success: false, cancelled: false, retryable: false, deliveryAttemptId: "", errorCode: cause.code, errorMessage: cause.message }); return Object.freeze({ success: false, cancelled: false, retryable: true, deliveryAttemptId: "", errorCode: String(cause?.code || "workflow-resolution-failed"), errorMessage: String(cause?.message || cause) }); }
  const request = Object.freeze({ organizationId: job.organizationId, reminderJobId: job.id, deliveryAttemptId: stableId("diligence_delivery", job.alertIdempotencyKey), alertEnvelopeId: stableId("diligence_alert", job.alertIdempotencyKey), subscriptionId: job.subscriptionId, channelType: job.channelType, providerId: job.providerId, endpointRef: job.endpointRef, payloadRef: job.payloadRef, recipientRef: job.recipientRef, providerIdempotencyKey: job.alertIdempotencyKey });
  try { const result = await adapter.enqueueDeliveryAttempt(request); return Object.freeze({ success: result?.success === true, retryable: result?.success === true ? false : result?.retryable !== false, deliveryAttemptId: String(result?.deliveryAttemptId || request.deliveryAttemptId), errorCode: String(result?.errorCode || ""), errorMessage: String(result?.errorMessage || "") }); } catch (cause) { return Object.freeze({ success: false, retryable: true, deliveryAttemptId: "", errorCode: String(cause?.code || "adapter-exception"), errorMessage: String(cause?.message || cause) }); }
}

export function completeDiligenceReminderJob(stateInput, input = {}, options = {}) {
  const state = createDiligenceReminderWorkerState(stateInput), completedAt = iso(options.completedAt, "completedAt"), index = state.jobs.findIndex((item) => item.id === input.jobId); if (index < 0) throw new TypeError(`Unknown reminder job: ${input.jobId}`); const current = state.jobs[index]; if (current.status !== "leased" || !current.lease) throw new TypeError("Reminder job is not leased"); if (current.lease.workerId !== options.workerId || current.lease.token !== options.leaseToken) throw error("WR_DILIGENCE_REMINDER_LEASE_CONFLICT", "Reminder lease ownership conflict"); if (new Date(current.lease.expiresAt) < new Date(completedAt)) throw error("WR_DILIGENCE_REMINDER_LEASE_EXPIRED", "Reminder lease expired before completion");
  const result = input.result || {}, jobs = [...state.jobs], deadLetters = [...state.deadLetters]; let next;
  if (result.cancelled === true) next = { ...current, status: "cancelled", lease: null, lastErrorCode: String(result.errorCode || "workflow-superseded"), lastErrorMessage: String(result.errorMessage || ""), updatedAt: completedAt };
  else if (result.success === true) next = { ...current, status: "emitted", lease: null, alertDeliveryAttemptId: required(result.deliveryAttemptId, "deliveryAttemptId"), lastErrorCode: "", lastErrorMessage: "", emittedAt: completedAt, updatedAt: completedAt };
  else if (result.retryable !== false && current.attemptNumber < current.maxAttempts) { const base = Math.max(1, Number(options.baseDelaySeconds) || 30), cap = Math.max(base, Number(options.maxDelaySeconds) || 3600), delay = Math.min(cap, base * 2 ** Math.max(0, current.attemptNumber - 1)); next = { ...current, status: "retry-scheduled", lease: null, nextAttemptAt: new Date(new Date(completedAt).getTime() + delay * 1000).toISOString(), lastErrorCode: String(result.errorCode || "alert-enqueue-failed"), lastErrorMessage: String(result.errorMessage || ""), updatedAt: completedAt }; }
  else { next = { ...current, status: "dead-lettered", lease: null, lastErrorCode: String(result.errorCode || "alert-enqueue-failed"), lastErrorMessage: String(result.errorMessage || ""), updatedAt: completedAt }; deadLetters.push(Object.freeze({ schemaVersion: DILIGENCE_REMINDER_DEAD_LETTER_VERSION, id: stableId("diligence_dead_letter", `${current.id}|${current.attemptNumber}|${completedAt}`), organizationId: current.organizationId, jobId: current.id, workflowId: current.workflowId, taskId: current.taskId, errorCode: next.lastErrorCode, errorMessage: next.lastErrorMessage, deadLetteredAt: completedAt })); }
  jobs[index] = next; return { ...state, revision: state.revision + 1, jobs, deadLetters, updatedAt: completedAt };
}

function persist(repository, context, state, options) { return repository.commit({ context, namespace: "diligence", key: "reminder-worker", value: state, expectedTenantRevision: options.expectedTenantRevision, expectedRecordRevision: options.expectedRecordRevision, idempotencyKey: options.idempotencyKey, occurredAt: options.occurredAt }, options.validation); }

export async function runDiligenceReminderWorkerCycle(options = {}) {
  const repository = options.repository; if (!repository?.readRecord || !repository?.tenantRevision || !repository?.commit) throw new TypeError("A durable repository is required"); const context = options.context, workerId = required(options.workerId, "workerId"), now = iso(options.now, "now"), validation = { now }; const stored = repository.readRecord(context, "diligence", "reminder-worker", validation), initial = stored?.value || createDiligenceReminderWorkerState({ organizationId: context.organizationId, updatedAt: now }), cycle = leaseDiligenceReminderJobs(initial, { now, workerId, leaseSeconds: options.leaseSeconds, limit: options.limit });
  if (!cycle.leasedJobs.length) return Object.freeze({ schemaVersion: DILIGENCE_REMINDER_RUN_VERSION, organizationId: context.organizationId, workerId, startedAt: now, completedAt: now, leasedJobIds: [], emittedJobIds: [], retryScheduledJobIds: [], deadLetteredJobIds: [], recoveredLeaseJobIds: cycle.recoveredLeaseJobIds, leaseReceipt: null, completionReceipt: null });
  const tenantRevision = repository.tenantRevision(context, validation), batchId = stableId("batch", cycle.leasedJobs.map((item) => item.id).sort().join("|")), leaseReceipt = persist(repository, context, cycle.state, { expectedTenantRevision: tenantRevision, expectedRecordRevision: Number(stored?.revision || 0), idempotencyKey: `diligence-reminder-lease:${context.organizationId}:${workerId}:${now}:${batchId}`, occurredAt: now, validation }); let completedState = cycle.state; const emittedJobIds = [], retryScheduledJobIds = [], deadLetteredJobIds = [];
  for (const job of cycle.leasedJobs) { const completedAt = iso(options.clock ? options.clock() : now, "completedAt"), result = await emitDiligenceReminder(job, options.adapter); completedState = completeDiligenceReminderJob(completedState, { jobId: job.id, result }, { workerId, leaseToken: job.lease.token, completedAt, baseDelaySeconds: options.baseDelaySeconds, maxDelaySeconds: options.maxDelaySeconds }); const status = completedState.jobs.find((item) => item.id === job.id)?.status; if (status === "emitted") emittedJobIds.push(job.id); if (status === "retry-scheduled") retryScheduledJobIds.push(job.id); if (status === "dead-lettered") deadLetteredJobIds.push(job.id); }
  const completedAt = iso(options.clock ? options.clock() : now, "completedAt"), completionReceipt = persist(repository, context, completedState, { expectedTenantRevision: leaseReceipt.tenantRevision, expectedRecordRevision: leaseReceipt.recordRevision, idempotencyKey: `diligence-reminder-complete:${context.organizationId}:${workerId}:${now}:${batchId}`, occurredAt: completedAt, validation: { now: completedAt } }); return Object.freeze({ schemaVersion: DILIGENCE_REMINDER_RUN_VERSION, organizationId: context.organizationId, workerId, startedAt: now, completedAt, leasedJobIds: cycle.leasedJobs.map((item) => item.id), emittedJobIds, retryScheduledJobIds, deadLetteredJobIds, recoveredLeaseJobIds: cycle.recoveredLeaseJobIds, leaseReceipt, completionReceipt });
}
