export const BUSINESS_CALENDAR_VERSION: "wr-business-calendar-v1";
export const DILIGENCE_TEMPLATE_TASK_VERSION: "wr-diligence-template-task-v1";
export const DILIGENCE_CHECKLIST_TEMPLATE_VERSION: "wr-diligence-checklist-template-v1";
export const DILIGENCE_EVIDENCE_RECEIPT_VERSION: "wr-diligence-evidence-receipt-v1";
export const DILIGENCE_CRITICAL_DATE_VERSION: "wr-diligence-critical-date-v1";
export const DILIGENCE_TASK_VERSION: "wr-diligence-task-v1";
export const DILIGENCE_HISTORY_EVENT_VERSION: "wr-diligence-history-event-v1";
export const DILIGENCE_WORKFLOW_VERSION: "wr-diligence-workflow-v1";
export const DILIGENCE_SLA_REPORT_VERSION: "wr-diligence-sla-report-v1";
export function diligenceSha256(value: unknown): string;
export function createBusinessCalendar(input?: Record<string, any>): Readonly<Record<string, any>>;
export function addBusinessDays(startDate: string, amount: number, calendar: Record<string, any>): string;
export function createDiligenceTemplateTask(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createDiligenceChecklistTemplate(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createDiligenceEvidenceReceipt(input?: Record<string, any>): Readonly<Record<string, any>>;
export function createDiligenceWorkflow(input?: Record<string, any>): Readonly<Record<string, any>>;
export function instantiateDiligenceWorkflow(input?: Record<string, any>): Readonly<Record<string, any>>;
export function startDiligenceTask(workflow: Record<string, any>, taskId: string, context?: Record<string, any>): Readonly<Record<string, any>>;
export function completeDiligenceTask(workflow: Record<string, any>, taskId: string, receipts?: Array<Record<string, any>>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function waiveDiligenceTask(workflow: Record<string, any>, taskId: string, approvalReceipts?: Array<Record<string, any>>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function updateDiligenceAnchor(workflow: Record<string, any>, input?: Record<string, any>, context?: Record<string, any>): Readonly<Record<string, any>>;
export function evaluateDiligenceSla(workflow: Record<string, any>, options?: Record<string, any>): Readonly<Record<string, any>>;
